// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ActivityService is the Wails service exposing the desktop's activity log to
 * the frontend: the Activity view reads pages of events through List, and the
 * UI records its own events through Record. Backend subsystems don't go through
 * here — they hold the activity.Recorder directly (see main.go's wiring).
 * 
 * Like FlowsService and PipelineService, this is thin wire glue; the real logic
 * lives in internal/desktop/activity.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as activity$0 from "../internal/desktop/activity/models.js";

/**
 * List returns up to limit activity events with id < before, newest first.
 * Pass before <= 0 (and the frontend passes 0 for the first page) to start from
 * the most recent event; page older history by passing the smallest id seen.
 */
export function List(before: number, limit: number): $CancellablePromise<activity$0.Event[] | null> {
    return $Call.ByID(2874726812, before, limit);
}

/**
 * Record appends a frontend-originated event and returns the stored row. This
 * is the UI's path for surfacing things only it knows about (a failed save, a
 * deleted profile); it emits the same activity:appended wake-up as backend
 * recording, so every open Activity view refreshes.
 */
export function Record(input: activity$0.RecordInput): $CancellablePromise<activity$0.Event> {
    return $Call.ByID(1202621025, input);
}
