// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ActionsService is the explicit editor API for the global actions catalog.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as actions$0 from "../internal/desktop/pipeline/actions/models.js";

export function CreateAction(a: actions$0.EditableAction): $CancellablePromise<actions$0.EditableAction> {
    return $Call.ByID(186567676, a);
}

export function DeleteAction(id: string): $CancellablePromise<void> {
    return $Call.ByID(2044407527, id);
}

export function GetAction(id: string): $CancellablePromise<actions$0.EditableAction> {
    return $Call.ByID(1390017604, id);
}

/**
 * ListActions returns the effective last-good catalog and a current parse
 * error, if a hand edit made the latest actions.yml invalid.
 */
export function ListActions(): $CancellablePromise<actions$0.EditableCatalog> {
    return $Call.ByID(363974597);
}

export function UpdateAction(id: string, a: actions$0.EditableAction): $CancellablePromise<actions$0.EditableAction> {
    return $Call.ByID(2719986457, id, a);
}
