// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export type {
    EditableAction,
    EditableCatalog,
    EditableClipboardConfig,
    EditableLaunchConfig,
    EditableMessageConfig,
    EditableShellConfig,
    InputSpec,
    Launcher,
    View
} from "./models.js";
