// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EditableAction is the explicit, non-executable editor contract exposed to
 * desktop clients. Exactly one config branch must be set and it must match
 * Type; callers cannot send an untyped executable blob.
 */
export interface EditableAction {
    "id": string;
    "label": string;
    "type": string;
    "showInDetail": boolean;
    "appliesTo": string[] | null;
    "inputs"?: InputSpec[] | null;
    "launch"?: EditableLaunchConfig | null;
    "shell"?: EditableShellConfig | null;
    "message"?: EditableMessageConfig | null;
    "clipboard"?: EditableClipboardConfig | null;
}

/**
 * EditableCatalog returns the effective last-good catalog and any error from
 * parsing the latest file. It lets the settings UI remain useful while making
 * a hand-edited malformed actions.yml visible to the user.
 */
export interface EditableCatalog {
    "actions": EditableAction[] | null;
    "error": string;
}

export interface EditableClipboardConfig {
    "textTemplate": string;
}

export interface EditableLaunchConfig {
    "promptTemplate": string;
    "agent"?: string;
    "repoTemplate"?: string;
}

export interface EditableMessageConfig {
    "messageTemplate": string;
    "topic": string;
}

export interface EditableShellConfig {
    "commandTemplate": string;
    "cwd"?: string;
    "timeout"?: string;
    "env"?: { [_ in string]?: string } | null;
}

/**
 * InputSpec declares one value collected from the user when an action is
 * invoked, exposed to every template that action renders as
 * `{{ .Inputs.<name> }}`.
 * 
 * Inputs are an envelope field rather than per-type config: every action type
 * renders over the same OutputData, so one declaration gives a new action type
 * the invocation form with nothing further to wire (ADR 0043).
 */
export interface InputSpec {
    /**
     * Name is the template key: `{{ .Inputs.<name> }}`.
     */
    "name": string;

    /**
     * Label is the form field's caption; the name is shown when it is empty.
     */
    "label": string;

    /**
     * Type selects the control: text, select, or multiline.
     */
    "type": string;

    /**
     * Required rejects an invocation whose value is blank.
     */
    "required": boolean;

    /**
     * Default prefills the form and supplies the value when none is given.
     */
    "default": string;

    /**
     * Placeholder is the hint shown in an empty text or multiline control.
     */
    "placeholder": string;

    /**
     * Options is the closed value set of a select input.
     */
    "options": string[] | null;
}

/**
 * View is the complete action contract exposed to the desktop frontend. It
 * deliberately excludes executable configuration: the frontend can present
 * and identify an action, but execution always resolves its current
 * definition from ActionStore.
 */
export interface View {
    "id": string;
    "label": string;
    "type": string;
    "showInDetail": boolean;
    "requiresSessionInput": boolean;
    "inputs"?: InputSpec[] | null;
}
