// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EditableAction is the explicit, non-executable editor contract exposed to
 * desktop clients. Exactly one config branch must be set and it must match
 * Type; callers cannot send an untyped executable blob.
 */
export interface EditableAction {
    "id": string;
    "label": string;
    "type": string;
    "showInDetail": boolean;

    /**
     * Targets is always explicit on the wire — an action that declares none
     * is an item action, and the editor renders a checked box rather than an
     * empty one it would have to explain.
     */
    "targets": string[] | null;
    "appliesTo": string[] | null;
    "inputs"?: InputSpec[] | null;
    "launch"?: EditableLaunchConfig | null;
    "shell"?: EditableShellConfig | null;
    "message"?: EditableMessageConfig | null;
    "clipboard"?: EditableClipboardConfig | null;
}

/**
 * EditableCatalog returns the effective last-good catalog and any error from
 * parsing the latest file. It lets the settings UI remain useful while making
 * a hand-edited malformed actions.yml visible to the user.
 * 
 * Launchers ride along rather than getting a read of their own: they are the
 * other list in the same file, so one parse answers for both and a single
 * Error describes whatever is wrong with it.
 */
export interface EditableCatalog {
    "actions": EditableAction[] | null;
    "launchers": Launcher[] | null;
    "error": string;
}

export interface EditableClipboardConfig {
    "textTemplate": string;
}

export interface EditableLaunchConfig {
    "promptTemplate": string;
    "agent"?: string;
    "repoTemplate"?: string;
    "postHook"?: string;
    "postHookTimeout"?: string;
}

export interface EditableMessageConfig {
    "messageTemplate": string;
    "topic": string;
}

export interface EditableShellConfig {
    "commandTemplate": string;
    "cwd"?: string;
    "timeout"?: string;
    "env"?: { [_ in string]?: string } | null;
}

/**
 * InputSpec declares one value collected from the user when an action is
 * invoked, exposed to every template that action renders as
 * `{{ .Inputs.<name> }}`.
 * 
 * Inputs are an envelope field rather than per-type config: every action type
 * renders over the same OutputData, so one declaration gives a new action type
 * the invocation form with nothing further to wire (ADR action-declared-inputs).
 */
export interface InputSpec {
    /**
     * Name is the template key: `{{ .Inputs.<name> }}`.
     */
    "name": string;

    /**
     * Label is the form field's caption; the name is shown when it is empty.
     */
    "label": string;

    /**
     * Type selects the control: text, select, or multiline.
     */
    "type": string;

    /**
     * Required rejects an invocation whose value is blank.
     */
    "required": boolean;

    /**
     * Default prefills the form and supplies the value when none is given.
     */
    "default": string;

    /**
     * Placeholder is the hint shown in an empty text or multiline control.
     */
    "placeholder": string;

    /**
     * Options is the closed value set of a select input.
     */
    "options": string[] | null;
}

/**
 * Launcher is a named command that opens in the pop-up terminal (ADR ephemeral-popup-terminals),
 * reached from the command palette or a keybinding of its own.
 * 
 * It shares actions.yml with the action catalog — one file, one loader, one
 * watcher, one place a user edits — but it is not an action and does not
 * pretend to be one: it never reaches the dispatcher, has no executor, no exit
 * status and no job, and none of the action envelope (`targets`, `applies_to`,
 * `show_in_detail`, `inputs`) means anything to it (ADR launchers-are-their-own-list-in-actions-yml).
 * 
 * Neither Command nor Cwd is a template. There is no triggering item to render
 * over, and none is needed: the command runs through a login shell in the
 * working directory, so a user's PATH, aliases, functions and $PWD already
 * resolve it.
 */
export interface Launcher {
    /**
     * ID names the launcher, and is what its bindable command id is built from
     * — `launcher.<id>` in settings.yaml's keybindings.
     */
    "id": string;

    /**
     * Label is the human-readable name shown in the command palette.
     */
    "label": string;

    /**
     * Command is the shell command line the terminal opens into.
     */
    "command": string;

    /**
     * Cwd pins the launcher to one directory, and is what makes a launcher
     * reachable with no session open. Empty means the checkout of the session on
     * screen — the launcher follows the session you are in, and is offered only
     * while you are in one (ADR quick-terminal-launchers-are-session-scoped).
     */
    "cwd"?: string;

    /**
     * Icon is the glyph the command palette shows, from the launcher set in
     * internal/app/icons. Empty means the terminal glyph.
     */
    "icon"?: string;
}

/**
 * View is the complete action contract exposed to the desktop frontend. It
 * deliberately excludes executable configuration: the frontend can present
 * and identify an action, but execution always resolves its current
 * definition from ActionStore.
 */
export interface View {
    "id": string;
    "label": string;
    "type": string;
    "showInDetail": boolean;
    "requiresSessionInput": boolean;
    "inputs"?: InputSpec[] | null;
}
