// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_workspace_session.sql

package queries

import (
	"context"
)

const deleteAgentWorkspaceSession = `-- name: DeleteAgentWorkspaceSession :exec
DELETE FROM agent_workspace_session WHERE id = ?
`

func (q *Queries) DeleteAgentWorkspaceSession(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAgentWorkspaceSession, id)
	return err
}

const deleteAgentWorkspaceSessionsByWorkspace = `-- name: DeleteAgentWorkspaceSessionsByWorkspace :exec
DELETE FROM agent_workspace_session WHERE workspace = ?
`

func (q *Queries) DeleteAgentWorkspaceSessionsByWorkspace(ctx context.Context, workspace string) error {
	_, err := q.db.ExecContext(ctx, deleteAgentWorkspaceSessionsByWorkspace, workspace)
	return err
}

const getAgentWorkspaceSession = `-- name: GetAgentWorkspaceSession :one
SELECT id, workspace, name, agent, agent_session_id, created_at, last_opened_at, schedule_id, end_token FROM agent_workspace_session WHERE id = ?
`

func (q *Queries) GetAgentWorkspaceSession(ctx context.Context, id int64) (AgentWorkspaceSession, error) {
	row := q.db.QueryRowContext(ctx, getAgentWorkspaceSession, id)
	var i AgentWorkspaceSession
	err := row.Scan(
		&i.ID,
		&i.Workspace,
		&i.Name,
		&i.Agent,
		&i.AgentSessionID,
		&i.CreatedAt,
		&i.LastOpenedAt,
		&i.ScheduleID,
		&i.EndToken,
	)
	return i, err
}

const getAgentWorkspaceSessionByEndToken = `-- name: GetAgentWorkspaceSessionByEndToken :one
SELECT id, workspace, name, agent, agent_session_id, created_at, last_opened_at, schedule_id, end_token FROM agent_workspace_session WHERE end_token = ? AND end_token <> ''
`

// The session a launch handed this token to. An empty token matches nothing:
// a row from before the column existed must not answer for a blank bearer.
func (q *Queries) GetAgentWorkspaceSessionByEndToken(ctx context.Context, endToken string) (AgentWorkspaceSession, error) {
	row := q.db.QueryRowContext(ctx, getAgentWorkspaceSessionByEndToken, endToken)
	var i AgentWorkspaceSession
	err := row.Scan(
		&i.ID,
		&i.Workspace,
		&i.Name,
		&i.Agent,
		&i.AgentSessionID,
		&i.CreatedAt,
		&i.LastOpenedAt,
		&i.ScheduleID,
		&i.EndToken,
	)
	return i, err
}

const insertAgentWorkspaceSession = `-- name: InsertAgentWorkspaceSession :one
INSERT INTO agent_workspace_session (workspace, name, agent, agent_session_id, created_at, last_opened_at, schedule_id, end_token)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, workspace, name, agent, agent_session_id, created_at, last_opened_at, schedule_id, end_token
`

type InsertAgentWorkspaceSessionParams struct {
	Workspace      string `json:"workspace"`
	Name           string `json:"name"`
	Agent          string `json:"agent"`
	AgentSessionID string `json:"agent_session_id"`
	CreatedAt      int64  `json:"created_at"`
	LastOpenedAt   int64  `json:"last_opened_at"`
	ScheduleID     string `json:"schedule_id"`
	EndToken       string `json:"end_token"`
}

func (q *Queries) InsertAgentWorkspaceSession(ctx context.Context, arg InsertAgentWorkspaceSessionParams) (AgentWorkspaceSession, error) {
	row := q.db.QueryRowContext(ctx, insertAgentWorkspaceSession,
		arg.Workspace,
		arg.Name,
		arg.Agent,
		arg.AgentSessionID,
		arg.CreatedAt,
		arg.LastOpenedAt,
		arg.ScheduleID,
		arg.EndToken,
	)
	var i AgentWorkspaceSession
	err := row.Scan(
		&i.ID,
		&i.Workspace,
		&i.Name,
		&i.Agent,
		&i.AgentSessionID,
		&i.CreatedAt,
		&i.LastOpenedAt,
		&i.ScheduleID,
		&i.EndToken,
	)
	return i, err
}

const listAgentWorkspaceSessions = `-- name: ListAgentWorkspaceSessions :many
SELECT id, workspace, name, agent, agent_session_id, created_at, last_opened_at, schedule_id, end_token FROM agent_workspace_session
WHERE workspace = ?
ORDER BY id DESC
`

// One workspace's sessions, newest record first. Creation order on purpose,
// not last_opened_at: resuming a chat must not reshuffle the sidebar under
// the pointer.
func (q *Queries) ListAgentWorkspaceSessions(ctx context.Context, workspace string) ([]AgentWorkspaceSession, error) {
	rows, err := q.db.QueryContext(ctx, listAgentWorkspaceSessions, workspace)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentWorkspaceSession{}
	for rows.Next() {
		var i AgentWorkspaceSession
		if err := rows.Scan(
			&i.ID,
			&i.Workspace,
			&i.Name,
			&i.Agent,
			&i.AgentSessionID,
			&i.CreatedAt,
			&i.LastOpenedAt,
			&i.ScheduleID,
			&i.EndToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllAgentWorkspaceSessions = `-- name: ListAllAgentWorkspaceSessions :many
SELECT id, workspace, name, agent, agent_session_id, created_at, last_opened_at, schedule_id, end_token FROM agent_workspace_session
ORDER BY id DESC
`

// Every session across every workspace, newest record first: the same
// stable creation order the scoped list uses.
func (q *Queries) ListAllAgentWorkspaceSessions(ctx context.Context) ([]AgentWorkspaceSession, error) {
	rows, err := q.db.QueryContext(ctx, listAllAgentWorkspaceSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentWorkspaceSession{}
	for rows.Next() {
		var i AgentWorkspaceSession
		if err := rows.Scan(
			&i.ID,
			&i.Workspace,
			&i.Name,
			&i.Agent,
			&i.AgentSessionID,
			&i.CreatedAt,
			&i.LastOpenedAt,
			&i.ScheduleID,
			&i.EndToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameAgentWorkspaceSession = `-- name: RenameAgentWorkspaceSession :exec
UPDATE agent_workspace_session SET name = ? WHERE id = ?
`

type RenameAgentWorkspaceSessionParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) RenameAgentWorkspaceSession(ctx context.Context, arg RenameAgentWorkspaceSessionParams) error {
	_, err := q.db.ExecContext(ctx, renameAgentWorkspaceSession, arg.Name, arg.ID)
	return err
}

const setAgentWorkspaceSessionAgentID = `-- name: SetAgentWorkspaceSessionAgentID :exec
UPDATE agent_workspace_session SET agent_session_id = ? WHERE id = ?
`

type SetAgentWorkspaceSessionAgentIDParams struct {
	AgentSessionID string `json:"agent_session_id"`
	ID             int64  `json:"id"`
}

// The only write to agent_session_id after the insert: a resume that falls
// back to a fresh launch (the agent has no resume form) mints a new id and
// records it here so a later resume of this same record addresses the
// conversation actually running rather than the one it replaced.
func (q *Queries) SetAgentWorkspaceSessionAgentID(ctx context.Context, arg SetAgentWorkspaceSessionAgentIDParams) error {
	_, err := q.db.ExecContext(ctx, setAgentWorkspaceSessionAgentID, arg.AgentSessionID, arg.ID)
	return err
}

const touchAgentWorkspaceSession = `-- name: TouchAgentWorkspaceSession :exec
UPDATE agent_workspace_session SET last_opened_at = ? WHERE id = ?
`

type TouchAgentWorkspaceSessionParams struct {
	LastOpenedAt int64 `json:"last_opened_at"`
	ID           int64 `json:"id"`
}

func (q *Queries) TouchAgentWorkspaceSession(ctx context.Context, arg TouchAgentWorkspaceSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchAgentWorkspaceSession, arg.LastOpenedAt, arg.ID)
	return err
}
