// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inbox_item.sql

package queries

import (
	"context"
	"database/sql"
)

const countInboxItemsByFeed = `-- name: CountInboxItemsByFeed :many
SELECT
    c.feed_id AS feed_id,
    CAST(COUNT(DISTINCT CASE WHEN i.archived_at IS NULL THEN i.id END) AS INTEGER) AS total,
    CAST(COUNT(DISTINCT CASE WHEN i.archived_at IS NULL AND i.unread = 1 THEN i.id END) AS INTEGER) AS unread,
    CAST(COUNT(DISTINCT CASE WHEN i.archived_at IS NOT NULL THEN i.id END) AS INTEGER) AS archived
FROM feed_membership_claim c
JOIN inbox_item i ON i.id = c.item_id
WHERE c.profile_id = ? AND i.ignored_at IS NULL
GROUP BY c.feed_id
`

type CountInboxItemsByFeedRow struct {
	FeedID   string `json:"feed_id"`
	Total    int64  `json:"total"`
	Unread   int64  `json:"unread"`
	Archived int64  `json:"archived"`
}

func (q *Queries) CountInboxItemsByFeed(ctx context.Context, profileID string) ([]CountInboxItemsByFeedRow, error) {
	rows, err := q.db.QueryContext(ctx, countInboxItemsByFeed, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountInboxItemsByFeedRow{}
	for rows.Next() {
		var i CountInboxItemsByFeedRow
		if err := rows.Scan(
			&i.FeedID,
			&i.Total,
			&i.Unread,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteInboxItemsByProfile = `-- name: DeleteInboxItemsByProfile :exec
DELETE FROM inbox_item WHERE profile_id = ?
`

func (q *Queries) DeleteInboxItemsByProfile(ctx context.Context, profileID string) error {
	_, err := q.db.ExecContext(ctx, deleteInboxItemsByProfile, profileID)
	return err
}

const findInboxItemsByExternalID = `-- name: FindInboxItemsByExternalID :many
SELECT id, profile_id, source_kind, source_scope, external_id, title, url, payload, revision, unread, archived_at, archived_actor, archived_reason, lifecycle, source_state, first_seen_at, last_event_at, ignored_at FROM inbox_item
WHERE external_id = ?1
  AND (?2 = '' OR profile_id = ?2)
ORDER BY profile_id, source_kind, source_scope
`

type FindInboxItemsByExternalIDParams struct {
	ExternalID string      `json:"external_id"`
	ProfileID  interface{} `json:"profile_id"`
}

func (q *Queries) FindInboxItemsByExternalID(ctx context.Context, arg FindInboxItemsByExternalIDParams) ([]InboxItem, error) {
	rows, err := q.db.QueryContext(ctx, findInboxItemsByExternalID, arg.ExternalID, arg.ProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxItem{}
	for rows.Next() {
		var i InboxItem
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.SourceKind,
			&i.SourceScope,
			&i.ExternalID,
			&i.Title,
			&i.Url,
			&i.Payload,
			&i.Revision,
			&i.Unread,
			&i.ArchivedAt,
			&i.ArchivedActor,
			&i.ArchivedReason,
			&i.Lifecycle,
			&i.SourceState,
			&i.FirstSeenAt,
			&i.LastEventAt,
			&i.IgnoredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInboxItemByExternalID = `-- name: GetInboxItemByExternalID :one
SELECT id, profile_id, source_kind, source_scope, external_id, title, url, payload, revision, unread, archived_at, archived_actor, archived_reason, lifecycle, source_state, first_seen_at, last_event_at, ignored_at FROM inbox_item
WHERE profile_id = ? AND source_kind = ? AND source_scope = ? AND external_id = ?
`

type GetInboxItemByExternalIDParams struct {
	ProfileID   string `json:"profile_id"`
	SourceKind  string `json:"source_kind"`
	SourceScope string `json:"source_scope"`
	ExternalID  string `json:"external_id"`
}

func (q *Queries) GetInboxItemByExternalID(ctx context.Context, arg GetInboxItemByExternalIDParams) (InboxItem, error) {
	row := q.db.QueryRowContext(ctx, getInboxItemByExternalID,
		arg.ProfileID,
		arg.SourceKind,
		arg.SourceScope,
		arg.ExternalID,
	)
	var i InboxItem
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.SourceKind,
		&i.SourceScope,
		&i.ExternalID,
		&i.Title,
		&i.Url,
		&i.Payload,
		&i.Revision,
		&i.Unread,
		&i.ArchivedAt,
		&i.ArchivedActor,
		&i.ArchivedReason,
		&i.Lifecycle,
		&i.SourceState,
		&i.FirstSeenAt,
		&i.LastEventAt,
		&i.IgnoredAt,
	)
	return i, err
}

const getInboxItemByID = `-- name: GetInboxItemByID :one
SELECT id, profile_id, source_kind, source_scope, external_id, title, url, payload, revision, unread, archived_at, archived_actor, archived_reason, lifecycle, source_state, first_seen_at, last_event_at, ignored_at FROM inbox_item WHERE id = ?
`

func (q *Queries) GetInboxItemByID(ctx context.Context, id int64) (InboxItem, error) {
	row := q.db.QueryRowContext(ctx, getInboxItemByID, id)
	var i InboxItem
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.SourceKind,
		&i.SourceScope,
		&i.ExternalID,
		&i.Title,
		&i.Url,
		&i.Payload,
		&i.Revision,
		&i.Unread,
		&i.ArchivedAt,
		&i.ArchivedActor,
		&i.ArchivedReason,
		&i.Lifecycle,
		&i.SourceState,
		&i.FirstSeenAt,
		&i.LastEventAt,
		&i.IgnoredAt,
	)
	return i, err
}

const getUnarchivedInboxItemByID = `-- name: GetUnarchivedInboxItemByID :one
SELECT id, profile_id, source_kind, source_scope, external_id, title, url, payload, revision, unread, archived_at, archived_actor, archived_reason, lifecycle, source_state, first_seen_at, last_event_at, ignored_at FROM inbox_item WHERE id = ? AND profile_id = ? AND archived_at IS NULL
`

type GetUnarchivedInboxItemByIDParams struct {
	ID        int64  `json:"id"`
	ProfileID string `json:"profile_id"`
}

// Every user-facing feed view is claim-scoped: source observations that did
// not reach a feed terminal remain internal pipeline data and never leak into
// workspace categories. Trash is the only exception: it deliberately surfaces
// unrouted and ignored items so users can debug rules and un-ignore.
func (q *Queries) GetUnarchivedInboxItemByID(ctx context.Context, arg GetUnarchivedInboxItemByIDParams) (InboxItem, error) {
	row := q.db.QueryRowContext(ctx, getUnarchivedInboxItemByID, arg.ID, arg.ProfileID)
	var i InboxItem
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.SourceKind,
		&i.SourceScope,
		&i.ExternalID,
		&i.Title,
		&i.Url,
		&i.Payload,
		&i.Revision,
		&i.Unread,
		&i.ArchivedAt,
		&i.ArchivedActor,
		&i.ArchivedReason,
		&i.Lifecycle,
		&i.SourceState,
		&i.FirstSeenAt,
		&i.LastEventAt,
		&i.IgnoredAt,
	)
	return i, err
}

const insertInboxItem = `-- name: InsertInboxItem :one
INSERT INTO inbox_item (
    profile_id, source_kind, source_scope, external_id,
    title, url, payload, revision, unread,
    lifecycle, first_seen_at, last_event_at
) VALUES (
    ?, ?, ?, ?,
    ?, ?, ?, 1, ?,
    ?, ?, ?
)
RETURNING id, profile_id, source_kind, source_scope, external_id, title, url, payload, revision, unread, archived_at, archived_actor, archived_reason, lifecycle, source_state, first_seen_at, last_event_at, ignored_at
`

type InsertInboxItemParams struct {
	ProfileID   string `json:"profile_id"`
	SourceKind  string `json:"source_kind"`
	SourceScope string `json:"source_scope"`
	ExternalID  string `json:"external_id"`
	Title       string `json:"title"`
	Url         string `json:"url"`
	Payload     []byte `json:"payload"`
	Unread      int64  `json:"unread"`
	Lifecycle   string `json:"lifecycle"`
	FirstSeenAt int64  `json:"first_seen_at"`
	LastEventAt int64  `json:"last_event_at"`
}

// Seed-only plain insert for deterministic desktop fixtures. The ingestion
// path receives its classify-and-upsert contract in a later phase.
func (q *Queries) InsertInboxItem(ctx context.Context, arg InsertInboxItemParams) (InboxItem, error) {
	row := q.db.QueryRowContext(ctx, insertInboxItem,
		arg.ProfileID,
		arg.SourceKind,
		arg.SourceScope,
		arg.ExternalID,
		arg.Title,
		arg.Url,
		arg.Payload,
		arg.Unread,
		arg.Lifecycle,
		arg.FirstSeenAt,
		arg.LastEventAt,
	)
	var i InboxItem
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.SourceKind,
		&i.SourceScope,
		&i.ExternalID,
		&i.Title,
		&i.Url,
		&i.Payload,
		&i.Revision,
		&i.Unread,
		&i.ArchivedAt,
		&i.ArchivedActor,
		&i.ArchivedReason,
		&i.Lifecycle,
		&i.SourceState,
		&i.FirstSeenAt,
		&i.LastEventAt,
		&i.IgnoredAt,
	)
	return i, err
}

const listAllInboxItems = `-- name: ListAllInboxItems :many
SELECT id, profile_id, source_kind, source_scope, external_id, title, url, payload, revision, unread, archived_at, archived_actor, archived_reason, lifecycle, source_state, first_seen_at, last_event_at, ignored_at FROM inbox_item
WHERE (?1 = '' OR profile_id = ?1)
ORDER BY last_event_at DESC, id DESC
LIMIT ?2
`

type ListAllInboxItemsParams struct {
	ProfileID interface{} `json:"profile_id"`
	Lim       int64       `json:"lim"`
}

func (q *Queries) ListAllInboxItems(ctx context.Context, arg ListAllInboxItemsParams) ([]InboxItem, error) {
	rows, err := q.db.QueryContext(ctx, listAllInboxItems, arg.ProfileID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxItem{}
	for rows.Next() {
		var i InboxItem
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.SourceKind,
			&i.SourceScope,
			&i.ExternalID,
			&i.Title,
			&i.Url,
			&i.Payload,
			&i.Revision,
			&i.Unread,
			&i.ArchivedAt,
			&i.ArchivedActor,
			&i.ArchivedReason,
			&i.Lifecycle,
			&i.SourceState,
			&i.FirstSeenAt,
			&i.LastEventAt,
			&i.IgnoredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchivedInboxItemsByFeed = `-- name: ListArchivedInboxItemsByFeed :many
SELECT DISTINCT i.id, i.profile_id, i.source_kind, i.source_scope, i.external_id, i.title, i.url, i.payload, i.revision, i.unread, i.archived_at, i.archived_actor, i.archived_reason, i.lifecycle, i.source_state, i.first_seen_at, i.last_event_at, i.ignored_at FROM inbox_item i
JOIN feed_membership_claim c ON c.item_id = i.id
WHERE c.profile_id = ? AND c.feed_id = ? AND i.archived_at IS NOT NULL AND i.ignored_at IS NULL
ORDER BY i.archived_at DESC, i.id DESC LIMIT ?
`

type ListArchivedInboxItemsByFeedParams struct {
	ProfileID string `json:"profile_id"`
	FeedID    string `json:"feed_id"`
	Limit     int64  `json:"limit"`
}

// Archived items stay visible inside the feeds they matched, demoted below
// active rows and lazy-loaded when the archived section expands.
func (q *Queries) ListArchivedInboxItemsByFeed(ctx context.Context, arg ListArchivedInboxItemsByFeedParams) ([]InboxItem, error) {
	rows, err := q.db.QueryContext(ctx, listArchivedInboxItemsByFeed, arg.ProfileID, arg.FeedID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxItem{}
	for rows.Next() {
		var i InboxItem
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.SourceKind,
			&i.SourceScope,
			&i.ExternalID,
			&i.Title,
			&i.Url,
			&i.Payload,
			&i.Revision,
			&i.Unread,
			&i.ArchivedAt,
			&i.ArchivedActor,
			&i.ArchivedReason,
			&i.Lifecycle,
			&i.SourceState,
			&i.FirstSeenAt,
			&i.LastEventAt,
			&i.IgnoredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInboxItemsByFeed = `-- name: ListInboxItemsByFeed :many
SELECT DISTINCT i.id, i.profile_id, i.source_kind, i.source_scope, i.external_id, i.title, i.url, i.payload, i.revision, i.unread, i.archived_at, i.archived_actor, i.archived_reason, i.lifecycle, i.source_state, i.first_seen_at, i.last_event_at, i.ignored_at FROM inbox_item i
JOIN feed_membership_claim c ON c.item_id = i.id
WHERE c.profile_id = ? AND c.feed_id = ? AND i.archived_at IS NULL AND i.ignored_at IS NULL
ORDER BY i.last_event_at DESC, i.id DESC LIMIT ?
`

type ListInboxItemsByFeedParams struct {
	ProfileID string `json:"profile_id"`
	FeedID    string `json:"feed_id"`
	Limit     int64  `json:"limit"`
}

func (q *Queries) ListInboxItemsByFeed(ctx context.Context, arg ListInboxItemsByFeedParams) ([]InboxItem, error) {
	rows, err := q.db.QueryContext(ctx, listInboxItemsByFeed, arg.ProfileID, arg.FeedID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxItem{}
	for rows.Next() {
		var i InboxItem
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.SourceKind,
			&i.SourceScope,
			&i.ExternalID,
			&i.Title,
			&i.Url,
			&i.Payload,
			&i.Revision,
			&i.Unread,
			&i.ArchivedAt,
			&i.ArchivedActor,
			&i.ArchivedReason,
			&i.Lifecycle,
			&i.SourceState,
			&i.FirstSeenAt,
			&i.LastEventAt,
			&i.IgnoredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInboxItemsTrash = `-- name: ListInboxItemsTrash :many
SELECT i.id, i.profile_id, i.source_kind, i.source_scope, i.external_id, i.title, i.url, i.payload, i.revision, i.unread, i.archived_at, i.archived_actor, i.archived_reason, i.lifecycle, i.source_state, i.first_seen_at, i.last_event_at, i.ignored_at FROM inbox_item i
WHERE i.profile_id = ?
  AND (i.ignored_at IS NOT NULL
       OR NOT EXISTS (SELECT 1 FROM feed_membership_claim c WHERE c.profile_id = i.profile_id AND c.item_id = i.id))
ORDER BY i.last_event_at DESC, i.id DESC LIMIT ?
`

type ListInboxItemsTrashParams struct {
	ProfileID string `json:"profile_id"`
	Limit     int64  `json:"limit"`
}

// Trash holds items with no path to any feed (routing produced no claims)
// plus user-ignored items. It is a utility/debug surface, never a queue.
func (q *Queries) ListInboxItemsTrash(ctx context.Context, arg ListInboxItemsTrashParams) ([]InboxItem, error) {
	rows, err := q.db.QueryContext(ctx, listInboxItemsTrash, arg.ProfileID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxItem{}
	for rows.Next() {
		var i InboxItem
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.SourceKind,
			&i.SourceScope,
			&i.ExternalID,
			&i.Title,
			&i.Url,
			&i.Payload,
			&i.Revision,
			&i.Unread,
			&i.ArchivedAt,
			&i.ArchivedActor,
			&i.ArchivedReason,
			&i.Lifecycle,
			&i.SourceState,
			&i.FirstSeenAt,
			&i.LastEventAt,
			&i.IgnoredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnarchivedInboxItemsByProfile = `-- name: ListUnarchivedInboxItemsByProfile :many
SELECT id, profile_id, source_kind, source_scope, external_id, title, url, payload, revision, unread, archived_at, archived_actor, archived_reason, lifecycle, source_state, first_seen_at, last_event_at, ignored_at FROM inbox_item WHERE profile_id = ? AND archived_at IS NULL
`

func (q *Queries) ListUnarchivedInboxItemsByProfile(ctx context.Context, profileID string) ([]InboxItem, error) {
	rows, err := q.db.QueryContext(ctx, listUnarchivedInboxItemsByProfile, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxItem{}
	for rows.Next() {
		var i InboxItem
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.SourceKind,
			&i.SourceScope,
			&i.ExternalID,
			&i.Title,
			&i.Url,
			&i.Payload,
			&i.Revision,
			&i.Unread,
			&i.ArchivedAt,
			&i.ArchivedActor,
			&i.ArchivedReason,
			&i.Lifecycle,
			&i.SourceState,
			&i.FirstSeenAt,
			&i.LastEventAt,
			&i.IgnoredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnarchivedInboxItemsBySource = `-- name: ListUnarchivedInboxItemsBySource :many
SELECT id, profile_id, source_kind, source_scope, external_id, title, url, payload, revision, unread, archived_at, archived_actor, archived_reason, lifecycle, source_state, first_seen_at, last_event_at, ignored_at FROM inbox_item
WHERE profile_id = ? AND source_kind = ? AND source_scope = ? AND archived_at IS NULL
ORDER BY last_event_at ASC, id ASC
`

type ListUnarchivedInboxItemsBySourceParams struct {
	ProfileID   string `json:"profile_id"`
	SourceKind  string `json:"source_kind"`
	SourceScope string `json:"source_scope"`
}

// The complete current item set of one source identity, oldest activity
// first: the webhook listener builds its per-delivery authoritative
// snapshot from these rows.
func (q *Queries) ListUnarchivedInboxItemsBySource(ctx context.Context, arg ListUnarchivedInboxItemsBySourceParams) ([]InboxItem, error) {
	rows, err := q.db.QueryContext(ctx, listUnarchivedInboxItemsBySource, arg.ProfileID, arg.SourceKind, arg.SourceScope)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxItem{}
	for rows.Next() {
		var i InboxItem
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.SourceKind,
			&i.SourceScope,
			&i.ExternalID,
			&i.Title,
			&i.Url,
			&i.Payload,
			&i.Revision,
			&i.Unread,
			&i.ArchivedAt,
			&i.ArchivedActor,
			&i.ArchivedReason,
			&i.Lifecycle,
			&i.SourceState,
			&i.FirstSeenAt,
			&i.LastEventAt,
			&i.IgnoredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFeedInboxItemsRead = `-- name: MarkFeedInboxItemsRead :execrows
UPDATE inbox_item SET unread = 0, revision = revision + 1
WHERE unread = 1 AND archived_at IS NULL AND ignored_at IS NULL
  AND id IN (SELECT c.item_id FROM feed_membership_claim c WHERE c.profile_id = ? AND c.feed_id = ?)
`

type MarkFeedInboxItemsReadParams struct {
	ProfileID string `json:"profile_id"`
	FeedID    string `json:"feed_id"`
}

// Bulk read-state clear, claim-scoped so it covers exactly the rows
// CountInboxItemsByFeed reports as unread. Deliberately NOT revision-guarded:
// a bulk triage has no single row whose revision the caller could have read,
// and read state is low-stakes. The revision still advances, so an optimistic
// per-item write holding a pre-clear copy is rejected and re-reads instead of
// silently resurrecting the unread flag. Archived and ignored rows are left
// alone: neither is in the active list this clears.
// (Keep this file ASCII-only. sqlc mixes byte and rune offsets when it edits a
// query, so a multi-byte character anywhere above corrupts a later query.)
func (q *Queries) MarkFeedInboxItemsRead(ctx context.Context, arg MarkFeedInboxItemsReadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markFeedInboxItemsRead, arg.ProfileID, arg.FeedID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markProfileInboxItemsRead = `-- name: MarkProfileInboxItemsRead :execrows
UPDATE inbox_item SET unread = 0, revision = revision + 1
WHERE unread = 1 AND archived_at IS NULL AND ignored_at IS NULL
  AND id IN (SELECT c.item_id FROM feed_membership_claim c WHERE c.profile_id = ?)
`

// The workspace-wide variant: every feed in the profile, same scoping rules.
// Unrouted observations stay untouched; they live only in Trash, which carries
// no unread semantics.
func (q *Queries) MarkProfileInboxItemsRead(ctx context.Context, profileID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, markProfileInboxItemsRead, profileID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pruneArchivedInboxItems = `-- name: PruneArchivedInboxItems :exec
DELETE FROM inbox_item WHERE archived_at IS NOT NULL AND archived_at <= ?
`

// Cascades to inbox_event and feed_membership_claim through their item FKs.
func (q *Queries) PruneArchivedInboxItems(ctx context.Context, archivedAt sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, pruneArchivedInboxItems, archivedAt)
	return err
}

const rescopeInboxItem = `-- name: RescopeInboxItem :exec
UPDATE inbox_item SET source_scope = ?1 WHERE id = ?2
`

type RescopeInboxItemParams struct {
	SourceScope string `json:"source_scope"`
	ID          int64  `json:"id"`
}

// Move a row to a new source_scope. Used to heal pre-#63 rows written with an
// empty scope onto the account-scoped identity every post-#63 read keys on
// (issue #95); the caller only rescopes when the target identity is free, so
// this never collides with the UNIQUE (profile_id, source_kind, source_scope,
// external_id) index.
func (q *Queries) RescopeInboxItem(ctx context.Context, arg RescopeInboxItemParams) error {
	_, err := q.db.ExecContext(ctx, rescopeInboxItem, arg.SourceScope, arg.ID)
	return err
}

const setInboxItemUnread = `-- name: SetInboxItemUnread :one
UPDATE inbox_item SET unread = ?, revision = revision + 1
WHERE id = ? AND revision = ?
RETURNING id, profile_id, source_kind, source_scope, external_id, title, url, payload, revision, unread, archived_at, archived_actor, archived_reason, lifecycle, source_state, first_seen_at, last_event_at, ignored_at
`

type SetInboxItemUnreadParams struct {
	Unread   int64 `json:"unread"`
	ID       int64 `json:"id"`
	Revision int64 `json:"revision"`
}

func (q *Queries) SetInboxItemUnread(ctx context.Context, arg SetInboxItemUnreadParams) (InboxItem, error) {
	row := q.db.QueryRowContext(ctx, setInboxItemUnread, arg.Unread, arg.ID, arg.Revision)
	var i InboxItem
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.SourceKind,
		&i.SourceScope,
		&i.ExternalID,
		&i.Title,
		&i.Url,
		&i.Payload,
		&i.Revision,
		&i.Unread,
		&i.ArchivedAt,
		&i.ArchivedActor,
		&i.ArchivedReason,
		&i.Lifecycle,
		&i.SourceState,
		&i.FirstSeenAt,
		&i.LastEventAt,
		&i.IgnoredAt,
	)
	return i, err
}

const toggleInboxItemArchived = `-- name: ToggleInboxItemArchived :one
UPDATE inbox_item SET
    ignored_at = CASE WHEN archived_at IS NULL THEN NULL ELSE ignored_at END,
    archived_at = CASE WHEN archived_at IS NULL THEN ? ELSE NULL END,
    archived_actor = CASE WHEN archived_at IS NULL THEN 'manual' ELSE NULL END,
    archived_reason = CASE WHEN archived_at IS NULL THEN 'manual' ELSE NULL END,
    revision = revision + 1
WHERE id = ? AND revision = ?
RETURNING id, profile_id, source_kind, source_scope, external_id, title, url, payload, revision, unread, archived_at, archived_actor, archived_reason, lifecycle, source_state, first_seen_at, last_event_at, ignored_at
`

type ToggleInboxItemArchivedParams struct {
	ArchivedAt sql.NullInt64 `json:"archived_at"`
	ID         int64         `json:"id"`
	Revision   int64         `json:"revision"`
}

func (q *Queries) ToggleInboxItemArchived(ctx context.Context, arg ToggleInboxItemArchivedParams) (InboxItem, error) {
	row := q.db.QueryRowContext(ctx, toggleInboxItemArchived, arg.ArchivedAt, arg.ID, arg.Revision)
	var i InboxItem
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.SourceKind,
		&i.SourceScope,
		&i.ExternalID,
		&i.Title,
		&i.Url,
		&i.Payload,
		&i.Revision,
		&i.Unread,
		&i.ArchivedAt,
		&i.ArchivedActor,
		&i.ArchivedReason,
		&i.Lifecycle,
		&i.SourceState,
		&i.FirstSeenAt,
		&i.LastEventAt,
		&i.IgnoredAt,
	)
	return i, err
}

const toggleInboxItemIgnored = `-- name: ToggleInboxItemIgnored :one
UPDATE inbox_item SET
    ignored_at = CASE WHEN ignored_at IS NULL THEN ? ELSE NULL END,
    unread = CASE WHEN ignored_at IS NULL THEN 0 ELSE 1 END,
    archived_at = CASE WHEN ignored_at IS NULL THEN NULL ELSE archived_at END,
    archived_actor = CASE WHEN ignored_at IS NULL THEN NULL ELSE archived_actor END,
    archived_reason = CASE WHEN ignored_at IS NULL THEN NULL ELSE archived_reason END,
    revision = revision + 1
WHERE id = ? AND revision = ?
RETURNING id, profile_id, source_kind, source_scope, external_id, title, url, payload, revision, unread, archived_at, archived_actor, archived_reason, lifecycle, source_state, first_seen_at, last_event_at, ignored_at
`

type ToggleInboxItemIgnoredParams struct {
	IgnoredAt sql.NullInt64 `json:"ignored_at"`
	ID        int64         `json:"id"`
	Revision  int64         `json:"revision"`
}

func (q *Queries) ToggleInboxItemIgnored(ctx context.Context, arg ToggleInboxItemIgnoredParams) (InboxItem, error) {
	row := q.db.QueryRowContext(ctx, toggleInboxItemIgnored, arg.IgnoredAt, arg.ID, arg.Revision)
	var i InboxItem
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.SourceKind,
		&i.SourceScope,
		&i.ExternalID,
		&i.Title,
		&i.Url,
		&i.Payload,
		&i.Revision,
		&i.Unread,
		&i.ArchivedAt,
		&i.ArchivedActor,
		&i.ArchivedReason,
		&i.Lifecycle,
		&i.SourceState,
		&i.FirstSeenAt,
		&i.LastEventAt,
		&i.IgnoredAt,
	)
	return i, err
}

const upsertInboxItem = `-- name: UpsertInboxItem :one
INSERT INTO inbox_item (
    profile_id, source_kind, source_scope, external_id,
    title, url, payload, revision, unread,
    archived_at, archived_actor, archived_reason,
    lifecycle, source_state, first_seen_at, last_event_at
) VALUES (?, ?, ?, ?, ?, ?, ?, 1, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (profile_id, source_kind, source_scope, external_id) DO UPDATE SET
    title = excluded.title, url = excluded.url, payload = excluded.payload,
    revision = inbox_item.revision + 1, unread = excluded.unread,
    archived_at = excluded.archived_at, archived_actor = excluded.archived_actor,
    archived_reason = excluded.archived_reason, lifecycle = excluded.lifecycle,
    source_state = excluded.source_state, last_event_at = excluded.last_event_at
RETURNING id, profile_id, source_kind, source_scope, external_id, title, url, payload, revision, unread, archived_at, archived_actor, archived_reason, lifecycle, source_state, first_seen_at, last_event_at, ignored_at
`

type UpsertInboxItemParams struct {
	ProfileID      string         `json:"profile_id"`
	SourceKind     string         `json:"source_kind"`
	SourceScope    string         `json:"source_scope"`
	ExternalID     string         `json:"external_id"`
	Title          string         `json:"title"`
	Url            string         `json:"url"`
	Payload        []byte         `json:"payload"`
	Unread         int64          `json:"unread"`
	ArchivedAt     sql.NullInt64  `json:"archived_at"`
	ArchivedActor  sql.NullString `json:"archived_actor"`
	ArchivedReason sql.NullString `json:"archived_reason"`
	Lifecycle      string         `json:"lifecycle"`
	SourceState    sql.NullString `json:"source_state"`
	FirstSeenAt    int64          `json:"first_seen_at"`
	LastEventAt    int64          `json:"last_event_at"`
}

func (q *Queries) UpsertInboxItem(ctx context.Context, arg UpsertInboxItemParams) (InboxItem, error) {
	row := q.db.QueryRowContext(ctx, upsertInboxItem,
		arg.ProfileID,
		arg.SourceKind,
		arg.SourceScope,
		arg.ExternalID,
		arg.Title,
		arg.Url,
		arg.Payload,
		arg.Unread,
		arg.ArchivedAt,
		arg.ArchivedActor,
		arg.ArchivedReason,
		arg.Lifecycle,
		arg.SourceState,
		arg.FirstSeenAt,
		arg.LastEventAt,
	)
	var i InboxItem
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.SourceKind,
		&i.SourceScope,
		&i.ExternalID,
		&i.Title,
		&i.Url,
		&i.Payload,
		&i.Revision,
		&i.Unread,
		&i.ArchivedAt,
		&i.ArchivedActor,
		&i.ArchivedReason,
		&i.Lifecycle,
		&i.SourceState,
		&i.FirstSeenAt,
		&i.LastEventAt,
		&i.IgnoredAt,
	)
	return i, err
}
