// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: item_session.sql

package queries

import (
	"context"
)

const deleteItemSession = `-- name: DeleteItemSession :exec
DELETE FROM item_session WHERE session_id = ?
`

func (q *Queries) DeleteItemSession(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteItemSession, sessionID)
	return err
}

const deleteItemSessionsByProfile = `-- name: DeleteItemSessionsByProfile :exec
DELETE FROM item_session WHERE profile_id = ?
`

func (q *Queries) DeleteItemSessionsByProfile(ctx context.Context, profileID string) error {
	_, err := q.db.ExecContext(ctx, deleteItemSessionsByProfile, profileID)
	return err
}

const linkItemSession = `-- name: LinkItemSession :exec
INSERT INTO item_session (session_id, profile_id, source_kind, source_scope, external_id, created_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (session_id) DO NOTHING
`

type LinkItemSessionParams struct {
	SessionID   string `json:"session_id"`
	ProfileID   string `json:"profile_id"`
	SourceKind  string `json:"source_kind"`
	SourceScope string `json:"source_scope"`
	ExternalID  string `json:"external_id"`
	CreatedAt   int64  `json:"created_at"`
}

// A session hive already minted an id for, so a re-link is the same row.
func (q *Queries) LinkItemSession(ctx context.Context, arg LinkItemSessionParams) error {
	_, err := q.db.ExecContext(ctx, linkItemSession,
		arg.SessionID,
		arg.ProfileID,
		arg.SourceKind,
		arg.SourceScope,
		arg.ExternalID,
		arg.CreatedAt,
	)
	return err
}

const listItemSessions = `-- name: ListItemSessions :many
SELECT session_id, profile_id, source_kind, source_scope, external_id, created_at FROM item_session
WHERE profile_id = ? AND source_kind = ? AND source_scope = ? AND external_id = ?
ORDER BY created_at DESC, session_id DESC
`

type ListItemSessionsParams struct {
	ProfileID   string `json:"profile_id"`
	SourceKind  string `json:"source_kind"`
	SourceScope string `json:"source_scope"`
	ExternalID  string `json:"external_id"`
}

// Newest first: a re-run appends a session rather than replacing one, so the
// most recent attempt leads.
func (q *Queries) ListItemSessions(ctx context.Context, arg ListItemSessionsParams) ([]ItemSession, error) {
	rows, err := q.db.QueryContext(ctx, listItemSessions,
		arg.ProfileID,
		arg.SourceKind,
		arg.SourceScope,
		arg.ExternalID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemSession{}
	for rows.Next() {
		var i ItemSession
		if err := rows.Scan(
			&i.SessionID,
			&i.ProfileID,
			&i.SourceKind,
			&i.SourceScope,
			&i.ExternalID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rescopeItemSessions = `-- name: RescopeItemSessions :exec
UPDATE item_session SET source_scope = ?1
WHERE profile_id = ?2
  AND source_kind = ?3
  AND source_scope = ''
  AND external_id = ?4
`

type RescopeItemSessionsParams struct {
	SourceScope string `json:"source_scope"`
	ProfileID   string `json:"profile_id"`
	SourceKind  string `json:"source_kind"`
	ExternalID  string `json:"external_id"`
}

// Follows an inbox row whose source_scope was healed (see
// resolveInboxItemScoped), so links keyed on the old scope stay reachable.
func (q *Queries) RescopeItemSessions(ctx context.Context, arg RescopeItemSessionsParams) error {
	_, err := q.db.ExecContext(ctx, rescopeItemSessions,
		arg.SourceScope,
		arg.ProfileID,
		arg.SourceKind,
		arg.ExternalID,
	)
	return err
}
