// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
	"database/sql"
	"strings"
)

const appendActivityEvent = `-- name: AppendActivityEvent :one
INSERT INTO activity_event (created_at, category, severity, title, body, source, metadata)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, created_at, category, severity, title, body, source, metadata
`

type AppendActivityEventParams struct {
	CreatedAt int64  `json:"created_at"`
	Category  string `json:"category"`
	Severity  string `json:"severity"`
	Title     string `json:"title"`
	Body      string `json:"body"`
	Source    string `json:"source"`
	Metadata  []byte `json:"metadata"`
}

// Append one audit-log row and return it (with its assigned id) so the caller
// can echo the stored event straight back to subscribers.
func (q *Queries) AppendActivityEvent(ctx context.Context, arg AppendActivityEventParams) (ActivityEvent, error) {
	row := q.db.QueryRowContext(ctx, appendActivityEvent,
		arg.CreatedAt,
		arg.Category,
		arg.Severity,
		arg.Title,
		arg.Body,
		arg.Source,
		arg.Metadata,
	)
	var i ActivityEvent
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Category,
		&i.Severity,
		&i.Title,
		&i.Body,
		&i.Source,
		&i.Metadata,
	)
	return i, err
}

const appendEvent = `-- name: AppendEvent :one
INSERT INTO event_log (topic, key, payload, created_at, snapshot, source_kind, source_scope, occurrence_key)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING "offset"
`

type AppendEventParams struct {
	Topic         string         `json:"topic"`
	Key           string         `json:"key"`
	Payload       []byte         `json:"payload"`
	CreatedAt     int64          `json:"created_at"`
	Snapshot      int64          `json:"snapshot"`
	SourceKind    string         `json:"source_kind"`
	SourceScope   string         `json:"source_scope"`
	OccurrenceKey sql.NullString `json:"occurrence_key"`
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, appendEvent,
		arg.Topic,
		arg.Key,
		arg.Payload,
		arg.CreatedAt,
		arg.Snapshot,
		arg.SourceKind,
		arg.SourceScope,
		arg.OccurrenceKey,
	)
	var offset int64
	err := row.Scan(&offset)
	return offset, err
}

const commitConsumerOffset = `-- name: CommitConsumerOffset :exec
INSERT INTO consumer_offset (consumer, "offset")
VALUES (?, ?)
ON CONFLICT(consumer) DO UPDATE SET "offset" = excluded."offset"
WHERE excluded."offset" > consumer_offset."offset"
`

type CommitConsumerOffsetParams struct {
	Consumer string `json:"consumer"`
	Offset   int64  `json:"offset"`
}

// Monotonic upsert: on conflict, only advance the stored offset when the
// incoming one is greater. If it isn't, the WHERE clause makes the DO UPDATE
// a no-op (SQLite upsert semantics), so a stale/out-of-order commit never
// regresses a consumer's checkpoint.
func (q *Queries) CommitConsumerOffset(ctx context.Context, arg CommitConsumerOffsetParams) error {
	_, err := q.db.ExecContext(ctx, commitConsumerOffset, arg.Consumer, arg.Offset)
	return err
}

const confirmOutputCommand = `-- name: ConfirmOutputCommand :one
INSERT INTO output_command (action_id, key, payload, status, created_at, profile_id, source_kind, source_scope, external_id)
VALUES (?, ?, ?, 'running', ?, ?, ?, ?, ?)
ON CONFLICT DO UPDATE SET
    status = 'running',
    profile_id = CASE WHEN output_command.profile_id <> '' AND output_command.external_id <> ''
                      THEN output_command.profile_id ELSE excluded.profile_id END,
    source_kind = CASE WHEN output_command.profile_id <> '' AND output_command.external_id <> ''
                       THEN output_command.source_kind ELSE excluded.source_kind END,
    source_scope = CASE WHEN output_command.profile_id <> '' AND output_command.external_id <> ''
                        THEN output_command.source_scope ELSE excluded.source_scope END,
    external_id = CASE WHEN output_command.profile_id <> '' AND output_command.external_id <> ''
                       THEN output_command.external_id ELSE excluded.external_id END
WHERE output_command.status = 'pending'
RETURNING id, action_id, "key", payload, status, attempts, last_error, result_json, stdout, stderr, created_at, is_rerun, profile_id, source_kind, source_scope, external_id
`

type ConfirmOutputCommandParams struct {
	ActionID    string `json:"action_id"`
	Key         string `json:"key"`
	Payload     []byte `json:"payload"`
	CreatedAt   int64  `json:"created_at"`
	ProfileID   string `json:"profile_id"`
	SourceKind  string `json:"source_kind"`
	SourceScope string `json:"source_scope"`
	ExternalID  string `json:"external_id"`
}

// Explicit detail invocation creates work or claims a queued flow command.
// Terminal/running commands remain deduplicated. Claiming a queued command
// keeps the origin the enqueue recorded when that names an item, and takes the
// caller's only when it does not. The four columns move together: a mix of one
// row's profile and another's external id would be a reference to no item at
// all, which is worse than either.
func (q *Queries) ConfirmOutputCommand(ctx context.Context, arg ConfirmOutputCommandParams) (OutputCommand, error) {
	row := q.db.QueryRowContext(ctx, confirmOutputCommand,
		arg.ActionID,
		arg.Key,
		arg.Payload,
		arg.CreatedAt,
		arg.ProfileID,
		arg.SourceKind,
		arg.SourceScope,
		arg.ExternalID,
	)
	var i OutputCommand
	err := row.Scan(
		&i.ID,
		&i.ActionID,
		&i.Key,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.ResultJson,
		&i.Stdout,
		&i.Stderr,
		&i.CreatedAt,
		&i.IsRerun,
		&i.ProfileID,
		&i.SourceKind,
		&i.SourceScope,
		&i.ExternalID,
	)
	return i, err
}

const countInboxItemsByFeed = `-- name: CountInboxItemsByFeed :many
SELECT
    c.feed_id AS feed_id,
    CAST(COUNT(DISTINCT CASE WHEN i.archived_at IS NULL THEN i.id END) AS INTEGER) AS total,
    CAST(COUNT(DISTINCT CASE WHEN i.archived_at IS NULL AND i.unread = 1 THEN i.id END) AS INTEGER) AS unread,
    CAST(COUNT(DISTINCT CASE WHEN i.archived_at IS NOT NULL THEN i.id END) AS INTEGER) AS archived
FROM feed_membership_claim c
JOIN inbox_item i ON i.id = c.item_id
WHERE c.profile_id = ? AND i.ignored_at IS NULL
GROUP BY c.feed_id
`

type CountInboxItemsByFeedRow struct {
	FeedID   string `json:"feed_id"`
	Total    int64  `json:"total"`
	Unread   int64  `json:"unread"`
	Archived int64  `json:"archived"`
}

func (q *Queries) CountInboxItemsByFeed(ctx context.Context, profileID string) ([]CountInboxItemsByFeedRow, error) {
	rows, err := q.db.QueryContext(ctx, countInboxItemsByFeed, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountInboxItemsByFeedRow{}
	for rows.Next() {
		var i CountInboxItemsByFeedRow
		if err := rows.Scan(
			&i.FeedID,
			&i.Total,
			&i.Unread,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countNonterminalCommandsForAction = `-- name: CountNonterminalCommandsForAction :one
SELECT COUNT(*) FROM output_command
WHERE action_id = ? AND status IN ('pending', 'running')
`

// Pending work can still run and running work may already have been
// dispatched, so either blocks deleting the action. Done and failed history
// is terminal and must never keep an action from deletion.
func (q *Queries) CountNonterminalCommandsForAction(ctx context.Context, actionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNonterminalCommandsForAction, actionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAgentWorkspaceSession = `-- name: DeleteAgentWorkspaceSession :exec
DELETE FROM agent_workspace_session WHERE id = ?
`

func (q *Queries) DeleteAgentWorkspaceSession(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAgentWorkspaceSession, id)
	return err
}

const deleteAgentWorkspaceSessionsByWorkspace = `-- name: DeleteAgentWorkspaceSessionsByWorkspace :exec
DELETE FROM agent_workspace_session WHERE workspace = ?
`

func (q *Queries) DeleteAgentWorkspaceSessionsByWorkspace(ctx context.Context, workspace string) error {
	_, err := q.db.ExecContext(ctx, deleteAgentWorkspaceSessionsByWorkspace, workspace)
	return err
}

const deleteConsumerOffsetByConsumer = `-- name: DeleteConsumerOffsetByConsumer :exec
DELETE FROM consumer_offset WHERE consumer = ?
`

func (q *Queries) DeleteConsumerOffsetByConsumer(ctx context.Context, consumer string) error {
	_, err := q.db.ExecContext(ctx, deleteConsumerOffsetByConsumer, consumer)
	return err
}

const deleteEventLogByTopicPrefix = `-- name: DeleteEventLogByTopicPrefix :exec
DELETE FROM event_log WHERE topic LIKE ? ESCAPE '\'
`

func (q *Queries) DeleteEventLogByTopicPrefix(ctx context.Context, topic string) error {
	_, err := q.db.ExecContext(ctx, deleteEventLogByTopicPrefix, topic)
	return err
}

const deleteEventsOlderThan = `-- name: DeleteEventsOlderThan :exec
DELETE FROM event_log AS target
WHERE target.created_at < ?
  AND NOT (
      target.snapshot = 1
      AND target."offset" = (
          SELECT MAX(snapshot_row."offset")
          FROM event_log AS snapshot_row
          WHERE snapshot_row.topic = target.topic AND snapshot_row.snapshot = 1
      )
  )
`

func (q *Queries) DeleteEventsOlderThan(ctx context.Context, createdAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteEventsOlderThan, createdAt)
	return err
}

const deleteEventsOverLimitPerTopic = `-- name: DeleteEventsOverLimitPerTopic :exec
DELETE FROM event_log AS target
WHERE (
    SELECT COUNT(*) FROM event_log AS newer
    WHERE newer.topic = target.topic AND newer."offset" > target."offset"
) >= CAST(?1 AS INTEGER)
  AND NOT (
      target.snapshot = 1
      AND target."offset" = (
          SELECT MAX(snapshot_row."offset")
          FROM event_log AS snapshot_row
          WHERE snapshot_row.topic = target.topic AND snapshot_row.snapshot = 1
      )
  )
`

func (q *Queries) DeleteEventsOverLimitPerTopic(ctx context.Context, limit int64) error {
	_, err := q.db.ExecContext(ctx, deleteEventsOverLimitPerTopic, limit)
	return err
}

const deleteExpiredNodeKV = `-- name: DeleteExpiredNodeKV :exec
DELETE FROM node_kv WHERE expires_at IS NOT NULL AND expires_at <= ?
`

func (q *Queries) DeleteExpiredNodeKV(ctx context.Context, expiresAt sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredNodeKV, expiresAt)
	return err
}

const deleteFeedMembershipClaimsForFeeds = `-- name: DeleteFeedMembershipClaimsForFeeds :exec
DELETE FROM feed_membership_claim
WHERE feed_membership_claim.profile_id = ? AND feed_id NOT IN (/*SLICE:feed_ids*/?)
`

type DeleteFeedMembershipClaimsForFeedsParams struct {
	ProfileID string   `json:"profile_id"`
	FeedIds   []string `json:"feed_ids"`
}

func (q *Queries) DeleteFeedMembershipClaimsForFeeds(ctx context.Context, arg DeleteFeedMembershipClaimsForFeedsParams) error {
	query := deleteFeedMembershipClaimsForFeeds
	var queryParams []interface{}
	queryParams = append(queryParams, arg.ProfileID)
	if len(arg.FeedIds) > 0 {
		for _, v := range arg.FeedIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:feed_ids*/?", strings.Repeat(",?", len(arg.FeedIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:feed_ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const deleteFeedMembershipClaimsForFeedsAll = `-- name: DeleteFeedMembershipClaimsForFeedsAll :exec
DELETE FROM feed_membership_claim WHERE profile_id = ?
`

func (q *Queries) DeleteFeedMembershipClaimsForFeedsAll(ctx context.Context, profileID string) error {
	_, err := q.db.ExecContext(ctx, deleteFeedMembershipClaimsForFeedsAll, profileID)
	return err
}

const deleteFeedMembershipClaimsForRemovedSources = `-- name: DeleteFeedMembershipClaimsForRemovedSources :exec
DELETE FROM feed_membership_claim
WHERE feed_membership_claim.profile_id = ?
  AND source_id NOT IN (/*SLICE:source_ids*/?)
  AND item_id IN (SELECT id FROM inbox_item WHERE archived_at IS NULL)
`

type DeleteFeedMembershipClaimsForRemovedSourcesParams struct {
	ProfileID string   `json:"profile_id"`
	SourceIds []string `json:"source_ids"`
}

func (q *Queries) DeleteFeedMembershipClaimsForRemovedSources(ctx context.Context, arg DeleteFeedMembershipClaimsForRemovedSourcesParams) error {
	query := deleteFeedMembershipClaimsForRemovedSources
	var queryParams []interface{}
	queryParams = append(queryParams, arg.ProfileID)
	if len(arg.SourceIds) > 0 {
		for _, v := range arg.SourceIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:source_ids*/?", strings.Repeat(",?", len(arg.SourceIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:source_ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const deleteFeedMembershipClaimsForRemovedSourcesAll = `-- name: DeleteFeedMembershipClaimsForRemovedSourcesAll :exec
DELETE FROM feed_membership_claim
WHERE feed_membership_claim.profile_id = ?
  AND item_id IN (SELECT id FROM inbox_item WHERE archived_at IS NULL)
`

func (q *Queries) DeleteFeedMembershipClaimsForRemovedSourcesAll(ctx context.Context, profileID string) error {
	_, err := q.db.ExecContext(ctx, deleteFeedMembershipClaimsForRemovedSourcesAll, profileID)
	return err
}

const deleteFeedMembershipClaimsForSourceAll = `-- name: DeleteFeedMembershipClaimsForSourceAll :exec
DELETE FROM feed_membership_claim WHERE feed_id = ? AND source_id = ?
`

type DeleteFeedMembershipClaimsForSourceAllParams struct {
	FeedID   string `json:"feed_id"`
	SourceID string `json:"source_id"`
}

func (q *Queries) DeleteFeedMembershipClaimsForSourceAll(ctx context.Context, arg DeleteFeedMembershipClaimsForSourceAllParams) error {
	_, err := q.db.ExecContext(ctx, deleteFeedMembershipClaimsForSourceAll, arg.FeedID, arg.SourceID)
	return err
}

const deleteFeedMembershipClaimsNotInSnapshot = `-- name: DeleteFeedMembershipClaimsNotInSnapshot :exec
DELETE FROM feed_membership_claim
WHERE feed_id = ? AND source_id = ? AND item_id NOT IN (/*SLICE:item_ids*/?)
`

type DeleteFeedMembershipClaimsNotInSnapshotParams struct {
	FeedID   string  `json:"feed_id"`
	SourceID string  `json:"source_id"`
	ItemIds  []int64 `json:"item_ids"`
}

func (q *Queries) DeleteFeedMembershipClaimsNotInSnapshot(ctx context.Context, arg DeleteFeedMembershipClaimsNotInSnapshotParams) error {
	query := deleteFeedMembershipClaimsNotInSnapshot
	var queryParams []interface{}
	queryParams = append(queryParams, arg.FeedID)
	queryParams = append(queryParams, arg.SourceID)
	if len(arg.ItemIds) > 0 {
		for _, v := range arg.ItemIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:item_ids*/?", strings.Repeat(",?", len(arg.ItemIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:item_ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const deleteInboxItemsByProfile = `-- name: DeleteInboxItemsByProfile :exec
DELETE FROM inbox_item WHERE profile_id = ?
`

func (q *Queries) DeleteInboxItemsByProfile(ctx context.Context, profileID string) error {
	_, err := q.db.ExecContext(ctx, deleteInboxItemsByProfile, profileID)
	return err
}

const deleteItemSession = `-- name: DeleteItemSession :exec
DELETE FROM item_session WHERE session_id = ?
`

func (q *Queries) DeleteItemSession(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteItemSession, sessionID)
	return err
}

const deleteItemSessionsByProfile = `-- name: DeleteItemSessionsByProfile :exec
DELETE FROM item_session WHERE profile_id = ?
`

func (q *Queries) DeleteItemSessionsByProfile(ctx context.Context, profileID string) error {
	_, err := q.db.ExecContext(ctx, deleteItemSessionsByProfile, profileID)
	return err
}

const deleteNodeKV = `-- name: DeleteNodeKV :exec
DELETE FROM node_kv WHERE flow_id = ? AND node_id = ? AND scope = ? AND key = ?
`

type DeleteNodeKVParams struct {
	FlowID string `json:"flow_id"`
	NodeID string `json:"node_id"`
	Scope  string `json:"scope"`
	Key    string `json:"key"`
}

func (q *Queries) DeleteNodeKV(ctx context.Context, arg DeleteNodeKVParams) error {
	_, err := q.db.ExecContext(ctx, deleteNodeKV,
		arg.FlowID,
		arg.NodeID,
		arg.Scope,
		arg.Key,
	)
	return err
}

const deleteNodeKVByFlow = `-- name: DeleteNodeKVByFlow :exec
DELETE FROM node_kv WHERE flow_id = ?
`

func (q *Queries) DeleteNodeKVByFlow(ctx context.Context, flowID string) error {
	_, err := q.db.ExecContext(ctx, deleteNodeKVByFlow, flowID)
	return err
}

const deleteNodeKVForFlowExceptNodes = `-- name: DeleteNodeKVForFlowExceptNodes :exec
DELETE FROM node_kv WHERE flow_id = ? AND node_id NOT IN (/*SLICE:node_ids*/?)
`

type DeleteNodeKVForFlowExceptNodesParams struct {
	FlowID  string   `json:"flow_id"`
	NodeIds []string `json:"node_ids"`
}

// The empty-slice case is invalid SQL (NOT IN ()); callers with no node ids
// to retain use DeleteNodeKVByFlow instead, mirroring the
// DeleteFeedMembershipClaimsForFeeds / *All pair.
func (q *Queries) DeleteNodeKVForFlowExceptNodes(ctx context.Context, arg DeleteNodeKVForFlowExceptNodesParams) error {
	query := deleteNodeKVForFlowExceptNodes
	var queryParams []interface{}
	queryParams = append(queryParams, arg.FlowID)
	if len(arg.NodeIds) > 0 {
		for _, v := range arg.NodeIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:node_ids*/?", strings.Repeat(",?", len(arg.NodeIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:node_ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const deleteOrphanedSourceHeads = `-- name: DeleteOrphanedSourceHeads :exec
DELETE FROM source_head
WHERE key NOT IN (SELECT external_id FROM inbox_item)
`

func (q *Queries) DeleteOrphanedSourceHeads(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteOrphanedSourceHeads)
	return err
}

const deleteScheduleCursor = `-- name: DeleteScheduleCursor :exec
DELETE FROM schedule_cursor WHERE workspace = ? AND schedule_id = ?
`

type DeleteScheduleCursorParams struct {
	Workspace  string `json:"workspace"`
	ScheduleID string `json:"schedule_id"`
}

func (q *Queries) DeleteScheduleCursor(ctx context.Context, arg DeleteScheduleCursorParams) error {
	_, err := q.db.ExecContext(ctx, deleteScheduleCursor, arg.Workspace, arg.ScheduleID)
	return err
}

const deleteScheduleRunsByWorkspace = `-- name: DeleteScheduleRunsByWorkspace :exec
DELETE FROM schedule_run WHERE workspace = ?
`

func (q *Queries) DeleteScheduleRunsByWorkspace(ctx context.Context, workspace string) error {
	_, err := q.db.ExecContext(ctx, deleteScheduleRunsByWorkspace, workspace)
	return err
}

const deleteSnapshotsOverLimitPerTopic = `-- name: DeleteSnapshotsOverLimitPerTopic :exec
DELETE FROM event_log AS target
WHERE target.snapshot = 1
  AND (
      SELECT COUNT(*) FROM event_log AS newer
      WHERE newer.topic = target.topic
        AND newer.snapshot = 1
        AND newer."offset" > target."offset"
  ) >= CAST(?1 AS INTEGER)
`

// Superseded source snapshots are dead weight: replay and every snapshot read
// take only the newest snapshot per topic, so older ones reconcile nothing.
// Keep the newest N snapshots per topic and delete the rest. This is the bound
// that actually caps event_log size, because a full-source snapshot dwarfs an
// ordinary item event; the per-topic row bound above counts item events too
// and so cannot target the snapshots that dominate. N is >= 1, so the single
// latest snapshot the age/count bounds preserve is preserved here as well.
func (q *Queries) DeleteSnapshotsOverLimitPerTopic(ctx context.Context, limit int64) error {
	_, err := q.db.ExecContext(ctx, deleteSnapshotsOverLimitPerTopic, limit)
	return err
}

const deleteSourceHead = `-- name: DeleteSourceHead :exec
DELETE FROM source_head WHERE topic = ? AND key = ?
`

type DeleteSourceHeadParams struct {
	Topic string `json:"topic"`
	Key   string `json:"key"`
}

func (q *Queries) DeleteSourceHead(ctx context.Context, arg DeleteSourceHeadParams) error {
	_, err := q.db.ExecContext(ctx, deleteSourceHead, arg.Topic, arg.Key)
	return err
}

const deleteSourceHeadByTopicPrefix = `-- name: DeleteSourceHeadByTopicPrefix :exec
DELETE FROM source_head WHERE topic LIKE ? ESCAPE '\'
`

func (q *Queries) DeleteSourceHeadByTopicPrefix(ctx context.Context, topic string) error {
	_, err := q.db.ExecContext(ctx, deleteSourceHeadByTopicPrefix, topic)
	return err
}

const deleteUnarchivedFeedMembershipClaimsByProfile = `-- name: DeleteUnarchivedFeedMembershipClaimsByProfile :exec
DELETE FROM feed_membership_claim
WHERE feed_membership_claim.profile_id = ? AND item_id IN (SELECT id FROM inbox_item WHERE archived_at IS NULL)
`

func (q *Queries) DeleteUnarchivedFeedMembershipClaimsByProfile(ctx context.Context, profileID string) error {
	_, err := q.db.ExecContext(ctx, deleteUnarchivedFeedMembershipClaimsByProfile, profileID)
	return err
}

const enqueueOutputCommand = `-- name: EnqueueOutputCommand :exec
INSERT INTO output_command (action_id, key, payload, status, created_at, profile_id, source_kind, source_scope, external_id)
VALUES (?, ?, ?, 'pending', ?, ?, ?, ?, ?)
ON CONFLICT DO NOTHING
`

type EnqueueOutputCommandParams struct {
	ActionID    string `json:"action_id"`
	Key         string `json:"key"`
	Payload     []byte `json:"payload"`
	CreatedAt   int64  `json:"created_at"`
	ProfileID   string `json:"profile_id"`
	SourceKind  string `json:"source_kind"`
	SourceScope string `json:"source_scope"`
	ExternalID  string `json:"external_id"`
}

// Deduped on (action_id, key): a replayed commit batch enqueues the same
// action invocation at most once (see idx_output_command_action_key).
func (q *Queries) EnqueueOutputCommand(ctx context.Context, arg EnqueueOutputCommandParams) error {
	_, err := q.db.ExecContext(ctx, enqueueOutputCommand,
		arg.ActionID,
		arg.Key,
		arg.Payload,
		arg.CreatedAt,
		arg.ProfileID,
		arg.SourceKind,
		arg.SourceScope,
		arg.ExternalID,
	)
	return err
}

const findInboxItemsByExternalID = `-- name: FindInboxItemsByExternalID :many
SELECT id, profile_id, source_kind, source_scope, external_id, title, url, payload, revision, unread, archived_at, archived_actor, archived_reason, lifecycle, source_state, first_seen_at, last_event_at, ignored_at FROM inbox_item
WHERE external_id = ?1
  AND (?2 = '' OR profile_id = ?2)
ORDER BY profile_id, source_kind, source_scope
`

type FindInboxItemsByExternalIDParams struct {
	ExternalID string      `json:"external_id"`
	ProfileID  interface{} `json:"profile_id"`
}

func (q *Queries) FindInboxItemsByExternalID(ctx context.Context, arg FindInboxItemsByExternalIDParams) ([]InboxItem, error) {
	rows, err := q.db.QueryContext(ctx, findInboxItemsByExternalID, arg.ExternalID, arg.ProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxItem{}
	for rows.Next() {
		var i InboxItem
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.SourceKind,
			&i.SourceScope,
			&i.ExternalID,
			&i.Title,
			&i.Url,
			&i.Payload,
			&i.Revision,
			&i.Unread,
			&i.ArchivedAt,
			&i.ArchivedActor,
			&i.ArchivedReason,
			&i.Lifecycle,
			&i.SourceState,
			&i.FirstSeenAt,
			&i.LastEventAt,
			&i.IgnoredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findRunningJobByCommandID = `-- name: FindRunningJobByCommandID :one
SELECT id, created_at, updated_at, status, label, step, action_id, target, error, command_id FROM job
WHERE command_id = ? AND status = 'running'
ORDER BY id DESC
LIMIT 1
`

// Restore a running job's identity after a worker or app restart so retries do
// not create duplicate jobs and strand the original lifecycle as active.
func (q *Queries) FindRunningJobByCommandID(ctx context.Context, commandID sql.NullInt64) (Job, error) {
	row := q.db.QueryRowContext(ctx, findRunningJobByCommandID, commandID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.Label,
		&i.Step,
		&i.ActionID,
		&i.Target,
		&i.Error,
		&i.CommandID,
	)
	return i, err
}

const getAgentWorkspaceSession = `-- name: GetAgentWorkspaceSession :one
SELECT id, workspace, name, agent, agent_session_id, created_at, last_opened_at FROM agent_workspace_session WHERE id = ?
`

func (q *Queries) GetAgentWorkspaceSession(ctx context.Context, id int64) (AgentWorkspaceSession, error) {
	row := q.db.QueryRowContext(ctx, getAgentWorkspaceSession, id)
	var i AgentWorkspaceSession
	err := row.Scan(
		&i.ID,
		&i.Workspace,
		&i.Name,
		&i.Agent,
		&i.AgentSessionID,
		&i.CreatedAt,
		&i.LastOpenedAt,
	)
	return i, err
}

const getConsumerOffset = `-- name: GetConsumerOffset :one
SELECT consumer, "offset" FROM consumer_offset
WHERE consumer = ?
`

func (q *Queries) GetConsumerOffset(ctx context.Context, consumer string) (ConsumerOffset, error) {
	row := q.db.QueryRowContext(ctx, getConsumerOffset, consumer)
	var i ConsumerOffset
	err := row.Scan(&i.Consumer, &i.Offset)
	return i, err
}

const getInboxItemByExternalID = `-- name: GetInboxItemByExternalID :one
SELECT id, profile_id, source_kind, source_scope, external_id, title, url, payload, revision, unread, archived_at, archived_actor, archived_reason, lifecycle, source_state, first_seen_at, last_event_at, ignored_at FROM inbox_item
WHERE profile_id = ? AND source_kind = ? AND source_scope = ? AND external_id = ?
`

type GetInboxItemByExternalIDParams struct {
	ProfileID   string `json:"profile_id"`
	SourceKind  string `json:"source_kind"`
	SourceScope string `json:"source_scope"`
	ExternalID  string `json:"external_id"`
}

func (q *Queries) GetInboxItemByExternalID(ctx context.Context, arg GetInboxItemByExternalIDParams) (InboxItem, error) {
	row := q.db.QueryRowContext(ctx, getInboxItemByExternalID,
		arg.ProfileID,
		arg.SourceKind,
		arg.SourceScope,
		arg.ExternalID,
	)
	var i InboxItem
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.SourceKind,
		&i.SourceScope,
		&i.ExternalID,
		&i.Title,
		&i.Url,
		&i.Payload,
		&i.Revision,
		&i.Unread,
		&i.ArchivedAt,
		&i.ArchivedActor,
		&i.ArchivedReason,
		&i.Lifecycle,
		&i.SourceState,
		&i.FirstSeenAt,
		&i.LastEventAt,
		&i.IgnoredAt,
	)
	return i, err
}

const getInboxItemByID = `-- name: GetInboxItemByID :one
SELECT id, profile_id, source_kind, source_scope, external_id, title, url, payload, revision, unread, archived_at, archived_actor, archived_reason, lifecycle, source_state, first_seen_at, last_event_at, ignored_at FROM inbox_item WHERE id = ?
`

func (q *Queries) GetInboxItemByID(ctx context.Context, id int64) (InboxItem, error) {
	row := q.db.QueryRowContext(ctx, getInboxItemByID, id)
	var i InboxItem
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.SourceKind,
		&i.SourceScope,
		&i.ExternalID,
		&i.Title,
		&i.Url,
		&i.Payload,
		&i.Revision,
		&i.Unread,
		&i.ArchivedAt,
		&i.ArchivedActor,
		&i.ArchivedReason,
		&i.Lifecycle,
		&i.SourceState,
		&i.FirstSeenAt,
		&i.LastEventAt,
		&i.IgnoredAt,
	)
	return i, err
}

const getLatestOutputCommandForAction = `-- name: GetLatestOutputCommandForAction :one
SELECT id, action_id, "key", payload, status, attempts, last_error, result_json, stdout, stderr, created_at, is_rerun, profile_id, source_kind, source_scope, external_id FROM output_command
WHERE action_id = ? AND key = ?
ORDER BY id DESC
LIMIT 1
`

type GetLatestOutputCommandForActionParams struct {
	ActionID string `json:"action_id"`
	Key      string `json:"key"`
}

func (q *Queries) GetLatestOutputCommandForAction(ctx context.Context, arg GetLatestOutputCommandForActionParams) (OutputCommand, error) {
	row := q.db.QueryRowContext(ctx, getLatestOutputCommandForAction, arg.ActionID, arg.Key)
	var i OutputCommand
	err := row.Scan(
		&i.ID,
		&i.ActionID,
		&i.Key,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.ResultJson,
		&i.Stdout,
		&i.Stderr,
		&i.CreatedAt,
		&i.IsRerun,
		&i.ProfileID,
		&i.SourceKind,
		&i.SourceScope,
		&i.ExternalID,
	)
	return i, err
}

const getNodeKV = `-- name: GetNodeKV :one
SELECT value FROM node_kv
WHERE flow_id = ? AND node_id = ? AND scope = ? AND key = ?
  AND (expires_at IS NULL OR expires_at > ?)
`

type GetNodeKVParams struct {
	FlowID    string        `json:"flow_id"`
	NodeID    string        `json:"node_id"`
	Scope     string        `json:"scope"`
	Key       string        `json:"key"`
	ExpiresAt sql.NullInt64 `json:"expires_at"`
}

// Expiry-aware read: an expired row reads as absent (sql.ErrNoRows). The
// final arg is an explicit `now` cutoff -- never a fresh time.Now() inside
// the query -- so the expiry boundary is deterministically testable.
func (q *Queries) GetNodeKV(ctx context.Context, arg GetNodeKVParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getNodeKV,
		arg.FlowID,
		arg.NodeID,
		arg.Scope,
		arg.Key,
		arg.ExpiresAt,
	)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getOutputCommand = `-- name: GetOutputCommand :one
SELECT id, action_id, "key", payload, status, attempts, last_error, result_json, stdout, stderr, created_at, is_rerun, profile_id, source_kind, source_scope, external_id FROM output_command WHERE id = ?
`

func (q *Queries) GetOutputCommand(ctx context.Context, id int64) (OutputCommand, error) {
	row := q.db.QueryRowContext(ctx, getOutputCommand, id)
	var i OutputCommand
	err := row.Scan(
		&i.ID,
		&i.ActionID,
		&i.Key,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.ResultJson,
		&i.Stdout,
		&i.Stderr,
		&i.CreatedAt,
		&i.IsRerun,
		&i.ProfileID,
		&i.SourceKind,
		&i.SourceScope,
		&i.ExternalID,
	)
	return i, err
}

const getScheduleCursor = `-- name: GetScheduleCursor :one
SELECT workspace, schedule_id, evaluated_through, cron FROM schedule_cursor WHERE workspace = ? AND schedule_id = ?
`

type GetScheduleCursorParams struct {
	Workspace  string `json:"workspace"`
	ScheduleID string `json:"schedule_id"`
}

func (q *Queries) GetScheduleCursor(ctx context.Context, arg GetScheduleCursorParams) (ScheduleCursor, error) {
	row := q.db.QueryRowContext(ctx, getScheduleCursor, arg.Workspace, arg.ScheduleID)
	var i ScheduleCursor
	err := row.Scan(
		&i.Workspace,
		&i.ScheduleID,
		&i.EvaluatedThrough,
		&i.Cron,
	)
	return i, err
}

const getScheduleRun = `-- name: GetScheduleRun :one
SELECT id, workspace, schedule_id, schedule_name, scheduled_for, started_at, reason, missed, status, session_id, prompt, error FROM schedule_run WHERE id = ?
`

func (q *Queries) GetScheduleRun(ctx context.Context, id int64) (ScheduleRun, error) {
	row := q.db.QueryRowContext(ctx, getScheduleRun, id)
	var i ScheduleRun
	err := row.Scan(
		&i.ID,
		&i.Workspace,
		&i.ScheduleID,
		&i.ScheduleName,
		&i.ScheduledFor,
		&i.StartedAt,
		&i.Reason,
		&i.Missed,
		&i.Status,
		&i.SessionID,
		&i.Prompt,
		&i.Error,
	)
	return i, err
}

const getSourceHeadPayload = `-- name: GetSourceHeadPayload :one
SELECT payload FROM source_head
WHERE topic = ? AND key = ?
`

type GetSourceHeadPayloadParams struct {
	Topic string `json:"topic"`
	Key   string `json:"key"`
}

func (q *Queries) GetSourceHeadPayload(ctx context.Context, arg GetSourceHeadPayloadParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getSourceHeadPayload, arg.Topic, arg.Key)
	var payload []byte
	err := row.Scan(&payload)
	return payload, err
}

const getUnarchivedInboxItemByID = `-- name: GetUnarchivedInboxItemByID :one
SELECT id, profile_id, source_kind, source_scope, external_id, title, url, payload, revision, unread, archived_at, archived_actor, archived_reason, lifecycle, source_state, first_seen_at, last_event_at, ignored_at FROM inbox_item WHERE id = ? AND profile_id = ? AND archived_at IS NULL
`

type GetUnarchivedInboxItemByIDParams struct {
	ID        int64  `json:"id"`
	ProfileID string `json:"profile_id"`
}

func (q *Queries) GetUnarchivedInboxItemByID(ctx context.Context, arg GetUnarchivedInboxItemByIDParams) (InboxItem, error) {
	row := q.db.QueryRowContext(ctx, getUnarchivedInboxItemByID, arg.ID, arg.ProfileID)
	var i InboxItem
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.SourceKind,
		&i.SourceScope,
		&i.ExternalID,
		&i.Title,
		&i.Url,
		&i.Payload,
		&i.Revision,
		&i.Unread,
		&i.ArchivedAt,
		&i.ArchivedActor,
		&i.ArchivedReason,
		&i.Lifecycle,
		&i.SourceState,
		&i.FirstSeenAt,
		&i.LastEventAt,
		&i.IgnoredAt,
	)
	return i, err
}

const getWebhookCapture = `-- name: GetWebhookCapture :one
SELECT topic, received_at, body FROM webhook_capture WHERE topic = ?
`

func (q *Queries) GetWebhookCapture(ctx context.Context, topic string) (WebhookCapture, error) {
	row := q.db.QueryRowContext(ctx, getWebhookCapture, topic)
	var i WebhookCapture
	err := row.Scan(&i.Topic, &i.ReceivedAt, &i.Body)
	return i, err
}

const insertAgentWorkspaceSession = `-- name: InsertAgentWorkspaceSession :one
INSERT INTO agent_workspace_session (workspace, name, agent, agent_session_id, created_at, last_opened_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, workspace, name, agent, agent_session_id, created_at, last_opened_at
`

type InsertAgentWorkspaceSessionParams struct {
	Workspace      string `json:"workspace"`
	Name           string `json:"name"`
	Agent          string `json:"agent"`
	AgentSessionID string `json:"agent_session_id"`
	CreatedAt      int64  `json:"created_at"`
	LastOpenedAt   int64  `json:"last_opened_at"`
}

func (q *Queries) InsertAgentWorkspaceSession(ctx context.Context, arg InsertAgentWorkspaceSessionParams) (AgentWorkspaceSession, error) {
	row := q.db.QueryRowContext(ctx, insertAgentWorkspaceSession,
		arg.Workspace,
		arg.Name,
		arg.Agent,
		arg.AgentSessionID,
		arg.CreatedAt,
		arg.LastOpenedAt,
	)
	var i AgentWorkspaceSession
	err := row.Scan(
		&i.ID,
		&i.Workspace,
		&i.Name,
		&i.Agent,
		&i.AgentSessionID,
		&i.CreatedAt,
		&i.LastOpenedAt,
	)
	return i, err
}

const insertInboxEvent = `-- name: InsertInboxEvent :one
INSERT INTO inbox_event (item_id, kind, transition, attention, occurrence_key, summary, detail, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (item_id, occurrence_key) WHERE occurrence_key IS NOT NULL DO NOTHING
RETURNING id, item_id, kind, transition, attention, occurrence_key, summary, detail, created_at
`

type InsertInboxEventParams struct {
	ItemID        int64          `json:"item_id"`
	Kind          string         `json:"kind"`
	Transition    string         `json:"transition"`
	Attention     string         `json:"attention"`
	OccurrenceKey sql.NullString `json:"occurrence_key"`
	Summary       sql.NullString `json:"summary"`
	Detail        []byte         `json:"detail"`
	CreatedAt     int64          `json:"created_at"`
}

func (q *Queries) InsertInboxEvent(ctx context.Context, arg InsertInboxEventParams) (InboxEvent, error) {
	row := q.db.QueryRowContext(ctx, insertInboxEvent,
		arg.ItemID,
		arg.Kind,
		arg.Transition,
		arg.Attention,
		arg.OccurrenceKey,
		arg.Summary,
		arg.Detail,
		arg.CreatedAt,
	)
	var i InboxEvent
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Kind,
		&i.Transition,
		&i.Attention,
		&i.OccurrenceKey,
		&i.Summary,
		&i.Detail,
		&i.CreatedAt,
	)
	return i, err
}

const insertInboxItem = `-- name: InsertInboxItem :one
INSERT INTO inbox_item (
    profile_id, source_kind, source_scope, external_id,
    title, url, payload, revision, unread,
    lifecycle, first_seen_at, last_event_at
) VALUES (
    ?, ?, ?, ?,
    ?, ?, ?, 1, ?,
    ?, ?, ?
)
RETURNING id, profile_id, source_kind, source_scope, external_id, title, url, payload, revision, unread, archived_at, archived_actor, archived_reason, lifecycle, source_state, first_seen_at, last_event_at, ignored_at
`

type InsertInboxItemParams struct {
	ProfileID   string `json:"profile_id"`
	SourceKind  string `json:"source_kind"`
	SourceScope string `json:"source_scope"`
	ExternalID  string `json:"external_id"`
	Title       string `json:"title"`
	Url         string `json:"url"`
	Payload     []byte `json:"payload"`
	Unread      int64  `json:"unread"`
	Lifecycle   string `json:"lifecycle"`
	FirstSeenAt int64  `json:"first_seen_at"`
	LastEventAt int64  `json:"last_event_at"`
}

// Seed-only plain insert for deterministic desktop fixtures. The ingestion
// path receives its classify-and-upsert contract in a later phase.
func (q *Queries) InsertInboxItem(ctx context.Context, arg InsertInboxItemParams) (InboxItem, error) {
	row := q.db.QueryRowContext(ctx, insertInboxItem,
		arg.ProfileID,
		arg.SourceKind,
		arg.SourceScope,
		arg.ExternalID,
		arg.Title,
		arg.Url,
		arg.Payload,
		arg.Unread,
		arg.Lifecycle,
		arg.FirstSeenAt,
		arg.LastEventAt,
	)
	var i InboxItem
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.SourceKind,
		&i.SourceScope,
		&i.ExternalID,
		&i.Title,
		&i.Url,
		&i.Payload,
		&i.Revision,
		&i.Unread,
		&i.ArchivedAt,
		&i.ArchivedActor,
		&i.ArchivedReason,
		&i.Lifecycle,
		&i.SourceState,
		&i.FirstSeenAt,
		&i.LastEventAt,
		&i.IgnoredAt,
	)
	return i, err
}

const insertJob = `-- name: InsertJob :one
INSERT INTO job (created_at, updated_at, status, label, step, action_id, target, error, command_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, created_at, updated_at, status, label, step, action_id, target, error, command_id
`

type InsertJobParams struct {
	CreatedAt int64         `json:"created_at"`
	UpdatedAt int64         `json:"updated_at"`
	Status    string        `json:"status"`
	Label     string        `json:"label"`
	Step      string        `json:"step"`
	ActionID  string        `json:"action_id"`
	Target    string        `json:"target"`
	Error     string        `json:"error"`
	CommandID sql.NullInt64 `json:"command_id"`
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, insertJob,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Status,
		arg.Label,
		arg.Step,
		arg.ActionID,
		arg.Target,
		arg.Error,
		arg.CommandID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.Label,
		&i.Step,
		&i.ActionID,
		&i.Target,
		&i.Error,
		&i.CommandID,
	)
	return i, err
}

const insertNodeRun = `-- name: InsertNodeRun :exec
INSERT INTO node_run (flow_id, node_id, ok, in_count, out_count, drop_count, err, ended_at, dur_ms)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertNodeRunParams struct {
	FlowID    string         `json:"flow_id"`
	NodeID    string         `json:"node_id"`
	Ok        int64          `json:"ok"`
	InCount   int64          `json:"in_count"`
	OutCount  int64          `json:"out_count"`
	DropCount int64          `json:"drop_count"`
	Err       sql.NullString `json:"err"`
	EndedAt   int64          `json:"ended_at"`
	DurMs     int64          `json:"dur_ms"`
}

func (q *Queries) InsertNodeRun(ctx context.Context, arg InsertNodeRunParams) error {
	_, err := q.db.ExecContext(ctx, insertNodeRun,
		arg.FlowID,
		arg.NodeID,
		arg.Ok,
		arg.InCount,
		arg.OutCount,
		arg.DropCount,
		arg.Err,
		arg.EndedAt,
		arg.DurMs,
	)
	return err
}

const insertScheduleRun = `-- name: InsertScheduleRun :one
INSERT INTO schedule_run (
    workspace, schedule_id, schedule_name, scheduled_for, started_at,
    reason, missed, status, session_id, prompt, error
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, workspace, schedule_id, schedule_name, scheduled_for, started_at, reason, missed, status, session_id, prompt, error
`

type InsertScheduleRunParams struct {
	Workspace    string        `json:"workspace"`
	ScheduleID   string        `json:"schedule_id"`
	ScheduleName string        `json:"schedule_name"`
	ScheduledFor int64         `json:"scheduled_for"`
	StartedAt    int64         `json:"started_at"`
	Reason       string        `json:"reason"`
	Missed       int64         `json:"missed"`
	Status       string        `json:"status"`
	SessionID    sql.NullInt64 `json:"session_id"`
	Prompt       string        `json:"prompt"`
	Error        string        `json:"error"`
}

func (q *Queries) InsertScheduleRun(ctx context.Context, arg InsertScheduleRunParams) (ScheduleRun, error) {
	row := q.db.QueryRowContext(ctx, insertScheduleRun,
		arg.Workspace,
		arg.ScheduleID,
		arg.ScheduleName,
		arg.ScheduledFor,
		arg.StartedAt,
		arg.Reason,
		arg.Missed,
		arg.Status,
		arg.SessionID,
		arg.Prompt,
		arg.Error,
	)
	var i ScheduleRun
	err := row.Scan(
		&i.ID,
		&i.Workspace,
		&i.ScheduleID,
		&i.ScheduleName,
		&i.ScheduledFor,
		&i.StartedAt,
		&i.Reason,
		&i.Missed,
		&i.Status,
		&i.SessionID,
		&i.Prompt,
		&i.Error,
	)
	return i, err
}

const lastLaunchedScheduleRun = `-- name: LastLaunchedScheduleRun :one
SELECT id, workspace, schedule_id, schedule_name, scheduled_for, started_at, reason, missed, status, session_id, prompt, error FROM schedule_run
WHERE workspace = ? AND schedule_id = ? AND status = 'launched'
ORDER BY started_at DESC, id DESC
LIMIT 1
`

type LastLaunchedScheduleRunParams struct {
	Workspace  string `json:"workspace"`
	ScheduleID string `json:"schedule_id"`
}

// The most recent run that actually started a chat, skipping over failed and
// skipped attempts. The scheduler checks this before deciding whether the
// previous run's chat is still live.
func (q *Queries) LastLaunchedScheduleRun(ctx context.Context, arg LastLaunchedScheduleRunParams) (ScheduleRun, error) {
	row := q.db.QueryRowContext(ctx, lastLaunchedScheduleRun, arg.Workspace, arg.ScheduleID)
	var i ScheduleRun
	err := row.Scan(
		&i.ID,
		&i.Workspace,
		&i.ScheduleID,
		&i.ScheduleName,
		&i.ScheduledFor,
		&i.StartedAt,
		&i.Reason,
		&i.Missed,
		&i.Status,
		&i.SessionID,
		&i.Prompt,
		&i.Error,
	)
	return i, err
}

const linkItemSession = `-- name: LinkItemSession :exec
INSERT INTO item_session (session_id, profile_id, source_kind, source_scope, external_id, created_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (session_id) DO NOTHING
`

type LinkItemSessionParams struct {
	SessionID   string `json:"session_id"`
	ProfileID   string `json:"profile_id"`
	SourceKind  string `json:"source_kind"`
	SourceScope string `json:"source_scope"`
	ExternalID  string `json:"external_id"`
	CreatedAt   int64  `json:"created_at"`
}

// A session hive already minted an id for, so a re-link is the same row.
func (q *Queries) LinkItemSession(ctx context.Context, arg LinkItemSessionParams) error {
	_, err := q.db.ExecContext(ctx, linkItemSession,
		arg.SessionID,
		arg.ProfileID,
		arg.SourceKind,
		arg.SourceScope,
		arg.ExternalID,
		arg.CreatedAt,
	)
	return err
}

const listActiveJobs = `-- name: ListActiveJobs :many
SELECT id, created_at, updated_at, status, label, step, action_id, target, error, command_id FROM job
WHERE status IN ('queued', 'running') OR (status IN ('done', 'failed') AND updated_at >= ?)
ORDER BY id DESC
`

// Non-terminal jobs plus terminal jobs updated within a recency window, newest
// first. Drives the auto-hiding titlebar chip.
func (q *Queries) ListActiveJobs(ctx context.Context, updatedAt int64) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listActiveJobs, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.Label,
			&i.Step,
			&i.ActionID,
			&i.Target,
			&i.Error,
			&i.CommandID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveSourceHeadKeys = `-- name: ListActiveSourceHeadKeys :many
SELECT h.key
FROM source_head h
JOIN inbox_item i
  ON i.external_id = h.key
 AND i.profile_id = ?1
 AND i.source_kind = ?2
 AND i.source_scope = ?3
WHERE h.topic = ?4
  AND i.archived_at IS NULL
`

type ListActiveSourceHeadKeysParams struct {
	ProfileID   string `json:"profile_id"`
	SourceKind  string `json:"source_kind"`
	SourceScope string `json:"source_scope"`
	Topic       string `json:"topic"`
}

func (q *Queries) ListActiveSourceHeadKeys(ctx context.Context, arg ListActiveSourceHeadKeysParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSourceHeadKeys,
		arg.ProfileID,
		arg.SourceKind,
		arg.SourceScope,
		arg.Topic,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityEvents = `-- name: ListActivityEvents :many
SELECT id, created_at, category, severity, title, body, source, metadata FROM activity_event
WHERE id < ?
ORDER BY id DESC
LIMIT ?
`

type ListActivityEventsParams struct {
	ID    int64 `json:"id"`
	Limit int64 `json:"limit"`
}

// Newest first, paged by a descending id cursor: pass a sentinel above the
// largest id for the first page, then the smallest id returned to continue.
func (q *Queries) ListActivityEvents(ctx context.Context, arg ListActivityEventsParams) ([]ActivityEvent, error) {
	rows, err := q.db.QueryContext(ctx, listActivityEvents, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityEvent{}
	for rows.Next() {
		var i ActivityEvent
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Category,
			&i.Severity,
			&i.Title,
			&i.Body,
			&i.Source,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentWorkspaceSessions = `-- name: ListAgentWorkspaceSessions :many
SELECT id, workspace, name, agent, agent_session_id, created_at, last_opened_at FROM agent_workspace_session
WHERE workspace = ?
ORDER BY id DESC
`

// One workspace's sessions, newest record first. Creation order on purpose,
// not last_opened_at: resuming a chat must not reshuffle the sidebar under
// the pointer.
func (q *Queries) ListAgentWorkspaceSessions(ctx context.Context, workspace string) ([]AgentWorkspaceSession, error) {
	rows, err := q.db.QueryContext(ctx, listAgentWorkspaceSessions, workspace)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentWorkspaceSession{}
	for rows.Next() {
		var i AgentWorkspaceSession
		if err := rows.Scan(
			&i.ID,
			&i.Workspace,
			&i.Name,
			&i.Agent,
			&i.AgentSessionID,
			&i.CreatedAt,
			&i.LastOpenedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllAgentWorkspaceSessions = `-- name: ListAllAgentWorkspaceSessions :many
SELECT id, workspace, name, agent, agent_session_id, created_at, last_opened_at FROM agent_workspace_session
ORDER BY id DESC
`

// Every session across every workspace, newest record first: the same
// stable creation order the scoped list uses.
func (q *Queries) ListAllAgentWorkspaceSessions(ctx context.Context) ([]AgentWorkspaceSession, error) {
	rows, err := q.db.QueryContext(ctx, listAllAgentWorkspaceSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentWorkspaceSession{}
	for rows.Next() {
		var i AgentWorkspaceSession
		if err := rows.Scan(
			&i.ID,
			&i.Workspace,
			&i.Name,
			&i.Agent,
			&i.AgentSessionID,
			&i.CreatedAt,
			&i.LastOpenedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllInboxItems = `-- name: ListAllInboxItems :many
SELECT id, profile_id, source_kind, source_scope, external_id, title, url, payload, revision, unread, archived_at, archived_actor, archived_reason, lifecycle, source_state, first_seen_at, last_event_at, ignored_at FROM inbox_item
WHERE (?1 = '' OR profile_id = ?1)
ORDER BY last_event_at DESC, id DESC
LIMIT ?2
`

type ListAllInboxItemsParams struct {
	ProfileID interface{} `json:"profile_id"`
	Lim       int64       `json:"lim"`
}

func (q *Queries) ListAllInboxItems(ctx context.Context, arg ListAllInboxItemsParams) ([]InboxItem, error) {
	rows, err := q.db.QueryContext(ctx, listAllInboxItems, arg.ProfileID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxItem{}
	for rows.Next() {
		var i InboxItem
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.SourceKind,
			&i.SourceScope,
			&i.ExternalID,
			&i.Title,
			&i.Url,
			&i.Payload,
			&i.Revision,
			&i.Unread,
			&i.ArchivedAt,
			&i.ArchivedActor,
			&i.ArchivedReason,
			&i.Lifecycle,
			&i.SourceState,
			&i.FirstSeenAt,
			&i.LastEventAt,
			&i.IgnoredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllScheduleRunSessions = `-- name: ListAllScheduleRunSessions :many
SELECT session_id, schedule_id FROM schedule_run
WHERE session_id IS NOT NULL
ORDER BY started_at ASC, id ASC
`

type ListAllScheduleRunSessionsRow struct {
	SessionID  sql.NullInt64 `json:"session_id"`
	ScheduleID string        `json:"schedule_id"`
}

// ListScheduleRunSessions across every workspace, for the sidebar's
// cross-workspace chat list. Session ids are unique across workspaces, so the
// rows key the same way.
func (q *Queries) ListAllScheduleRunSessions(ctx context.Context) ([]ListAllScheduleRunSessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllScheduleRunSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllScheduleRunSessionsRow{}
	for rows.Next() {
		var i ListAllScheduleRunSessionsRow
		if err := rows.Scan(&i.SessionID, &i.ScheduleID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchivedInboxItemsByFeed = `-- name: ListArchivedInboxItemsByFeed :many
SELECT DISTINCT i.id, i.profile_id, i.source_kind, i.source_scope, i.external_id, i.title, i.url, i.payload, i.revision, i.unread, i.archived_at, i.archived_actor, i.archived_reason, i.lifecycle, i.source_state, i.first_seen_at, i.last_event_at, i.ignored_at FROM inbox_item i
JOIN feed_membership_claim c ON c.item_id = i.id
WHERE c.profile_id = ? AND c.feed_id = ? AND i.archived_at IS NOT NULL AND i.ignored_at IS NULL
ORDER BY i.archived_at DESC, i.id DESC LIMIT ?
`

type ListArchivedInboxItemsByFeedParams struct {
	ProfileID string `json:"profile_id"`
	FeedID    string `json:"feed_id"`
	Limit     int64  `json:"limit"`
}

// Archived items stay visible inside the feeds they matched, demoted below
// active rows and lazy-loaded when the archived section expands.
func (q *Queries) ListArchivedInboxItemsByFeed(ctx context.Context, arg ListArchivedInboxItemsByFeedParams) ([]InboxItem, error) {
	rows, err := q.db.QueryContext(ctx, listArchivedInboxItemsByFeed, arg.ProfileID, arg.FeedID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxItem{}
	for rows.Next() {
		var i InboxItem
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.SourceKind,
			&i.SourceScope,
			&i.ExternalID,
			&i.Title,
			&i.Url,
			&i.Payload,
			&i.Revision,
			&i.Unread,
			&i.ArchivedAt,
			&i.ArchivedActor,
			&i.ArchivedReason,
			&i.Lifecycle,
			&i.SourceState,
			&i.FirstSeenAt,
			&i.LastEventAt,
			&i.IgnoredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInboxEventsByItem = `-- name: ListInboxEventsByItem :many
SELECT id, item_id, kind, transition, attention, occurrence_key, summary, detail, created_at FROM inbox_event WHERE item_id = ? ORDER BY id DESC LIMIT ?
`

type ListInboxEventsByItemParams struct {
	ItemID int64 `json:"item_id"`
	Limit  int64 `json:"limit"`
}

func (q *Queries) ListInboxEventsByItem(ctx context.Context, arg ListInboxEventsByItemParams) ([]InboxEvent, error) {
	rows, err := q.db.QueryContext(ctx, listInboxEventsByItem, arg.ItemID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxEvent{}
	for rows.Next() {
		var i InboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.Kind,
			&i.Transition,
			&i.Attention,
			&i.OccurrenceKey,
			&i.Summary,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInboxItemsByFeed = `-- name: ListInboxItemsByFeed :many
SELECT DISTINCT i.id, i.profile_id, i.source_kind, i.source_scope, i.external_id, i.title, i.url, i.payload, i.revision, i.unread, i.archived_at, i.archived_actor, i.archived_reason, i.lifecycle, i.source_state, i.first_seen_at, i.last_event_at, i.ignored_at FROM inbox_item i
JOIN feed_membership_claim c ON c.item_id = i.id
WHERE c.profile_id = ? AND c.feed_id = ? AND i.archived_at IS NULL AND i.ignored_at IS NULL
ORDER BY i.last_event_at DESC, i.id DESC LIMIT ?
`

type ListInboxItemsByFeedParams struct {
	ProfileID string `json:"profile_id"`
	FeedID    string `json:"feed_id"`
	Limit     int64  `json:"limit"`
}

// Every user-facing feed view is claim-scoped: source observations that did
// not reach a feed terminal remain internal pipeline data and never leak into
// workspace categories. Trash is the only exception: it deliberately surfaces
// unrouted and ignored items so users can debug rules and un-ignore.
func (q *Queries) ListInboxItemsByFeed(ctx context.Context, arg ListInboxItemsByFeedParams) ([]InboxItem, error) {
	rows, err := q.db.QueryContext(ctx, listInboxItemsByFeed, arg.ProfileID, arg.FeedID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxItem{}
	for rows.Next() {
		var i InboxItem
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.SourceKind,
			&i.SourceScope,
			&i.ExternalID,
			&i.Title,
			&i.Url,
			&i.Payload,
			&i.Revision,
			&i.Unread,
			&i.ArchivedAt,
			&i.ArchivedActor,
			&i.ArchivedReason,
			&i.Lifecycle,
			&i.SourceState,
			&i.FirstSeenAt,
			&i.LastEventAt,
			&i.IgnoredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInboxItemsTrash = `-- name: ListInboxItemsTrash :many
SELECT i.id, i.profile_id, i.source_kind, i.source_scope, i.external_id, i.title, i.url, i.payload, i.revision, i.unread, i.archived_at, i.archived_actor, i.archived_reason, i.lifecycle, i.source_state, i.first_seen_at, i.last_event_at, i.ignored_at FROM inbox_item i
WHERE i.profile_id = ?
  AND (i.ignored_at IS NOT NULL
       OR NOT EXISTS (SELECT 1 FROM feed_membership_claim c WHERE c.profile_id = i.profile_id AND c.item_id = i.id))
ORDER BY i.last_event_at DESC, i.id DESC LIMIT ?
`

type ListInboxItemsTrashParams struct {
	ProfileID string `json:"profile_id"`
	Limit     int64  `json:"limit"`
}

// Trash holds items with no path to any feed (routing produced no claims)
// plus user-ignored items. It is a utility/debug surface, never a queue.
func (q *Queries) ListInboxItemsTrash(ctx context.Context, arg ListInboxItemsTrashParams) ([]InboxItem, error) {
	rows, err := q.db.QueryContext(ctx, listInboxItemsTrash, arg.ProfileID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxItem{}
	for rows.Next() {
		var i InboxItem
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.SourceKind,
			&i.SourceScope,
			&i.ExternalID,
			&i.Title,
			&i.Url,
			&i.Payload,
			&i.Revision,
			&i.Unread,
			&i.ArchivedAt,
			&i.ArchivedActor,
			&i.ArchivedReason,
			&i.Lifecycle,
			&i.SourceState,
			&i.FirstSeenAt,
			&i.LastEventAt,
			&i.IgnoredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemSessions = `-- name: ListItemSessions :many
SELECT session_id, profile_id, source_kind, source_scope, external_id, created_at FROM item_session
WHERE profile_id = ? AND source_kind = ? AND source_scope = ? AND external_id = ?
ORDER BY created_at DESC, session_id DESC
`

type ListItemSessionsParams struct {
	ProfileID   string `json:"profile_id"`
	SourceKind  string `json:"source_kind"`
	SourceScope string `json:"source_scope"`
	ExternalID  string `json:"external_id"`
}

// Newest first: a re-run appends a session rather than replacing one, so the
// most recent attempt leads.
func (q *Queries) ListItemSessions(ctx context.Context, arg ListItemSessionsParams) ([]ItemSession, error) {
	rows, err := q.db.QueryContext(ctx, listItemSessions,
		arg.ProfileID,
		arg.SourceKind,
		arg.SourceScope,
		arg.ExternalID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemSession{}
	for rows.Next() {
		var i ItemSession
		if err := rows.Scan(
			&i.SessionID,
			&i.ProfileID,
			&i.SourceKind,
			&i.SourceScope,
			&i.ExternalID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT id, created_at, updated_at, status, label, step, action_id, target, error, command_id FROM job WHERE id < ? ORDER BY id DESC LIMIT ?
`

type ListJobsParams struct {
	ID    int64 `json:"id"`
	Limit int64 `json:"limit"`
}

// Newest first, paged by a descending id cursor (same shape as ListActivityEvents).
func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobs, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.Label,
			&i.Step,
			&i.ActionID,
			&i.Target,
			&i.Error,
			&i.CommandID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestSourceSnapshotsByTopicPrefix = `-- name: ListLatestSourceSnapshotsByTopicPrefix :many
SELECT event_log."offset", event_log.topic, event_log."key", event_log.payload, event_log.snapshot, event_log.source_kind, event_log.source_scope, event_log.occurrence_key, event_log.created_at
FROM event_log
JOIN (
    SELECT topic, MAX("offset") AS "offset"
    FROM event_log
    WHERE snapshot = 1
      AND "offset" <= CAST(?1 AS INTEGER)
      AND substr(topic, 1, length(CAST(?2 AS TEXT))) = CAST(?2 AS TEXT)
    GROUP BY topic
) AS latest ON latest.topic = event_log.topic AND latest."offset" = event_log."offset"
ORDER BY event_log.topic
`

type ListLatestSourceSnapshotsByTopicPrefixParams struct {
	ThroughOffset int64  `json:"through_offset"`
	TopicPrefix   string `json:"topic_prefix"`
}

func (q *Queries) ListLatestSourceSnapshotsByTopicPrefix(ctx context.Context, arg ListLatestSourceSnapshotsByTopicPrefixParams) ([]EventLog, error) {
	rows, err := q.db.QueryContext(ctx, listLatestSourceSnapshotsByTopicPrefix, arg.ThroughOffset, arg.TopicPrefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventLog{}
	for rows.Next() {
		var i EventLog
		if err := rows.Scan(
			&i.Offset,
			&i.Topic,
			&i.Key,
			&i.Payload,
			&i.Snapshot,
			&i.SourceKind,
			&i.SourceScope,
			&i.OccurrenceKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeKVKeysByPrefix = `-- name: ListNodeKVKeysByPrefix :many
SELECT key FROM node_kv
WHERE flow_id = ? AND node_id = ? AND scope = ?
  AND key GLOB ?4
  AND (expires_at IS NULL OR expires_at > ?5)
ORDER BY key
`

type ListNodeKVKeysByPrefixParams struct {
	FlowID  string        `json:"flow_id"`
	NodeID  string        `json:"node_id"`
	Scope   string        `json:"scope"`
	Pattern string        `json:"pattern"`
	Now     sql.NullInt64 `json:"now"`
}

// Unexpired keys under one node/scope whose key has the given prefix. Uses
// GLOB, which is binary/case-SENSITIVE, so it matches Go strings.HasPrefix
// exactly; default LIKE is ASCII case-insensitive and would silently
// disagree on a mixed-case prefix. The wrapper escapes GLOB metacharacters
// in the prefix and appends `*`; a literal leading prefix lets SQLite
// range-scan the composite PK index. The final arg is an explicit `now`
// cutoff.
func (q *Queries) ListNodeKVKeysByPrefix(ctx context.Context, arg ListNodeKVKeysByPrefixParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listNodeKVKeysByPrefix,
		arg.FlowID,
		arg.NodeID,
		arg.Scope,
		arg.Pattern,
		arg.Now,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeRunsByFlow = `-- name: ListNodeRunsByFlow :many
SELECT flow_id, node_id, ok, in_count, out_count, drop_count, err, ended_at, dur_ms FROM node_run
WHERE flow_id = ?
ORDER BY ended_at DESC
LIMIT ?
`

type ListNodeRunsByFlowParams struct {
	FlowID string `json:"flow_id"`
	Limit  int64  `json:"limit"`
}

// Recent runs, newest first: the canvas derives latest-per-node status and a
// RECENT list from this page rather than querying per-node.
func (q *Queries) ListNodeRunsByFlow(ctx context.Context, arg ListNodeRunsByFlowParams) ([]NodeRun, error) {
	rows, err := q.db.QueryContext(ctx, listNodeRunsByFlow, arg.FlowID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeRun{}
	for rows.Next() {
		var i NodeRun
		if err := rows.Scan(
			&i.FlowID,
			&i.NodeID,
			&i.Ok,
			&i.InCount,
			&i.OutCount,
			&i.DropCount,
			&i.Err,
			&i.EndedAt,
			&i.DurMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunnableOutputCommandsAfter = `-- name: ListRunnableOutputCommandsAfter :many
SELECT id, action_id, "key", payload, status, attempts, last_error, result_json, stdout, stderr, created_at, is_rerun, profile_id, source_kind, source_scope, external_id FROM output_command
WHERE status = 'pending' AND id > ?
ORDER BY id ASC
LIMIT ?
`

type ListRunnableOutputCommandsAfterParams struct {
	ID    int64 `json:"id"`
	Limit int64 `json:"limit"`
}

// Every enqueued flow action is runnable immediately; running is reserved for
// an explicit detail invocation. Continues a bounded worker scan after the
// previous row. The status/id predicate is covered by
// idx_output_command_status_id.
func (q *Queries) ListRunnableOutputCommandsAfter(ctx context.Context, arg ListRunnableOutputCommandsAfterParams) ([]OutputCommand, error) {
	rows, err := q.db.QueryContext(ctx, listRunnableOutputCommandsAfter, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutputCommand{}
	for rows.Next() {
		var i OutputCommand
		if err := rows.Scan(
			&i.ID,
			&i.ActionID,
			&i.Key,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.ResultJson,
			&i.Stdout,
			&i.Stderr,
			&i.CreatedAt,
			&i.IsRerun,
			&i.ProfileID,
			&i.SourceKind,
			&i.SourceScope,
			&i.ExternalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleCursors = `-- name: ListScheduleCursors :many
SELECT workspace, schedule_id, evaluated_through, cron FROM schedule_cursor
`

func (q *Queries) ListScheduleCursors(ctx context.Context) ([]ScheduleCursor, error) {
	rows, err := q.db.QueryContext(ctx, listScheduleCursors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduleCursor{}
	for rows.Next() {
		var i ScheduleCursor
		if err := rows.Scan(
			&i.Workspace,
			&i.ScheduleID,
			&i.EvaluatedThrough,
			&i.Cron,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleRunSessions = `-- name: ListScheduleRunSessions :many
SELECT session_id, schedule_id FROM schedule_run
WHERE workspace = ? AND session_id IS NOT NULL
ORDER BY started_at ASC, id ASC
`

type ListScheduleRunSessionsRow struct {
	SessionID  sql.NullInt64 `json:"session_id"`
	ScheduleID string        `json:"schedule_id"`
}

// Which schedule started each chat in one workspace. Oldest first so a caller
// folding these into a map keyed by session ends up with the newest run's
// schedule. No index of its own: a workspace keeps at most ScheduleRunLimit
// runs per schedule, and schedule_run_by_schedule already narrows to the
// workspace.
func (q *Queries) ListScheduleRunSessions(ctx context.Context, workspace string) ([]ListScheduleRunSessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listScheduleRunSessions, workspace)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScheduleRunSessionsRow{}
	for rows.Next() {
		var i ListScheduleRunSessionsRow
		if err := rows.Scan(&i.SessionID, &i.ScheduleID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleRuns = `-- name: ListScheduleRuns :many
SELECT id, workspace, schedule_id, schedule_name, scheduled_for, started_at, reason, missed, status, session_id, prompt, error FROM schedule_run
WHERE workspace = ?
ORDER BY started_at DESC, id DESC
LIMIT ?
`

type ListScheduleRunsParams struct {
	Workspace string `json:"workspace"`
	Limit     int64  `json:"limit"`
}

// One workspace's runs across every schedule, newest first.
func (q *Queries) ListScheduleRuns(ctx context.Context, arg ListScheduleRunsParams) ([]ScheduleRun, error) {
	rows, err := q.db.QueryContext(ctx, listScheduleRuns, arg.Workspace, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduleRun{}
	for rows.Next() {
		var i ScheduleRun
		if err := rows.Scan(
			&i.ID,
			&i.Workspace,
			&i.ScheduleID,
			&i.ScheduleName,
			&i.ScheduledFor,
			&i.StartedAt,
			&i.Reason,
			&i.Missed,
			&i.Status,
			&i.SessionID,
			&i.Prompt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleRunsForSchedule = `-- name: ListScheduleRunsForSchedule :many
SELECT id, workspace, schedule_id, schedule_name, scheduled_for, started_at, reason, missed, status, session_id, prompt, error FROM schedule_run
WHERE workspace = ? AND schedule_id = ?
ORDER BY started_at DESC, id DESC
LIMIT ?
`

type ListScheduleRunsForScheduleParams struct {
	Workspace  string `json:"workspace"`
	ScheduleID string `json:"schedule_id"`
	Limit      int64  `json:"limit"`
}

// One schedule's runs, newest first.
func (q *Queries) ListScheduleRunsForSchedule(ctx context.Context, arg ListScheduleRunsForScheduleParams) ([]ScheduleRun, error) {
	rows, err := q.db.QueryContext(ctx, listScheduleRunsForSchedule, arg.Workspace, arg.ScheduleID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduleRun{}
	for rows.Next() {
		var i ScheduleRun
		if err := rows.Scan(
			&i.ID,
			&i.Workspace,
			&i.ScheduleID,
			&i.ScheduleName,
			&i.ScheduledFor,
			&i.StartedAt,
			&i.Reason,
			&i.Missed,
			&i.Status,
			&i.SessionID,
			&i.Prompt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnarchivedInboxItemsByProfile = `-- name: ListUnarchivedInboxItemsByProfile :many
SELECT id, profile_id, source_kind, source_scope, external_id, title, url, payload, revision, unread, archived_at, archived_actor, archived_reason, lifecycle, source_state, first_seen_at, last_event_at, ignored_at FROM inbox_item WHERE profile_id = ? AND archived_at IS NULL
`

func (q *Queries) ListUnarchivedInboxItemsByProfile(ctx context.Context, profileID string) ([]InboxItem, error) {
	rows, err := q.db.QueryContext(ctx, listUnarchivedInboxItemsByProfile, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxItem{}
	for rows.Next() {
		var i InboxItem
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.SourceKind,
			&i.SourceScope,
			&i.ExternalID,
			&i.Title,
			&i.Url,
			&i.Payload,
			&i.Revision,
			&i.Unread,
			&i.ArchivedAt,
			&i.ArchivedActor,
			&i.ArchivedReason,
			&i.Lifecycle,
			&i.SourceState,
			&i.FirstSeenAt,
			&i.LastEventAt,
			&i.IgnoredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnarchivedInboxItemsBySource = `-- name: ListUnarchivedInboxItemsBySource :many
SELECT id, profile_id, source_kind, source_scope, external_id, title, url, payload, revision, unread, archived_at, archived_actor, archived_reason, lifecycle, source_state, first_seen_at, last_event_at, ignored_at FROM inbox_item
WHERE profile_id = ? AND source_kind = ? AND source_scope = ? AND archived_at IS NULL
ORDER BY last_event_at ASC, id ASC
`

type ListUnarchivedInboxItemsBySourceParams struct {
	ProfileID   string `json:"profile_id"`
	SourceKind  string `json:"source_kind"`
	SourceScope string `json:"source_scope"`
}

// The complete current item set of one source identity, oldest activity
// first: the webhook listener builds its per-delivery authoritative
// snapshot from these rows.
func (q *Queries) ListUnarchivedInboxItemsBySource(ctx context.Context, arg ListUnarchivedInboxItemsBySourceParams) ([]InboxItem, error) {
	rows, err := q.db.QueryContext(ctx, listUnarchivedInboxItemsBySource, arg.ProfileID, arg.SourceKind, arg.SourceScope)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxItem{}
	for rows.Next() {
		var i InboxItem
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.SourceKind,
			&i.SourceScope,
			&i.ExternalID,
			&i.Title,
			&i.Url,
			&i.Payload,
			&i.Revision,
			&i.Unread,
			&i.ArchivedAt,
			&i.ArchivedActor,
			&i.ArchivedReason,
			&i.Lifecycle,
			&i.SourceState,
			&i.FirstSeenAt,
			&i.LastEventAt,
			&i.IgnoredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFeedInboxItemsRead = `-- name: MarkFeedInboxItemsRead :execrows
UPDATE inbox_item SET unread = 0, revision = revision + 1
WHERE unread = 1 AND archived_at IS NULL AND ignored_at IS NULL
  AND id IN (SELECT c.item_id FROM feed_membership_claim c WHERE c.profile_id = ? AND c.feed_id = ?)
`

type MarkFeedInboxItemsReadParams struct {
	ProfileID string `json:"profile_id"`
	FeedID    string `json:"feed_id"`
}

// Bulk read-state clear, claim-scoped so it covers exactly the rows
// CountInboxItemsByFeed reports as unread. Deliberately NOT revision-guarded:
// a bulk triage has no single row whose revision the caller could have read,
// and read state is low-stakes. The revision still advances, so an optimistic
// per-item write holding a pre-clear copy is rejected and re-reads instead of
// silently resurrecting the unread flag. Archived and ignored rows are left
// alone: neither is in the active list this clears.
// (Keep this file ASCII-only. sqlc mixes byte and rune offsets when it edits a
// query, so a multi-byte character anywhere above corrupts a later query.)
func (q *Queries) MarkFeedInboxItemsRead(ctx context.Context, arg MarkFeedInboxItemsReadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markFeedInboxItemsRead, arg.ProfileID, arg.FeedID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markOutputCommandDone = `-- name: MarkOutputCommandDone :exec
UPDATE output_command
SET status = 'done', last_error = NULL, result_json = ?, stdout = ?, stderr = ?
WHERE id = ?
`

type MarkOutputCommandDoneParams struct {
	ResultJson sql.NullString `json:"result_json"`
	Stdout     sql.NullString `json:"stdout"`
	Stderr     sql.NullString `json:"stderr"`
	ID         int64          `json:"id"`
}

func (q *Queries) MarkOutputCommandDone(ctx context.Context, arg MarkOutputCommandDoneParams) error {
	_, err := q.db.ExecContext(ctx, markOutputCommandDone,
		arg.ResultJson,
		arg.Stdout,
		arg.Stderr,
		arg.ID,
	)
	return err
}

const markOutputCommandFailed = `-- name: MarkOutputCommandFailed :exec
UPDATE output_command SET status = 'failed', attempts = attempts + 1, last_error = ?, stdout = ?, stderr = ?
WHERE id = ?
`

type MarkOutputCommandFailedParams struct {
	LastError sql.NullString `json:"last_error"`
	Stdout    sql.NullString `json:"stdout"`
	Stderr    sql.NullString `json:"stderr"`
	ID        int64          `json:"id"`
}

func (q *Queries) MarkOutputCommandFailed(ctx context.Context, arg MarkOutputCommandFailedParams) error {
	_, err := q.db.ExecContext(ctx, markOutputCommandFailed,
		arg.LastError,
		arg.Stdout,
		arg.Stderr,
		arg.ID,
	)
	return err
}

const markProfileInboxItemsRead = `-- name: MarkProfileInboxItemsRead :execrows
UPDATE inbox_item SET unread = 0, revision = revision + 1
WHERE unread = 1 AND archived_at IS NULL AND ignored_at IS NULL
  AND id IN (SELECT c.item_id FROM feed_membership_claim c WHERE c.profile_id = ?)
`

// The workspace-wide variant: every feed in the profile, same scoping rules.
// Unrouted observations stay untouched; they live only in Trash, which carries
// no unread semantics.
func (q *Queries) MarkProfileInboxItemsRead(ctx context.Context, profileID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, markProfileInboxItemsRead, profileID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pruneActivityEvents = `-- name: PruneActivityEvents :exec
DELETE FROM activity_event
WHERE id IN (
    SELECT id FROM activity_event
    ORDER BY id DESC
    LIMIT -1 OFFSET ?
)
`

// Retain only the newest rows globally; bounded diagnostic history like
// node_run. The id primary key both orders and breaks ties exactly.
func (q *Queries) PruneActivityEvents(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, pruneActivityEvents, offset)
	return err
}

const pruneArchivedInboxItems = `-- name: PruneArchivedInboxItems :exec
DELETE FROM inbox_item WHERE archived_at IS NOT NULL AND archived_at <= ?
`

// Cascades to inbox_event and feed_membership_claim through their item FKs.
func (q *Queries) PruneArchivedInboxItems(ctx context.Context, archivedAt sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, pruneArchivedInboxItems, archivedAt)
	return err
}

const pruneNodeRuns = `-- name: PruneNodeRuns :exec
DELETE FROM node_run
WHERE rowid IN (
    SELECT rowid FROM node_run
    ORDER BY ended_at DESC, rowid DESC
    LIMIT -1 OFFSET ?
)
`

// Retain the newest rows globally. rowid breaks same-nanosecond ties, so the
// limit is exact even when a fast batch stamps equal ended_at values.
func (q *Queries) PruneNodeRuns(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, pruneNodeRuns, offset)
	return err
}

const pruneScheduleRuns = `-- name: PruneScheduleRuns :exec
DELETE FROM schedule_run AS target
WHERE target.workspace = ?1 AND target.schedule_id = ?2
  AND target.id NOT IN (
      SELECT kept.id FROM schedule_run AS kept
      WHERE kept.workspace = ?1 AND kept.schedule_id = ?2
      ORDER BY kept.started_at DESC, kept.id DESC
      LIMIT ?3
  )
`

type PruneScheduleRunsParams struct {
	Workspace  string `json:"workspace"`
	ScheduleID string `json:"schedule_id"`
	Keep       int64  `json:"keep"`
}

// Retain only the newest `keep` rows for one (workspace, schedule_id), the
// per-schedule counterpart to PruneNodeRuns' global bound. id breaks ties on
// equal started_at.
func (q *Queries) PruneScheduleRuns(ctx context.Context, arg PruneScheduleRunsParams) error {
	_, err := q.db.ExecContext(ctx, pruneScheduleRuns, arg.Workspace, arg.ScheduleID, arg.Keep)
	return err
}

const pruneTerminalJobs = `-- name: PruneTerminalJobs :exec
DELETE FROM job
WHERE id IN (
    SELECT id FROM job
    WHERE status IN ('done', 'failed')
    ORDER BY id DESC
    LIMIT -1 OFFSET ?
)
`

// Never remove active jobs: only terminal done/failed history is bounded
// (mirrors PruneTerminalOutputCommands).
func (q *Queries) PruneTerminalJobs(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, pruneTerminalJobs, offset)
	return err
}

const pruneTerminalOutputCommands = `-- name: PruneTerminalOutputCommands :exec
DELETE FROM output_command
WHERE id IN (
    SELECT id FROM output_command
    WHERE status IN ('done', 'failed')
    ORDER BY id DESC
    LIMIT -1 OFFSET ?
)
`

// Never remove active commands: only terminal done/failed history is bounded.
func (q *Queries) PruneTerminalOutputCommands(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, pruneTerminalOutputCommands, offset)
	return err
}

const readEventsFrom = `-- name: ReadEventsFrom :many
SELECT "offset", topic, "key", payload, snapshot, source_kind, source_scope, occurrence_key, created_at FROM event_log
WHERE "offset" > ?
ORDER BY "offset" ASC
LIMIT ?
`

type ReadEventsFromParams struct {
	Offset int64 `json:"offset"`
	Limit  int64 `json:"limit"`
}

func (q *Queries) ReadEventsFrom(ctx context.Context, arg ReadEventsFromParams) ([]EventLog, error) {
	rows, err := q.db.QueryContext(ctx, readEventsFrom, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventLog{}
	for rows.Next() {
		var i EventLog
		if err := rows.Scan(
			&i.Offset,
			&i.Topic,
			&i.Key,
			&i.Payload,
			&i.Snapshot,
			&i.SourceKind,
			&i.SourceScope,
			&i.OccurrenceKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameAgentWorkspaceSession = `-- name: RenameAgentWorkspaceSession :exec
UPDATE agent_workspace_session SET name = ? WHERE id = ?
`

type RenameAgentWorkspaceSessionParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) RenameAgentWorkspaceSession(ctx context.Context, arg RenameAgentWorkspaceSessionParams) error {
	_, err := q.db.ExecContext(ctx, renameAgentWorkspaceSession, arg.Name, arg.ID)
	return err
}

const rerunOutputCommand = `-- name: RerunOutputCommand :one
INSERT INTO output_command (action_id, key, payload, status, created_at, is_rerun, profile_id, source_kind, source_scope, external_id)
SELECT ?1, ?2, ?3, 'running', ?4, 1,
       ?5, ?6, ?7, ?8
WHERE EXISTS (
    SELECT 1 FROM output_command
    WHERE action_id = ?1 AND key = ?2
      AND status IN ('done', 'failed')
)
AND NOT EXISTS (
    SELECT 1 FROM output_command
    WHERE action_id = ?1 AND key = ?2
      AND status IN ('pending', 'running')
)
RETURNING id, action_id, "key", payload, status, attempts, last_error, result_json, stdout, stderr, created_at, is_rerun, profile_id, source_kind, source_scope, external_id
`

type RerunOutputCommandParams struct {
	ActionID    string `json:"action_id"`
	Key         string `json:"key"`
	Payload     []byte `json:"payload"`
	CreatedAt   int64  `json:"created_at"`
	ProfileID   string `json:"profile_id"`
	SourceKind  string `json:"source_kind"`
	SourceScope string `json:"source_scope"`
	ExternalID  string `json:"external_id"`
}

// An explicit user confirmation creates a separate command so prior execution
// diagnostics and Activity links remain intact.
func (q *Queries) RerunOutputCommand(ctx context.Context, arg RerunOutputCommandParams) (OutputCommand, error) {
	row := q.db.QueryRowContext(ctx, rerunOutputCommand,
		arg.ActionID,
		arg.Key,
		arg.Payload,
		arg.CreatedAt,
		arg.ProfileID,
		arg.SourceKind,
		arg.SourceScope,
		arg.ExternalID,
	)
	var i OutputCommand
	err := row.Scan(
		&i.ID,
		&i.ActionID,
		&i.Key,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.ResultJson,
		&i.Stdout,
		&i.Stderr,
		&i.CreatedAt,
		&i.IsRerun,
		&i.ProfileID,
		&i.SourceKind,
		&i.SourceScope,
		&i.ExternalID,
	)
	return i, err
}

const rescopeInboxItem = `-- name: RescopeInboxItem :exec
UPDATE inbox_item SET source_scope = ?1 WHERE id = ?2
`

type RescopeInboxItemParams struct {
	SourceScope string `json:"source_scope"`
	ID          int64  `json:"id"`
}

// Move a row to a new source_scope. Used to heal pre-#63 rows written with an
// empty scope onto the account-scoped identity every post-#63 read keys on
// (issue #95); the caller only rescopes when the target identity is free, so
// this never collides with the UNIQUE (profile_id, source_kind, source_scope,
// external_id) index.
func (q *Queries) RescopeInboxItem(ctx context.Context, arg RescopeInboxItemParams) error {
	_, err := q.db.ExecContext(ctx, rescopeInboxItem, arg.SourceScope, arg.ID)
	return err
}

const rescopeItemSessions = `-- name: RescopeItemSessions :exec
UPDATE item_session SET source_scope = ?1
WHERE profile_id = ?2
  AND source_kind = ?3
  AND source_scope = ''
  AND external_id = ?4
`

type RescopeItemSessionsParams struct {
	SourceScope string `json:"source_scope"`
	ProfileID   string `json:"profile_id"`
	SourceKind  string `json:"source_kind"`
	ExternalID  string `json:"external_id"`
}

// Follows an inbox row whose source_scope was healed (see
// resolveInboxItemScoped), so links keyed on the old scope stay reachable.
func (q *Queries) RescopeItemSessions(ctx context.Context, arg RescopeItemSessionsParams) error {
	_, err := q.db.ExecContext(ctx, rescopeItemSessions,
		arg.SourceScope,
		arg.ProfileID,
		arg.SourceKind,
		arg.ExternalID,
	)
	return err
}

const retryOutputCommand = `-- name: RetryOutputCommand :exec
UPDATE output_command SET attempts = attempts + 1, last_error = ?, stdout = ?, stderr = ?
WHERE id = ?
`

type RetryOutputCommandParams struct {
	LastError sql.NullString `json:"last_error"`
	Stdout    sql.NullString `json:"stdout"`
	Stderr    sql.NullString `json:"stderr"`
	ID        int64          `json:"id"`
}

func (q *Queries) RetryOutputCommand(ctx context.Context, arg RetryOutputCommandParams) error {
	_, err := q.db.ExecContext(ctx, retryOutputCommand,
		arg.LastError,
		arg.Stdout,
		arg.Stderr,
		arg.ID,
	)
	return err
}

const setAgentWorkspaceSessionAgentID = `-- name: SetAgentWorkspaceSessionAgentID :exec
UPDATE agent_workspace_session SET agent_session_id = ? WHERE id = ?
`

type SetAgentWorkspaceSessionAgentIDParams struct {
	AgentSessionID string `json:"agent_session_id"`
	ID             int64  `json:"id"`
}

// The only write to agent_session_id after the insert: a resume that falls
// back to a fresh launch (the agent has no resume form) mints a new id and
// records it here so a later resume of this same record addresses the
// conversation actually running rather than the one it replaced.
func (q *Queries) SetAgentWorkspaceSessionAgentID(ctx context.Context, arg SetAgentWorkspaceSessionAgentIDParams) error {
	_, err := q.db.ExecContext(ctx, setAgentWorkspaceSessionAgentID, arg.AgentSessionID, arg.ID)
	return err
}

const setInboxItemUnread = `-- name: SetInboxItemUnread :one
UPDATE inbox_item SET unread = ?, revision = revision + 1
WHERE id = ? AND revision = ?
RETURNING id, profile_id, source_kind, source_scope, external_id, title, url, payload, revision, unread, archived_at, archived_actor, archived_reason, lifecycle, source_state, first_seen_at, last_event_at, ignored_at
`

type SetInboxItemUnreadParams struct {
	Unread   int64 `json:"unread"`
	ID       int64 `json:"id"`
	Revision int64 `json:"revision"`
}

func (q *Queries) SetInboxItemUnread(ctx context.Context, arg SetInboxItemUnreadParams) (InboxItem, error) {
	row := q.db.QueryRowContext(ctx, setInboxItemUnread, arg.Unread, arg.ID, arg.Revision)
	var i InboxItem
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.SourceKind,
		&i.SourceScope,
		&i.ExternalID,
		&i.Title,
		&i.Url,
		&i.Payload,
		&i.Revision,
		&i.Unread,
		&i.ArchivedAt,
		&i.ArchivedActor,
		&i.ArchivedReason,
		&i.Lifecycle,
		&i.SourceState,
		&i.FirstSeenAt,
		&i.LastEventAt,
		&i.IgnoredAt,
	)
	return i, err
}

const setJobRunning = `-- name: SetJobRunning :one
UPDATE job SET updated_at = ?, status = ?, step = ?, command_id = ?
WHERE id = ?
RETURNING id, created_at, updated_at, status, label, step, action_id, target, error, command_id
`

type SetJobRunningParams struct {
	UpdatedAt int64         `json:"updated_at"`
	Status    string        `json:"status"`
	Step      string        `json:"step"`
	CommandID sql.NullInt64 `json:"command_id"`
	ID        int64         `json:"id"`
}

// Advance a job to running and link its output_command. This is the ONLY write
// that sets command_id, so terminal transitions can never null it out.
func (q *Queries) SetJobRunning(ctx context.Context, arg SetJobRunningParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, setJobRunning,
		arg.UpdatedAt,
		arg.Status,
		arg.Step,
		arg.CommandID,
		arg.ID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.Label,
		&i.Step,
		&i.ActionID,
		&i.Target,
		&i.Error,
		&i.CommandID,
	)
	return i, err
}

const setJobStatus = `-- name: SetJobStatus :one
UPDATE job SET updated_at = ?, status = ?, step = ?, error = ?
WHERE id = ?
RETURNING id, created_at, updated_at, status, label, step, action_id, target, error, command_id
`

type SetJobStatusParams struct {
	UpdatedAt int64  `json:"updated_at"`
	Status    string `json:"status"`
	Step      string `json:"step"`
	Error     string `json:"error"`
	ID        int64  `json:"id"`
}

// Advance a job's status/step/error WITHOUT touching command_id (used by the
// done/failed terminal transitions). Splitting this from SetJobRunning avoids a
// read-modify-write and prevents clobbering the command link.
func (q *Queries) SetJobStatus(ctx context.Context, arg SetJobStatusParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, setJobStatus,
		arg.UpdatedAt,
		arg.Status,
		arg.Step,
		arg.Error,
		arg.ID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.Label,
		&i.Step,
		&i.ActionID,
		&i.Target,
		&i.Error,
		&i.CommandID,
	)
	return i, err
}

const toggleInboxItemArchived = `-- name: ToggleInboxItemArchived :one
UPDATE inbox_item SET
    ignored_at = CASE WHEN archived_at IS NULL THEN NULL ELSE ignored_at END,
    archived_at = CASE WHEN archived_at IS NULL THEN ? ELSE NULL END,
    archived_actor = CASE WHEN archived_at IS NULL THEN 'manual' ELSE NULL END,
    archived_reason = CASE WHEN archived_at IS NULL THEN 'manual' ELSE NULL END,
    revision = revision + 1
WHERE id = ? AND revision = ?
RETURNING id, profile_id, source_kind, source_scope, external_id, title, url, payload, revision, unread, archived_at, archived_actor, archived_reason, lifecycle, source_state, first_seen_at, last_event_at, ignored_at
`

type ToggleInboxItemArchivedParams struct {
	ArchivedAt sql.NullInt64 `json:"archived_at"`
	ID         int64         `json:"id"`
	Revision   int64         `json:"revision"`
}

func (q *Queries) ToggleInboxItemArchived(ctx context.Context, arg ToggleInboxItemArchivedParams) (InboxItem, error) {
	row := q.db.QueryRowContext(ctx, toggleInboxItemArchived, arg.ArchivedAt, arg.ID, arg.Revision)
	var i InboxItem
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.SourceKind,
		&i.SourceScope,
		&i.ExternalID,
		&i.Title,
		&i.Url,
		&i.Payload,
		&i.Revision,
		&i.Unread,
		&i.ArchivedAt,
		&i.ArchivedActor,
		&i.ArchivedReason,
		&i.Lifecycle,
		&i.SourceState,
		&i.FirstSeenAt,
		&i.LastEventAt,
		&i.IgnoredAt,
	)
	return i, err
}

const toggleInboxItemIgnored = `-- name: ToggleInboxItemIgnored :one
UPDATE inbox_item SET
    ignored_at = CASE WHEN ignored_at IS NULL THEN ? ELSE NULL END,
    unread = CASE WHEN ignored_at IS NULL THEN 0 ELSE 1 END,
    archived_at = CASE WHEN ignored_at IS NULL THEN NULL ELSE archived_at END,
    archived_actor = CASE WHEN ignored_at IS NULL THEN NULL ELSE archived_actor END,
    archived_reason = CASE WHEN ignored_at IS NULL THEN NULL ELSE archived_reason END,
    revision = revision + 1
WHERE id = ? AND revision = ?
RETURNING id, profile_id, source_kind, source_scope, external_id, title, url, payload, revision, unread, archived_at, archived_actor, archived_reason, lifecycle, source_state, first_seen_at, last_event_at, ignored_at
`

type ToggleInboxItemIgnoredParams struct {
	IgnoredAt sql.NullInt64 `json:"ignored_at"`
	ID        int64         `json:"id"`
	Revision  int64         `json:"revision"`
}

func (q *Queries) ToggleInboxItemIgnored(ctx context.Context, arg ToggleInboxItemIgnoredParams) (InboxItem, error) {
	row := q.db.QueryRowContext(ctx, toggleInboxItemIgnored, arg.IgnoredAt, arg.ID, arg.Revision)
	var i InboxItem
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.SourceKind,
		&i.SourceScope,
		&i.ExternalID,
		&i.Title,
		&i.Url,
		&i.Payload,
		&i.Revision,
		&i.Unread,
		&i.ArchivedAt,
		&i.ArchivedActor,
		&i.ArchivedReason,
		&i.Lifecycle,
		&i.SourceState,
		&i.FirstSeenAt,
		&i.LastEventAt,
		&i.IgnoredAt,
	)
	return i, err
}

const touchAgentWorkspaceSession = `-- name: TouchAgentWorkspaceSession :exec
UPDATE agent_workspace_session SET last_opened_at = ? WHERE id = ?
`

type TouchAgentWorkspaceSessionParams struct {
	LastOpenedAt int64 `json:"last_opened_at"`
	ID           int64 `json:"id"`
}

func (q *Queries) TouchAgentWorkspaceSession(ctx context.Context, arg TouchAgentWorkspaceSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchAgentWorkspaceSession, arg.LastOpenedAt, arg.ID)
	return err
}

const updateEventOccurrenceKey = `-- name: UpdateEventOccurrenceKey :exec
UPDATE event_log SET occurrence_key = ? WHERE "offset" = ?
`

type UpdateEventOccurrenceKeyParams struct {
	OccurrenceKey sql.NullString `json:"occurrence_key"`
	Offset        int64          `json:"offset"`
}

func (q *Queries) UpdateEventOccurrenceKey(ctx context.Context, arg UpdateEventOccurrenceKeyParams) error {
	_, err := q.db.ExecContext(ctx, updateEventOccurrenceKey, arg.OccurrenceKey, arg.Offset)
	return err
}

const upsertFeedMembershipClaim = `-- name: UpsertFeedMembershipClaim :exec
INSERT INTO feed_membership_claim (profile_id, feed_id, item_id, source_id)
VALUES (?, ?, ?, ?)
ON CONFLICT (profile_id, feed_id, item_id, source_id) DO NOTHING
`

type UpsertFeedMembershipClaimParams struct {
	ProfileID string `json:"profile_id"`
	FeedID    string `json:"feed_id"`
	ItemID    int64  `json:"item_id"`
	SourceID  string `json:"source_id"`
}

func (q *Queries) UpsertFeedMembershipClaim(ctx context.Context, arg UpsertFeedMembershipClaimParams) error {
	_, err := q.db.ExecContext(ctx, upsertFeedMembershipClaim,
		arg.ProfileID,
		arg.FeedID,
		arg.ItemID,
		arg.SourceID,
	)
	return err
}

const upsertInboxItem = `-- name: UpsertInboxItem :one
INSERT INTO inbox_item (
    profile_id, source_kind, source_scope, external_id,
    title, url, payload, revision, unread,
    archived_at, archived_actor, archived_reason,
    lifecycle, source_state, first_seen_at, last_event_at
) VALUES (?, ?, ?, ?, ?, ?, ?, 1, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (profile_id, source_kind, source_scope, external_id) DO UPDATE SET
    title = excluded.title, url = excluded.url, payload = excluded.payload,
    revision = inbox_item.revision + 1, unread = excluded.unread,
    archived_at = excluded.archived_at, archived_actor = excluded.archived_actor,
    archived_reason = excluded.archived_reason, lifecycle = excluded.lifecycle,
    source_state = excluded.source_state, last_event_at = excluded.last_event_at
RETURNING id, profile_id, source_kind, source_scope, external_id, title, url, payload, revision, unread, archived_at, archived_actor, archived_reason, lifecycle, source_state, first_seen_at, last_event_at, ignored_at
`

type UpsertInboxItemParams struct {
	ProfileID      string         `json:"profile_id"`
	SourceKind     string         `json:"source_kind"`
	SourceScope    string         `json:"source_scope"`
	ExternalID     string         `json:"external_id"`
	Title          string         `json:"title"`
	Url            string         `json:"url"`
	Payload        []byte         `json:"payload"`
	Unread         int64          `json:"unread"`
	ArchivedAt     sql.NullInt64  `json:"archived_at"`
	ArchivedActor  sql.NullString `json:"archived_actor"`
	ArchivedReason sql.NullString `json:"archived_reason"`
	Lifecycle      string         `json:"lifecycle"`
	SourceState    sql.NullString `json:"source_state"`
	FirstSeenAt    int64          `json:"first_seen_at"`
	LastEventAt    int64          `json:"last_event_at"`
}

func (q *Queries) UpsertInboxItem(ctx context.Context, arg UpsertInboxItemParams) (InboxItem, error) {
	row := q.db.QueryRowContext(ctx, upsertInboxItem,
		arg.ProfileID,
		arg.SourceKind,
		arg.SourceScope,
		arg.ExternalID,
		arg.Title,
		arg.Url,
		arg.Payload,
		arg.Unread,
		arg.ArchivedAt,
		arg.ArchivedActor,
		arg.ArchivedReason,
		arg.Lifecycle,
		arg.SourceState,
		arg.FirstSeenAt,
		arg.LastEventAt,
	)
	var i InboxItem
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.SourceKind,
		&i.SourceScope,
		&i.ExternalID,
		&i.Title,
		&i.Url,
		&i.Payload,
		&i.Revision,
		&i.Unread,
		&i.ArchivedAt,
		&i.ArchivedActor,
		&i.ArchivedReason,
		&i.Lifecycle,
		&i.SourceState,
		&i.FirstSeenAt,
		&i.LastEventAt,
		&i.IgnoredAt,
	)
	return i, err
}

const upsertNodeKV = `-- name: UpsertNodeKV :exec
INSERT INTO node_kv (flow_id, node_id, scope, key, value, expires_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (flow_id, node_id, scope, key) DO UPDATE SET
    value = excluded.value, expires_at = excluded.expires_at, updated_at = excluded.updated_at
`

type UpsertNodeKVParams struct {
	FlowID    string        `json:"flow_id"`
	NodeID    string        `json:"node_id"`
	Scope     string        `json:"scope"`
	Key       string        `json:"key"`
	Value     string        `json:"value"`
	ExpiresAt sql.NullInt64 `json:"expires_at"`
	UpdatedAt int64         `json:"updated_at"`
}

func (q *Queries) UpsertNodeKV(ctx context.Context, arg UpsertNodeKVParams) error {
	_, err := q.db.ExecContext(ctx, upsertNodeKV,
		arg.FlowID,
		arg.NodeID,
		arg.Scope,
		arg.Key,
		arg.Value,
		arg.ExpiresAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertScheduleCursor = `-- name: UpsertScheduleCursor :exec
INSERT INTO schedule_cursor (workspace, schedule_id, evaluated_through, cron)
VALUES (?, ?, ?, ?)
ON CONFLICT (workspace, schedule_id) DO UPDATE SET
    evaluated_through = excluded.evaluated_through, cron = excluded.cron
`

type UpsertScheduleCursorParams struct {
	Workspace        string `json:"workspace"`
	ScheduleID       string `json:"schedule_id"`
	EvaluatedThrough int64  `json:"evaluated_through"`
	Cron             string `json:"cron"`
}

func (q *Queries) UpsertScheduleCursor(ctx context.Context, arg UpsertScheduleCursorParams) error {
	_, err := q.db.ExecContext(ctx, upsertScheduleCursor,
		arg.Workspace,
		arg.ScheduleID,
		arg.EvaluatedThrough,
		arg.Cron,
	)
	return err
}

const upsertSourceHead = `-- name: UpsertSourceHead :exec
INSERT INTO source_head (topic, key, payload)
VALUES (?, ?, ?)
ON CONFLICT(topic, key) DO UPDATE SET payload = excluded.payload
`

type UpsertSourceHeadParams struct {
	Topic   string `json:"topic"`
	Key     string `json:"key"`
	Payload []byte `json:"payload"`
}

func (q *Queries) UpsertSourceHead(ctx context.Context, arg UpsertSourceHeadParams) error {
	_, err := q.db.ExecContext(ctx, upsertSourceHead, arg.Topic, arg.Key, arg.Payload)
	return err
}

const upsertWebhookCapture = `-- name: UpsertWebhookCapture :exec
INSERT INTO webhook_capture (topic, received_at, body)
VALUES (?, ?, ?)
ON CONFLICT (topic) DO UPDATE SET received_at = excluded.received_at, body = excluded.body
`

type UpsertWebhookCaptureParams struct {
	Topic      string `json:"topic"`
	ReceivedAt int64  `json:"received_at"`
	Body       []byte `json:"body"`
}

func (q *Queries) UpsertWebhookCapture(ctx context.Context, arg UpsertWebhookCaptureParams) error {
	_, err := q.db.ExecContext(ctx, upsertWebhookCapture, arg.Topic, arg.ReceivedAt, arg.Body)
	return err
}
