// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails service exposing authentication to the frontend.
 * State changes are pushed via the auth:updated event; the frontend re-reads
 * Status on receipt.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CancelDeviceFlow(): $CancellablePromise<void> {
    return $Call.ByID(2622709662);
}

export function SetToken(token: string): $CancellablePromise<$models.Status> {
    return $Call.ByID(253308431, token);
}

export function SignOut(): $CancellablePromise<void> {
    return $Call.ByID(2986637625);
}

export function StartDeviceFlow(): $CancellablePromise<$models.DeviceFlowInfo> {
    return $Call.ByID(1619800028);
}

export function Status(): $CancellablePromise<$models.Status> {
    return $Call.ByID(144283588);
}
