// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.4

// Built By: go install

package todo

import (
	"fmt"
	"strings"
)

const (
	// SourceAgent is a Source of type agent.
	SourceAgent Source = "agent"
	// SourceHuman is a Source of type human.
	SourceHuman Source = "human"
	// SourceSystem is a Source of type system.
	SourceSystem Source = "system"
)

var ErrInvalidSource = fmt.Errorf("not a valid Source, try [%s]", strings.Join(_SourceNames, ", "))

var _SourceNames = []string{
	string(SourceAgent),
	string(SourceHuman),
	string(SourceSystem),
}

// SourceNames returns a list of possible string values of Source.
func SourceNames() []string {
	tmp := make([]string, len(_SourceNames))
	copy(tmp, _SourceNames)
	return tmp
}

// String implements the Stringer interface.
func (x Source) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Source) IsValid() bool {
	_, err := ParseSource(string(x))
	return err == nil
}

var _SourceValue = map[string]Source{
	"agent":  SourceAgent,
	"human":  SourceHuman,
	"system": SourceSystem,
}

// ParseSource attempts to convert a string to a Source.
func ParseSource(name string) (Source, error) {
	if x, ok := _SourceValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _SourceValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return Source(""), fmt.Errorf("%s is %w", name, ErrInvalidSource)
}

// MarshalText implements the text marshaller method.
func (x Source) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Source) UnmarshalText(text []byte) error {
	tmp, err := ParseSource(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *Source) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// StatusPending is a Status of type pending.
	StatusPending Status = "pending"
	// StatusAcknowledged is a Status of type acknowledged.
	StatusAcknowledged Status = "acknowledged"
	// StatusCompleted is a Status of type completed.
	StatusCompleted Status = "completed"
	// StatusDismissed is a Status of type dismissed.
	StatusDismissed Status = "dismissed"
)

var ErrInvalidStatus = fmt.Errorf("not a valid Status, try [%s]", strings.Join(_StatusNames, ", "))

var _StatusNames = []string{
	string(StatusPending),
	string(StatusAcknowledged),
	string(StatusCompleted),
	string(StatusDismissed),
}

// StatusNames returns a list of possible string values of Status.
func StatusNames() []string {
	tmp := make([]string, len(_StatusNames))
	copy(tmp, _StatusNames)
	return tmp
}

// String implements the Stringer interface.
func (x Status) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Status) IsValid() bool {
	_, err := ParseStatus(string(x))
	return err == nil
}

var _StatusValue = map[string]Status{
	"pending":      StatusPending,
	"acknowledged": StatusAcknowledged,
	"completed":    StatusCompleted,
	"dismissed":    StatusDismissed,
}

// ParseStatus attempts to convert a string to a Status.
func ParseStatus(name string) (Status, error) {
	if x, ok := _StatusValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _StatusValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return Status(""), fmt.Errorf("%s is %w", name, ErrInvalidStatus)
}

// MarshalText implements the text marshaller method.
func (x Status) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Status) UnmarshalText(text []byte) error {
	tmp, err := ParseStatus(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *Status) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
