// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.4

// Built By: go install

package hc

import (
	"fmt"
	"strings"
)

const (
	// ItemTypeEpic is a ItemType of type epic.
	ItemTypeEpic ItemType = "epic"
	// ItemTypeTask is a ItemType of type task.
	ItemTypeTask ItemType = "task"
)

var ErrInvalidItemType = fmt.Errorf("not a valid ItemType, try [%s]", strings.Join(_ItemTypeNames, ", "))

var _ItemTypeNames = []string{
	string(ItemTypeEpic),
	string(ItemTypeTask),
}

// ItemTypeNames returns a list of possible string values of ItemType.
func ItemTypeNames() []string {
	tmp := make([]string, len(_ItemTypeNames))
	copy(tmp, _ItemTypeNames)
	return tmp
}

// String implements the Stringer interface.
func (x ItemType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ItemType) IsValid() bool {
	_, err := ParseItemType(string(x))
	return err == nil
}

var _ItemTypeValue = map[string]ItemType{
	"epic": ItemTypeEpic,
	"task": ItemTypeTask,
}

// ParseItemType attempts to convert a string to a ItemType.
func ParseItemType(name string) (ItemType, error) {
	if x, ok := _ItemTypeValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _ItemTypeValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return ItemType(""), fmt.Errorf("%s is %w", name, ErrInvalidItemType)
}

// MarshalText implements the text marshaller method.
func (x ItemType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ItemType) UnmarshalText(text []byte) error {
	tmp, err := ParseItemType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *ItemType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// StatusOpen is a Status of type open.
	StatusOpen Status = "open"
	// StatusInProgress is a Status of type in_progress.
	StatusInProgress Status = "in_progress"
	// StatusDone is a Status of type done.
	StatusDone Status = "done"
	// StatusCancelled is a Status of type cancelled.
	StatusCancelled Status = "cancelled"
)

var ErrInvalidStatus = fmt.Errorf("not a valid Status, try [%s]", strings.Join(_StatusNames, ", "))

var _StatusNames = []string{
	string(StatusOpen),
	string(StatusInProgress),
	string(StatusDone),
	string(StatusCancelled),
}

// StatusNames returns a list of possible string values of Status.
func StatusNames() []string {
	tmp := make([]string, len(_StatusNames))
	copy(tmp, _StatusNames)
	return tmp
}

// String implements the Stringer interface.
func (x Status) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Status) IsValid() bool {
	_, err := ParseStatus(string(x))
	return err == nil
}

var _StatusValue = map[string]Status{
	"open":        StatusOpen,
	"in_progress": StatusInProgress,
	"done":        StatusDone,
	"cancelled":   StatusCancelled,
}

// ParseStatus attempts to convert a string to a Status.
func ParseStatus(name string) (Status, error) {
	if x, ok := _StatusValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _StatusValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return Status(""), fmt.Errorf("%s is %w", name, ErrInvalidStatus)
}

// MarshalText implements the text marshaller method.
func (x Status) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Status) UnmarshalText(text []byte) error {
	tmp, err := ParseStatus(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *Status) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
