package main

import (
	"net/http"
	"sort"
	"time"

	"github.com/hay-kot/httpkit/server"
)

// StateView is the dashboard's single read. One endpoint keeps the page a
// plain poll rather than a fan of requests that can disagree with each other.
type StateView struct {
	Upstream  string               `json:"upstream"`
	CacheTTL  string               `json:"cacheTTL"`
	Entries   int                  `json:"cacheEntries"`
	Stats     Stats                `json:"stats"`
	Items     []Item               `json:"items"`
	Overlays  map[string]Mutations `json:"overlays"`
	Scenarios []ScenarioView       `json:"scenarios"`
	Targets   []WebhookTarget      `json:"targets"`
	Payloads  []string             `json:"payloads"`
	Recent    []LogEntry           `json:"recent"`
	Pushes    []PushResult         `json:"pushes"`
	Actions   []ActionView         `json:"actions"`
}

// ScenarioView is one in-flight scenario. Scenarios are generated by callers
// rather than configured, so only running ones exist to report.
type ScenarioView struct {
	Name  string `json:"name"`
	Steps int    `json:"steps"`
}

// ActionView describes one available quick action, so the dashboard renders
// whatever the vocabulary contains rather than hardcoding a parallel list.
type ActionView struct {
	Name  string `json:"name"`
	Label string `json:"label"`
}

func (c *Control) State(w http.ResponseWriter, _ *http.Request) error {
	stats, recent := c.proxy.Snapshot()

	c.mu.Lock()
	scenarios := make([]ScenarioView, 0, len(c.scenarios))
	for name, steps := range c.scenarios {
		scenarios = append(scenarios, ScenarioView{Name: name, Steps: steps})
	}
	c.mu.Unlock()
	sort.Slice(scenarios, func(i, j int) bool { return scenarios[i].Name < scenarios[j].Name })

	actions := make([]ActionView, 0, len(actionOrder))
	for _, name := range actionOrder {
		actions = append(actions, ActionView{Name: name, Label: quickActions[name].label})
	}

	return server.JSON(w, http.StatusOK, StateView{
		Upstream:  c.cfg.Upstream,
		CacheTTL:  c.cfg.Cache.TTL.String(),
		Entries:   c.cache.Entries(),
		Stats:     stats,
		Items:     c.store.Items(),
		Overlays:  c.store.Overlays(),
		Scenarios: scenarios,
		Targets:   c.pusher.Targets(),
		Payloads:  c.pusher.PayloadNames(),
		Recent:    recent,
		Pushes:    c.pusher.Recent(),
		Actions:   actions,
	})
}

// HealthView is a superset of devproxy.Health: Probe reads only Devserver, so
// the readiness fields do not change the probe contract.
type HealthView struct {
	Devserver      bool      `json:"devserver"`
	AppConnected   bool      `json:"appConnected"`
	Requests       int64     `json:"requests"`
	UpstreamCalls  int64     `json:"upstreamCalls"`
	ItemsObserved  int       `json:"itemsObserved"`
	CacheEntries   int       `json:"cacheEntries"`
	LastUpstreamAt time.Time `json:"lastUpstreamAt"`
}

// Health writes Devserver first so the standby-vs-foreign answer never
// hinges on the readiness read.
func (c *Control) Health(w http.ResponseWriter, _ *http.Request) error {
	stats, _ := c.proxy.Snapshot()
	return server.JSON(w, http.StatusOK, HealthView{
		Devserver:      true,
		AppConnected:   stats.Requests > 0,
		Requests:       stats.Requests,
		UpstreamCalls:  stats.UpstreamCalls,
		ItemsObserved:  len(c.store.Items()),
		CacheEntries:   c.cache.Entries(),
		LastUpstreamAt: stats.LastUpstreamAt,
	})
}
