// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Instance is one connected Gitea or Forgejo account, as the Integrations
 * screen renders it.
 */
export interface Instance {
    "account": string;
    "url": string;
    "login": string;
    "name": string;
    "version": string;
}
