// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Input carries the caller-supplied context a prompt needs beyond Env. Every
 * field is optional; a prompt that needs one documents it on its definition.
 */
export interface Input {
    /**
     * WebhookPath and WebhookSample scope the webhook transform prompt to one
     * sources.webhook node: its configured path and its last captured delivery.
     */
    "webhookPath": string;
    "webhookSample": string;
}

/**
 * Prompt is one rendered, copyable prompt.
 */
export interface Prompt {
    "id": string;

    /**
     * Title and Description label the entry in the settings catalog.
     */
    "title": string;
    "description": string;

    /**
     * Target names what the prompt configures — a path for file-backed
     * prompts, a surface name otherwise — shown under the title.
     */
    "target": string;

    /**
     * Text is the prompt itself: what the copy button puts on the clipboard.
     */
    "text": string;
}
