// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ActionsService is the explicit editor API for the global actions catalog.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as actions$0 from "../../app/actions/models.js";

export function CreateAction(a: actions$0.EditableAction): $CancellablePromise<actions$0.EditableAction> {
    return $Call.ByID(1408174538, a);
}

export function DeleteAction(id: string): $CancellablePromise<void> {
    return $Call.ByID(1950457013, id);
}

export function GetAction(id: string): $CancellablePromise<actions$0.EditableAction> {
    return $Call.ByID(1642808218, id);
}

/**
 * ListActions returns the effective last-good catalog and a current parse
 * error, if a hand edit made the latest actions.yml invalid.
 */
export function ListActions(): $CancellablePromise<actions$0.EditableCatalog> {
    return $Call.ByID(998142743);
}

/**
 * ReorderActions persists the catalog order the settings list was dragged
 * into. ids must be the full catalog; a stale list (a hand edit added or
 * removed an action meanwhile) is rejected so the caller reloads.
 */
export function ReorderActions(ids: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(8930906, ids);
}

export function UpdateAction(id: string, a: actions$0.EditableAction): $CancellablePromise<actions$0.EditableAction> {
    return $Call.ByID(1928360735, id, a);
}
