// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ActivityService exposes the desktop's activity log to the frontend: the
 * Activity view reads pages through List and records its own events through
 * Record. Backend subsystems do not go through here — they hold the recorder.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as activity$0 from "../../app/activity/models.js";

/**
 * List returns up to limit activity events with id < before, newest first.
 * The frontend passes 0 for the first page.
 */
export function List(before: number, limit: number): $CancellablePromise<activity$0.Event[] | null> {
    return $Call.ByID(871906718, before, limit);
}

/**
 * Record appends a frontend-originated event and returns the stored row.
 */
export function Record(input: activity$0.RecordInput): $CancellablePromise<activity$0.Event> {
    return $Call.ByID(3536654567, input);
}
