// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AuthService is the Wails service exposing authentication to the frontend.
 * State changes are pushed via the auth:updated event; the frontend re-reads
 * Status on receipt.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as auth$0 from "../../app/auth/models.js";

export function CancelDeviceFlow(): $CancellablePromise<void> {
    return $Call.ByID(1747166401);
}

export function SetToken(token: string): $CancellablePromise<auth$0.Status> {
    return $Call.ByID(1169658288, token);
}

export function SignOut(): $CancellablePromise<void> {
    return $Call.ByID(1026375320);
}

export function StartDeviceFlow(): $CancellablePromise<auth$0.DeviceFlowInfo> {
    return $Call.ByID(474656501);
}

export function Status(): $CancellablePromise<auth$0.Status> {
    return $Call.ByID(3434465215);
}
