// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FlowsService exposes the flow definitions to the frontend graph editor.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as flow$0 from "../../app/flow/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreateFlow(name: string): $CancellablePromise<$models.FlowSummary> {
    return $Call.ByID(2011944446, name);
}

export function DeleteFlow(id: string): $CancellablePromise<void> {
    return $Call.ByID(4075818113, id);
}

export function GetFlow(id: string): $CancellablePromise<flow$0.Flow> {
    return $Call.ByID(2384703294, id);
}

export function GetLayout(id: string): $CancellablePromise<flow$0.Layout> {
    return $Call.ByID(2097594588, id);
}

export function GetSidebar(id: string): $CancellablePromise<flow$0.SidebarLayout> {
    return $Call.ByID(3616802494, id);
}

/**
 * ListFlows returns one summary per flow file, valid and invalid alike.
 */
export function ListFlows(): $CancellablePromise<$models.FlowSummary[] | null> {
    return $Call.ByID(993012807);
}

export function RenameFlow(id: string, name: string): $CancellablePromise<$models.FlowSummary> {
    return $Call.ByID(3264506312, id, name);
}

export function SaveFlow(f: flow$0.Flow): $CancellablePromise<void> {
    return $Call.ByID(582447999, f);
}

export function SaveLayout(id: string, layout: flow$0.Layout): $CancellablePromise<void> {
    return $Call.ByID(2815114505, id, layout);
}

export function SaveSidebar(id: string, layout: flow$0.SidebarLayout): $CancellablePromise<void> {
    return $Call.ByID(1405338909, id, layout);
}

export function SetFlowEnabled(id: string, enabled: boolean): $CancellablePromise<$models.FlowSummary> {
    return $Call.ByID(2806455367, id, enabled);
}
