// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GitHubService exposes the GitHub connector's connection to the frontend:
 * the device flow, the PAT fallback, and disconnecting. State changes are
 * pushed via the connection:updated signal; the frontend re-reads Status on
 * receipt.
 * 
 * It is one connector's service, not the app's login. Nothing in the app is
 * gated on it returning connected.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as github$0 from "../../app/sources/github/models.js";

export function CancelDeviceFlow(): $CancellablePromise<void> {
    return $Call.ByID(3120315940);
}

export function Disconnect(): $CancellablePromise<void> {
    return $Call.ByID(3614816186);
}

export function SetToken(token: string): $CancellablePromise<github$0.ConnectionStatus> {
    return $Call.ByID(1555568965, token);
}

export function StartDeviceFlow(): $CancellablePromise<github$0.DeviceFlowInfo> {
    return $Call.ByID(1541860354);
}

export function Status(): $CancellablePromise<github$0.ConnectionStatus> {
    return $Call.ByID(4133175778);
}
