// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GrafanaService exposes the Grafana connector's stack auth to the frontend:
 * connecting a stack by pasting its URL and a service-account token, and
 * disconnecting one. State changes are pushed via the connection:updated
 * signal; the frontend re-reads the Integrations list on receipt.
 * 
 * It is one connector's service, not the app's login. Nothing in the app is
 * gated on a stack being connected.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as grafana$0 from "../../app/sources/grafana/models.js";

export function Connect(url: string, token: string): $CancellablePromise<grafana$0.Stack> {
    return $Call.ByID(140703095, url, token);
}

export function Disconnect(account: string): $CancellablePromise<void> {
    return $Call.ByID(3171311689, account);
}
