// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HiveConfigService exposes the external Hive CLI configuration to first run
 * and to Settings ▸ Hive CLI: which agent starts a session and which folders
 * hold the repositories the session picker offers.
 * 
 * Every method is a straight call into the core. The native folder picker the
 * workspace list uses is SystemService.ChooseDirectory, which already exists
 * for the data/config directory overrides.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../../app/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as hiveconf$0 from "../../app/hiveconf/models.js";

/**
 * InspectWorkspace validates a chosen folder and counts the repositories in
 * it, so the picker can confirm the choice before it is saved.
 */
export function InspectWorkspace(path: string): $CancellablePromise<hiveconf$0.Workspace> {
    return $Call.ByID(1533427038, path);
}

/**
 * Save writes the configuration and reloads the running Hive services from it.
 */
export function Save(req: app$0.HiveSetupRequest): $CancellablePromise<app$0.HiveSetup> {
    return $Call.ByID(3830150062, req);
}

/**
 * Setup reports what the Hive config declares and which agents are installed.
 */
export function Setup(): $CancellablePromise<app$0.HiveSetup> {
    return $Call.ByID(169371636);
}
