// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ObservabilityService exposes runtime statistics and telemetry export status.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Settings returns telemetry configuration and exporter status.
 */
export function Settings(): $CancellablePromise<$models.ObservabilitySettings> {
    return $Call.ByID(520190855);
}

/**
 * Stats samples current process and runtime resource use.
 */
export function Stats(): $CancellablePromise<$models.RuntimeStats> {
    return $Call.ByID(799363537);
}
