// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PipelineService exposes the inbox to the frontend. Every method is a
 * request build plus one call into the core.
 * 
 * The event log is not on this surface. Reading it, committing runs against
 * it, and the replay protocol used to be RPCs because the graph ran in the
 * browser; with the engine in Go they are internal calls, and the
 * decimal-string offset encoding they needed to survive the JavaScript number
 * boundary went with them.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as actions$0 from "../../app/actions/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as stores$0 from "../../app/data/stores/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dispatch$0 from "../../app/dispatch/models.js";

export function ActionRun(commandID: number): $CancellablePromise<dispatch$0.ActionRunView> {
    return $Call.ByID(1655642280, commandID);
}

export function ActionViews(itemID: number): $CancellablePromise<actions$0.View[] | null> {
    return $Call.ByID(3356906731, itemID);
}

export function Events(itemID: number, limit: number): $CancellablePromise<stores$0.InboxEvent[] | null> {
    return $Call.ByID(4125924180, itemID, limit);
}

export function Feed(profileID: string, itemID: number): $CancellablePromise<string> {
    return $Call.ByID(4173616213, profileID, itemID);
}

export function FeedCounts(profileID: string): $CancellablePromise<stores$0.FeedCount[] | null> {
    return $Call.ByID(444584149, profileID);
}

export function InvokeAction(actionID: string, itemID: number, input: dispatch$0.ActionInvocationInput): $CancellablePromise<dispatch$0.ActionRunView> {
    return $Call.ByID(1680026695, actionID, itemID, input);
}

export function ListArchivedByFeed(profileID: string, feedID: string, limit: number): $CancellablePromise<stores$0.InboxItem[] | null> {
    return $Call.ByID(2031154650, profileID, feedID, limit);
}

export function ListByFeed(profileID: string, feedID: string, limit: number): $CancellablePromise<stores$0.InboxItem[] | null> {
    return $Call.ByID(3350169100, profileID, feedID, limit);
}

export function ListTrash(profileID: string, limit: number): $CancellablePromise<stores$0.InboxItem[] | null> {
    return $Call.ByID(2143013553, profileID, limit);
}

export function MarkRead(profileID: string, feedID: string): $CancellablePromise<number> {
    return $Call.ByID(317389540, profileID, feedID);
}

export function NewSessionDraft(itemID: number): $CancellablePromise<dispatch$0.SessionDraft> {
    return $Call.ByID(2051065966, itemID);
}

export function NodeRuns(flowID: string, limit: number): $CancellablePromise<stores$0.NodeRunRecord[] | null> {
    return $Call.ByID(3592664483, flowID, limit);
}

/**
 * RenderClipboardAction returns the text a clipboard action renders for an
 * item. The frontend writes it to the clipboard through the native Wails
 * clipboard; the core produces the text and never touches the clipboard.
 */
export function RenderClipboardAction(actionID: string, itemID: number, inputs: { [_ in string]?: string } | null): $CancellablePromise<string> {
    return $Call.ByID(3812385739, actionID, itemID, inputs);
}

export function SetUnread(itemID: number, revision: number, unread: boolean): $CancellablePromise<stores$0.InboxItem> {
    return $Call.ByID(783512488, itemID, revision, unread);
}

export function ToggleArchived(itemID: number, revision: number): $CancellablePromise<stores$0.InboxItem> {
    return $Call.ByID(756635811, itemID, revision);
}

export function ToggleIgnored(itemID: number, revision: number): $CancellablePromise<stores$0.InboxItem> {
    return $Call.ByID(1613598741, itemID, revision);
}
