// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PipelineService is the Wails service exposing the desktop pipeline's
 * event log, configured actions, and commit protocol to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as actions$0 from "../../app/actions/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dispatch$0 from "../../app/dispatch/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../../app/store/models.js";

export function ActionRun(commandID: number): $CancellablePromise<dispatch$0.ActionRunView> {
    return $Call.ByID(1655642280, commandID);
}

/**
 * ActionViews returns the configured actions applicable to an inbox item:
 * shown-in-detail, applies_to matches the item's canonical kind, and every
 * hard template capability is satisfiable for the item's payload.
 */
export function ActionViews(itemID: number): $CancellablePromise<actions$0.View[] | null> {
    return $Call.ByID(3356906731, itemID);
}

/**
 * ActivateReplay atomically advances the consumer and installs the prepared
 * membership state for a startup or deploy replay.
 */
export function ActivateReplay(profileID: string, tail: string, claims: store$0.FeedMembershipClaim[] | null, feedIDs: string[] | null, sourceIDs: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(404315423, profileID, tail, claims, feedIDs, sourceIDs);
}

/**
 * Commit applies the frontend graph runtime's batch atomically. Feed outputs
 * are accepted without durable effect until membership claims land; action
 * outputs, node-run metrics, and the consumer offset are persisted atomically.
 * Idempotent by offset: replaying a batch already applied (UpToOffset <= the
 * consumer's current offset) is a no-op.
 */
export function Commit(batch: store$0.CommitBatch): $CancellablePromise<void> {
    return $Call.ByID(1748285836, batch);
}

/**
 * EventLogTailOffset returns a Wails-safe decimal tail for the startup/deploy
 * replay protocol.
 */
export function EventLogTailOffset(): $CancellablePromise<string> {
    return $Call.ByID(1303973178);
}

export function FeedCounts(profileID: string): $CancellablePromise<store$0.FeedInboxCount[] | null> {
    return $Call.ByID(444584149, profileID);
}

export function InboxItemEvents(itemID: number, limit: number): $CancellablePromise<store$0.InboxEventView[] | null> {
    return $Call.ByID(1903831253, itemID, limit);
}

/**
 * InboxItemFeed returns the feed that holds an item, or "" when no feed
 * claims it (an unrouted item, shown in Trash). The frontend uses it to turn
 * a clicked notification into a feed route that reveals the item.
 */
export function InboxItemFeed(profileID: string, itemID: number): $CancellablePromise<string> {
    return $Call.ByID(4206645656, profileID, itemID);
}

/**
 * InvokeAction records the user's explicit confirmation for actionID against
 * item and executes it. It accepts only actions that apply to the item's kind;
 * executable configuration is always re-resolved from ActionStore.
 */
export function InvokeAction(actionID: string, itemID: number, input: dispatch$0.ActionInvocationInput): $CancellablePromise<dispatch$0.ActionRunView> {
    return $Call.ByID(1680026695, actionID, itemID, input);
}

/**
 * ListArchivedInboxItemsByFeed returns a feed's archived section, loaded
 * lazily when the user expands the archived divider.
 */
export function ListArchivedInboxItemsByFeed(profileID: string, feedID: string, limit: number): $CancellablePromise<store$0.InboxItemView[] | null> {
    return $Call.ByID(2837386034, profileID, feedID, limit);
}

export function ListInboxItemsByFeed(profileID: string, feedID: string, limit: number): $CancellablePromise<store$0.InboxItemView[] | null> {
    return $Call.ByID(2653900732, profileID, feedID, limit);
}

/**
 * ListInboxItemsTrash returns unrouted and ignored items for the Trash
 * utility view.
 */
export function ListInboxItemsTrash(profileID: string, limit: number): $CancellablePromise<store$0.InboxItemView[] | null> {
    return $Call.ByID(31725505, profileID, limit);
}

/**
 * ListReplaySourceSnapshots returns each source's latest authoritative
 * snapshot so membership replay preserves source provenance.
 */
export function ListReplaySourceSnapshots(profileID: string, throughOffset: string): $CancellablePromise<store$0.Msg[] | null> {
    return $Call.ByID(3559261984, profileID, throughOffset);
}

/**
 * ListUnarchivedInboxItems returns the JSON/Wails-friendly immutable inbox
 * identity and payload needed for claims-only synthetic replay.
 */
export function ListUnarchivedInboxItems(profileID: string): $CancellablePromise<store$0.InboxItemView[] | null> {
    return $Call.ByID(3455889604, profileID);
}

export function MarkInboxItemUnread(itemID: number, revision: number, unread: boolean): $CancellablePromise<store$0.InboxItemView> {
    return $Call.ByID(4238206404, itemID, revision, unread);
}

/**
 * MarkInboxItemsRead clears unread for a whole scope in one write: the named
 * feed, or every feed in the workspace when feedID is empty. Archived and
 * ignored items keep their state. It returns the number of items cleared,
 * which is what the frontend reports back to the user.
 */
export function MarkInboxItemsRead(profileID: string, feedID: string): $CancellablePromise<number> {
    return $Call.ByID(974783704, profileID, feedID);
}

/**
 * NodeRuns returns up to limit of a flow's most recent node_run rows,
 * newest first, for the flows canvas's live per-node status and RECENT
 * activity list.
 */
export function NodeRuns(flowID: string, limit: number): $CancellablePromise<store$0.NodeRunRecord[] | null> {
    return $Call.ByID(3592664483, flowID, limit);
}

/**
 * ReadFrom returns up to limit event_log rows after consumer's persisted
 * offset, in ascending order. The frontend never supplies an offset: the
 * SQLite checkpoint is the source of truth across runtime restarts.
 */
export function ReadFrom(consumer: string, limit: number): $CancellablePromise<store$0.Msg[] | null> {
    return $Call.ByID(1752659845, consumer, limit);
}

/**
 * SessionLaunchOptions supplies the configured repository and agent choices
 * for interactive launch-session actions. It intentionally exposes no local
 * checkout paths or executable action configuration.
 */
export function SessionLaunchOptions(): $CancellablePromise<dispatch$0.SessionLaunchOptions> {
    return $Call.ByID(446957222);
}

export function ToggleInboxItemArchived(itemID: number, revision: number): $CancellablePromise<store$0.InboxItemView> {
    return $Call.ByID(2209910498, itemID, revision);
}

export function ToggleInboxItemIgnored(itemID: number, revision: number): $CancellablePromise<store$0.InboxItemView> {
    return $Call.ByID(1906272206, itemID, revision);
}
