// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PopupTerminalService is the pop-up's bootstrap and nothing else: opening,
 * closing and streaming a terminal all go over the loopback HTTP surface, so
 * neither the control plane nor the data plane crosses the Wails bridge.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Available reports whether a pop-up terminal can be opened, with a reason the
 * frontend renders as-is when it cannot.
 */
export function Available(): $CancellablePromise<$models.PopupTerminalAvailability> {
    return $Call.ByID(503387436);
}

/**
 * Endpoint reports where the pop-up's surface is reachable, or KindUnavailable
 * when this run has no loopback server or no token to reach it with.
 */
export function Endpoint(): $CancellablePromise<$models.PopupTerminalEndpoint> {
    return $Call.ByID(1537852312);
}
