// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Preview($in: $models.ReportInput): $CancellablePromise<$models.ReportPreview> {
    return $Call.ByID(2830240947, $in);
}

export function Submit($in: $models.ReportInput): $CancellablePromise<$models.ReportResult> {
    return $Call.ByID(2664891537, $in);
}
