// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function IssueURL(): $CancellablePromise<string> {
    return $Call.ByID(2612044405);
}

export function Preview(): $CancellablePromise<$models.ReportPreview> {
    return $Call.ByID(2830240947);
}

export function Save($in: $models.ReportInput): $CancellablePromise<$models.ReportResult> {
    return $Call.ByID(540616300, $in);
}
