// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SessionService is the frontend API for the New Session form and for managing
 * the sessions that exist.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dispatch$0 from "../../app/dispatch/models.js";

/**
 * CreateSession validates the form and starts the session as a background job,
 * returning the job id. Its outcome surfaces in the jobs UI.
 */
export function CreateSession(req: dispatch$0.CreateSessionRequest): $CancellablePromise<number> {
    return $Call.ByID(4281714313, req);
}

/**
 * DeleteSession starts the delete as a background job and returns the job id.
 */
export function DeleteSession(id: string): $CancellablePromise<number> {
    return $Call.ByID(3432643808, id);
}

/**
 * ListSessions returns every session in every state; Slug is the tmux target an
 * attach uses, and only an active session has one.
 */
export function ListSessions(): $CancellablePromise<dispatch$0.SessionSummary[] | null> {
    return $Call.ByID(220196846);
}

/**
 * PruneSessions starts the prune of every recycled and corrupted session as a
 * background job and returns the job id.
 */
export function PruneSessions(): $CancellablePromise<number> {
    return $Call.ByID(3377171188);
}

/**
 * RecycleSession starts the recycle as a background job and returns the job id.
 */
export function RecycleSession(id: string): $CancellablePromise<number> {
    return $Call.ByID(1670381516, id);
}

/**
 * RenameSession renames a session and returns its new summary. The slug in it
 * is the new tmux target: renaming re-slugs, so an attached caller has to
 * re-attach under the name that comes back.
 */
export function RenameSession(id: string, name: string): $CancellablePromise<dispatch$0.SessionSummary> {
    return $Call.ByID(3421065663, id, name);
}

/**
 * SessionDetail reads one session in full, for the detail view.
 */
export function SessionDetail(id: string): $CancellablePromise<dispatch$0.SessionDetail> {
    return $Call.ByID(3289077136, id);
}

export function SessionLaunchOptions(): $CancellablePromise<dispatch$0.SessionLaunchOptions> {
    return $Call.ByID(715924228);
}

/**
 * SessionRisk reports the uncommitted or unpushed work a delete or recycle
 * would discard, for the confirmation that precedes one.
 */
export function SessionRisk(id: string): $CancellablePromise<dispatch$0.SessionRisk> {
    return $Call.ByID(2710389542, id);
}

/**
 * SetSessionGroup sets a session's group; an empty group clears it.
 */
export function SetSessionGroup(id: string, group: string): $CancellablePromise<void> {
    return $Call.ByID(4133128838, id, group);
}
