// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SessionService is the frontend API for the New Session form.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dispatch$0 from "../../app/dispatch/models.js";

export function CreateSession(req: dispatch$0.CreateSessionRequest): $CancellablePromise<dispatch$0.SessionExecutionOutcome> {
    return $Call.ByID(4281714313, req);
}

export function SessionLaunchOptions(): $CancellablePromise<dispatch$0.SessionLaunchOptions> {
    return $Call.ByID(715924228);
}
