// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SessionService is the frontend API for the New Session form.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dispatch$0 from "../../app/dispatch/models.js";

/**
 * CreateSession validates the form and starts the session as a background job,
 * returning the job id. Its outcome surfaces in the jobs UI.
 */
export function CreateSession(req: dispatch$0.CreateSessionRequest): $CancellablePromise<number> {
    return $Call.ByID(4281714313, req);
}

/**
 * ListSessions returns the active sessions the terminal picker offers; Slug is
 * the tmux target an attach uses.
 */
export function ListSessions(): $CancellablePromise<dispatch$0.SessionSummary[] | null> {
    return $Call.ByID(220196846);
}

export function SessionLaunchOptions(): $CancellablePromise<dispatch$0.SessionLaunchOptions> {
    return $Call.ByID(715924228);
}
