// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService exposes user-tunable settings to the frontend. The JSON
 * shapes below are the wire contract; the core deals in Durations and plain
 * maps.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AppearanceSettings(): $CancellablePromise<$models.AppearanceSettings> {
    return $Call.ByID(2122138421);
}

export function ExperimentalSettings(): $CancellablePromise<$models.ExperimentalSettings> {
    return $Call.ByID(1419259869);
}

export function GithubSettings(): $CancellablePromise<$models.GithubSettings> {
    return $Call.ByID(1295591268);
}

export function KeybindingSettings(): $CancellablePromise<$models.KeybindingSettings> {
    return $Call.ByID(3547481147);
}

/**
 * MonospaceFonts lists the monospace families installed on this machine, for
 * the terminal's font picker. The webview cannot enumerate them itself —
 * queryLocalFonts is Chromium-only and macOS runs on WKWebView.
 * 
 * The scan is cached for the process, so a font installed while the app runs
 * appears on the next launch.
 */
export function MonospaceFonts(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2340474665);
}

export function NotificationSettings(): $CancellablePromise<$models.NotificationSettings> {
    return $Call.ByID(256290300);
}

export function SetExperimentalTerminal(enabled: boolean): $CancellablePromise<$models.ExperimentalSettings> {
    return $Call.ByID(1793440840, enabled);
}

/**
 * SetGithubSettings converts the wire's seconds to a duration and hands it to
 * the core, which owns the floor and the live apply. A negative or absurd
 * value is caught here because it cannot be represented as a duration at all.
 */
export function SetGithubSettings($in: $models.GithubSettings): $CancellablePromise<void> {
    return $Call.ByID(3274038292, $in);
}

export function SetKeybindingSettings($in: $models.KeybindingSettings): $CancellablePromise<void> {
    return $Call.ByID(2513481483, $in);
}

export function SetNotificationSettings($in: $models.NotificationSettings): $CancellablePromise<void> {
    return $Call.ByID(460333036, $in);
}

export function SetTerminalFontFamily(family: string): $CancellablePromise<void> {
    return $Call.ByID(2359069387, family);
}

export function SetTerminalFontSize(size: string): $CancellablePromise<void> {
    return $Call.ByID(736291786, size);
}

export function SetTerminalFontWeights(weight: number, weightBold: number): $CancellablePromise<void> {
    return $Call.ByID(749037916, weight, weightBold);
}

export function SetTerminalPoolSize(size: number): $CancellablePromise<void> {
    return $Call.ByID(3703274857, size);
}

export function SetTerminalShowWindows(show: boolean): $CancellablePromise<void> {
    return $Call.ByID(2890059572, show);
}

/**
 * The appearance setters are per-field so the theme picker and the terminal
 * font picker cannot clobber each other's persisted value.
 */
export function SetTheme(theme: string): $CancellablePromise<void> {
    return $Call.ByID(2875194419, theme);
}
