// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService exposes user-tunable desktop settings to the frontend.
 * Saving persists settings.yaml and applies supported values to the running
 * services immediately.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AppearanceSettings returns the persisted appearance configuration. An empty
 * Theme tells the frontend no choice has been recorded, which is its cue to
 * adopt whatever theme its localStorage cache already holds.
 */
export function AppearanceSettings(): $CancellablePromise<$models.AppearanceSettings> {
    return $Call.ByID(2122138421);
}

/**
 * GithubSettings returns the current resolved GitHub polling settings.
 */
export function GithubSettings(): $CancellablePromise<$models.GithubSettings> {
    return $Call.ByID(1295591268);
}

/**
 * KeybindingSettings returns the persisted shortcut overrides. A nil map is
 * normalized to an empty one so the frontend never has to null-check it.
 */
export function KeybindingSettings(): $CancellablePromise<$models.KeybindingSettings> {
    return $Call.ByID(3547481147);
}

/**
 * NotificationSettings returns the current resolved notification settings.
 */
export function NotificationSettings(): $CancellablePromise<$models.NotificationSettings> {
    return $Call.ByID(256290300);
}

/**
 * SetAppearanceSettings persists the appearance configuration while preserving
 * all unrelated desktop settings.
 */
export function SetAppearanceSettings($in: $models.AppearanceSettings): $CancellablePromise<void> {
    return $Call.ByID(215032261, $in);
}

/**
 * SetGithubSettings validates, persists, and immediately applies the GitHub
 * poll interval. API callers below the floor are rejected rather than clamped.
 */
export function SetGithubSettings($in: $models.GithubSettings): $CancellablePromise<void> {
    return $Call.ByID(3274038292, $in);
}

/**
 * SetKeybindingSettings persists the shortcut overrides while preserving all
 * unrelated desktop settings. An empty map clears the section entirely, which
 * is how "reset everything to defaults" is expressed.
 */
export function SetKeybindingSettings($in: $models.KeybindingSettings): $CancellablePromise<void> {
    return $Call.ByID(2513481483, $in);
}

/**
 * SetNotificationSettings persists the notification configuration while
 * preserving all unrelated desktop settings.
 */
export function SetNotificationSettings($in: $models.NotificationSettings): $CancellablePromise<void> {
    return $Call.ByID(460333036, $in);
}
