// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SkillsService installs the paste-ready prompts as agent skills — the installer
 * surface behind Settings ▸ Skills. Every method returns the whole catalog so a
 * mutation and a read are the same shape; the input carries the frontend-owned
 * command catalog the keyboard-shortcuts skill needs, exactly as PromptsService.
 * 
 * Transport only. Rendering, installation, and drift detection live in the core
 * (internal/app/skills, app.SkillsService).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../../app/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as prompts$0 from "../../app/prompts/models.js";

export function Catalog(input: prompts$0.Input): $CancellablePromise<app$0.SkillsCatalog> {
    return $Call.ByID(1566658668, input);
}

export function InstallTarget(input: prompts$0.Input, targetID: string): $CancellablePromise<app$0.SkillsTargetResult> {
    return $Call.ByID(909052637, input, targetID);
}

export function SetAutoUpdate(input: prompts$0.Input, enabled: boolean): $CancellablePromise<app$0.SkillsCatalog> {
    return $Call.ByID(3505849477, input, enabled);
}

export function SetTargetDir(input: prompts$0.Input, targetID: string, dir: string): $CancellablePromise<app$0.SkillsCatalog> {
    return $Call.ByID(977488945, input, targetID, dir);
}

export function Sync(input: prompts$0.Input): $CancellablePromise<app$0.SkillsSyncResult> {
    return $Call.ByID(2693915070, input);
}

export function UninstallTarget(input: prompts$0.Input, targetID: string): $CancellablePromise<app$0.SkillsTargetResult> {
    return $Call.ByID(2750298160, input, targetID);
}
