// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemService exposes the desktop app's on-disk locations (data dir, config
 * dir, log file, database) to the System settings screen, along with the
 * actions that screen offers: open/reveal a path in the OS, pick a new
 * directory, and persist point-only data/config directory overrides.
 * 
 * Directory overrides are point-only and take effect after a restart: they are
 * written to the bootstrap pointer file (see internal/settings.Bootstrap) and
 * seeded into the environment at next launch. Nothing is moved.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Build returns the version, commit, and date this desktop app was built from,
 * plus a link to the matching GitHub release when the build corresponds to a
 * published version.
 */
export function Build(): $CancellablePromise<$models.BuildInfo> {
    return $Call.ByID(660083870);
}

/**
 * ChooseDirectory opens a native directory picker and returns the chosen path,
 * or "" if the user cancels. Used by the Change… actions before SetDataDir /
 * SetConfigDir.
 */
export function ChooseDirectory(title: string): $CancellablePromise<string> {
    return $Call.ByID(1021218838, title);
}

/**
 * ClearConfigDir removes the config-directory override.
 */
export function ClearConfigDir(): $CancellablePromise<void> {
    return $Call.ByID(551453092);
}

/**
 * ClearDataDir removes the data-directory override, reverting to the default
 * location on the next launch.
 */
export function ClearDataDir(): $CancellablePromise<void> {
    return $Call.ByID(2071939710);
}

/**
 * Info returns the effective locations for this running process plus whether
 * the data/config directories are backed by a stored override.
 */
export function Info(): $CancellablePromise<$models.SystemInfo> {
    return $Call.ByID(1101836886);
}

/**
 * OpenPath opens one of the known system locations in the OS default
 * application. The path is validated against the current location set so this
 * RPC cannot be used to open arbitrary files.
 */
export function OpenPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(998581101, path);
}

/**
 * Quit terminates the app so the user can relaunch and apply a directory
 * override in one click from the restart-required banner.
 */
export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(666721581);
}

/**
 * RevealPath reveals one of the known system locations in the OS file manager.
 * Validated the same way as OpenPath.
 */
export function RevealPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(1872839052, path);
}

/**
 * SetConfigDir persists a config-directory override (profiles/flows/actions).
 * Same semantics as SetDataDir.
 */
export function SetConfigDir(path: string): $CancellablePromise<void> {
    return $Call.ByID(908885759, path);
}

/**
 * SetDataDir persists a data-directory override. It validates the target and
 * creates it if missing, but does not move existing data — the override takes
 * effect on the next launch.
 */
export function SetDataDir(path: string): $CancellablePromise<void> {
    return $Call.ByID(2908604437, path);
}
