// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemService exposes the app's on-disk locations to the System settings
 * screen, plus the two things only a GUI can do: pick a directory natively
 * and quit. Everything else — the path allowlist, the override validation
 * with its write probe — is core logic behind app.SystemService.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Build returns the version, commit, and date this desktop app was built from.
 */
export function Build(): $CancellablePromise<$models.BuildInfo> {
    return $Call.ByID(660083870);
}

/**
 * ChooseDirectory opens a native directory picker and returns the chosen path,
 * or "" if the user cancels. GUI-only, so it stays here.
 */
export function ChooseDirectory(title: string): $CancellablePromise<string> {
    return $Call.ByID(1021218838, title);
}

/**
 * ClearConfigDir removes the config-directory override.
 */
export function ClearConfigDir(): $CancellablePromise<void> {
    return $Call.ByID(551453092);
}

/**
 * ClearDataDir removes the data-directory override.
 */
export function ClearDataDir(): $CancellablePromise<void> {
    return $Call.ByID(2071939710);
}

/**
 * Info returns the effective locations for this running process plus whether
 * the data/config directories are backed by a stored override.
 */
export function Info(): $CancellablePromise<$models.SystemInfo> {
    return $Call.ByID(1101836886);
}

/**
 * OpenPath opens one of the known system locations in the OS default
 * application. The core validates the path against the current location set,
 * so this RPC cannot be used to open arbitrary files.
 */
export function OpenPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(998581101, path);
}

/**
 * Quit terminates the app so the user can relaunch and apply a directory
 * override in one click from the restart-required banner. GUI-only.
 */
export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(666721581);
}

/**
 * RevealPath reveals one of the known system locations in the OS file manager.
 */
export function RevealPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(1872839052, path);
}

/**
 * SetConfigDir persists a config-directory override (flows, actions).
 */
export function SetConfigDir(path: string): $CancellablePromise<void> {
    return $Call.ByID(908885759, path);
}

/**
 * SetDataDir persists a data-directory override. It takes effect on the next
 * launch; nothing is moved.
 */
export function SetDataDir(path: string): $CancellablePromise<void> {
    return $Call.ByID(2908604437, path);
}
