// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TerminalService gates terminal mode and hands the webview its transport. The
 * data path itself never crosses the Wails bridge.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Available answers even when the loopback server is down, which is why it
 * composes tmux availability with the transport's own reachability.
 */
export function Available(): $CancellablePromise<$models.TerminalAvailability> {
    return $Call.ByID(1009187906);
}

/**
 * Endpoint reports where the terminal server is reachable, or KindUnavailable
 * while the loopback server is unbound or HTTP is disabled.
 */
export function Endpoint(): $CancellablePromise<$models.TerminalEndpoint> {
    return $Call.ByID(2785709422);
}
