// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TerminalService gates terminal mode and hands the webview its transport. The
 * data path itself never crosses the Wails bridge.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../../app/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Available answers even when the loopback server is down, which is why it
 * composes tmux availability with the transport's own reachability.
 */
export function Available(): $CancellablePromise<$models.TerminalAvailability> {
    return $Call.ByID(1009187906);
}

/**
 * Enabled reports the experimental.terminal opt-in (ADR 0037). The frontend
 * renders the way into terminal mode only when it is on; availability stays a
 * separate axis, because an enabled-but-unavailable terminal explains itself
 * inside the mode instead of hiding the way in.
 */
export function Enabled(): $CancellablePromise<boolean> {
    return $Call.ByID(1465995536);
}

/**
 * Endpoint reports where the terminal server is reachable, or KindUnavailable
 * while the loopback server is unbound or HTTP is disabled.
 */
export function Endpoint(): $CancellablePromise<$models.TerminalEndpoint> {
    return $Call.ByID(2785709422);
}

/**
 * Scratch declares the scratch terminal the session tree pins above the
 * repositories: the tmux session to attach to, and what to call it. It is
 * constant for the run, so the tree reads it once beside the session list.
 */
export function Scratch(): $CancellablePromise<app$0.ScratchTerminal> {
    return $Call.ByID(1213064263);
}
