// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WebhookService is the Wails service exposing the local webhook listener's
 * endpoint info, its user-tunable settings, and each webhook-source node's
 * last captured delivery to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Capture returns the last request body POSTed to a webhook-source node,
 * with the non-blocking feed-shape verdict the editor surfaces (a payload
 * missing feed-item fields ingests fine but renders minimally in feeds).
 */
export function Capture(flowID: string, nodeID: string): $CancellablePromise<$models.WebhookCaptureView> {
    return $Call.ByID(2352578020, flowID, nodeID);
}

/**
 * GeneratePort returns a fresh random port from the generation range without
 * persisting it: the settings pane offers it as a candidate, and saving is
 * what commits it.
 */
export function GeneratePort(): $CancellablePromise<number> {
    return $Call.ByID(1791720346);
}

/**
 * Info returns the listener's state and the base URL webhook-source paths
 * are served under (endpoint URL = BaseURL + node path).
 */
export function Info(): $CancellablePromise<$models.WebhookInfo> {
    return $Call.ByID(2309675334);
}

/**
 * SetSettings persists the enable toggle and port, preserving all unrelated
 * desktop settings. Neither is applied to the running listener: both are
 * startup-time decisions, and Settings reports the pending restart.
 */
export function SetSettings(next: $models.WebhookSettings): $CancellablePromise<void> {
    return $Call.ByID(2412382875, next);
}

/**
 * Settings returns the persisted webhook configuration alongside the state of
 * this session's listener.
 */
export function Settings(): $CancellablePromise<$models.WebhookSettings> {
    return $Call.ByID(2255886723);
}
