// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Job is one action-run lifecycle row. ID, CreatedAt, and UpdatedAt are
 * assigned by the store. CreatedAt and UpdatedAt are unix milliseconds. Step
 * is a human label derived from Status in v1.
 */
export interface Job {
    "id": number;
    "createdAt": number;
    "updatedAt": number;
    "status": JobStatus;
    "label": string;
    "step": string;
    "actionId": string;
    "target": string;
    "error"?: string;
    "commandId"?: number | null;
}

/**
 * JobStatus is a job's lifecycle stage.
 * 
 * ENUM(queued, running, done, failed)
 */
export type JobStatus = string;
