// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as hiveconf$0 from "./hiveconf/models.js";

/**
 * HiveSetup is the external Hive configuration as the first-run and settings
 * screens see it: what the file declares, what this machine could run, and
 * whether the environment is overriding the choice.
 */
export interface HiveSetup {
    "config": hiveconf$0.Setup;

    /**
     * Agents is the catalog marked by what resolved on the launch PATH.
     */
    "agents": hiveconf$0.AgentOption[] | null;

    /**
     * DefaultAgentOverride is HIVE_DEFAULT_AGENT when it is set and names a
     * profile the file declares — that is, when it would actually win over
     * agents.default at load. It is reported rather than hidden because
     * without it, a user who exports the variable picks an agent in the UI,
     * sees it saved, and watches sessions start with a different one.
     */
    "defaultAgentOverride": string;
}

/**
 * HiveSetupRequest is a whole edit, not a delta: the screen holds every
 * profile and every workspace while it is open, so a save reconciles the file
 * to exactly this set. Profiles the screen loaded and did not touch come back
 * unchanged, which is what keeps a hand-written profile from being dropped by
 * an edit that was only about workspaces.
 */
export interface HiveSetupRequest {
    "defaultAgent": string;
    "profiles": hiveconf$0.Profile[] | null;
    "workspaces": string[] | null;
}

/**
 * Integration is one card on the Integrations screen: a projection of the
 * registry, not a second list — an unregistered connector is not an
 * integration. Cards are grouped by credentials provider, so a provider that
 * ships several connector types (Grafana's metrics and alerts) shows as one
 * card; a connector with no provider (the webhook listener) is keyed by its
 * type.
 */
export interface Integration {
    "key": string;
    "title": string;
    "stability": string;

    /**
     * Provider is empty when the connector needs no credential, which also means
     * the account fields below are meaningless rather than merely empty.
     */
    "provider": string;
    "types": string[] | null;

    /**
     * Accounts is every connected account for Provider, sorted. Names only — a
     * value never leaves the credential store.
     */
    "accounts": string[] | null;

    /**
     * EnvOverride reports this provider's environment override is set, which
     * authenticates every fetch without a stored account. Without it a headless
     * or CI run would show "Not connected" beside a working feed.
     */
    "envOverride": boolean;
}

export interface MenuBarFeedChoice {
    "feed": string;
    "profileName": string;
    "folder": string;
    "name": string;
}

export interface MenuBarPin {
    "feed": string;
    "limit": number;
}

/**
 * PopupLauncher is one configured launcher, as much of it as a menu needs.
 * What it runs is deliberately absent: a caller invokes it by id.
 */
export interface PopupLauncher {
    "id": string;
    "label": string;
    "icon": string;

    /**
     * RequiresSession reports that this launcher opens wherever the terminal on
     * screen is, so a surface offering it with no terminal attached is offering
     * a launch the core will refuse (ADR quick-terminal-launchers-are-session-scoped).
     */
    "requiresSession": boolean;
}

/**
 * ScratchTerminal declares the scratch terminal to the surfaces that draw it.
 * There is exactly one, it is created on first use, and it holds no hive
 * session, checkout or agent — its tabs are whatever the user opened.
 */
export interface ScratchTerminal {
    "slug": string;
    "name": string;
}
