// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Integration is one connector family as the Integrations screen shows it: what
 * the registry declares about it, plus what the credential store currently
 * holds for it.
 * 
 * It is a projection of the registry, not a second list. A connector that is
 * not registered is not an integration — there is no "coming soon" entry,
 * because a card a user cannot act on is a promise the code does not make.
 * 
 * Cards are grouped by credentials provider: a provider that ships several
 * connector types (Grafana's metrics and alerts) shows as one card, because
 * connecting a stack authenticates both. A connector with no provider (the
 * webhook listener is local ingress) is its own card, keyed by its type.
 */
export interface Integration {
    /**
     * Key identifies the card: the credentials provider for a credentialed
     * connector ("github", "grafana"), else the connector type
     * ("sources.webhook"). The frontend keys its icon and drawer off it.
     */
    "key": string;
    "title": string;
    "stability": string;

    /**
     * Provider is the credentials provider, empty when the connector needs no
     * credential. Empty means the account fields below are meaningless rather
     * than merely empty: a webhook listener is not "not connected".
     */
    "provider": string;

    /**
     * Types are the connector node types this card covers, sorted. A family
     * like Grafana lists several; a single-type connector lists one.
     */
    "types": string[] | null;

    /**
     * Accounts is every connected account for Provider, sorted. Names only —
     * a value never leaves the credential store.
     */
    "accounts": string[] | null;

    /**
     * EnvOverride reports that this provider's environment override is set,
     * which authenticates every fetch without any stored account. Without it
     * a headless or CI run would show "Not connected" beside a working feed.
     */
    "envOverride": boolean;
}

/**
 * SkillEntry is one installable skill, shown as an informational list entry with
 * its preview text. The install state is per agent, not per skill, so it lives on
 * SkillTarget rather than here.
 */
export interface SkillEntry {
    "id": string;
    "name": string;
    "title": string;
    "description": string;

    /**
     * Target names the surface the underlying prompt configures (a path or URL),
     * shown for orientation.
     */
    "target": string;

    /**
     * rendered body, for preview and copy
     */
    "text": string;
}

/**
 * SkillTarget is one agent destination with its resolved directory and install
 * state. Installed is how many skills are on this agent (0 means "off"); NeedsSync
 * is set when an on agent has a skill missing or drifted that Sync would fix.
 */
export interface SkillTarget {
    "id": string;
    "label": string;

    /**
     * configured directory (override or default), as entered
     */
    "dir": string;

    /**
     * true when using the built-in default
     */
    "default": boolean;
    "installed": number;
    "needsSync": boolean;
}

/**
 * SkillsCatalog is the whole Skills settings surface in one value, so the
 * frontend renders and every mutation returns the same shape.
 */
export interface SkillsCatalog {
    "skills": SkillEntry[] | null;
    "targets": SkillTarget[] | null;
    "autoUpdate": boolean;
}

/**
 * SkillsSyncResult is what a provisioning sync did, so the UI can report it.
 */
export interface SkillsSyncResult {
    "catalog": SkillsCatalog;

    /**
     * newly written
     */
    "installed": number;

    /**
     * app-changed, rewritten
     */
    "updated": number;

    /**
     * missing file recreated
     */
    "restored": number;

    /**
     * user-edited, left untouched
     */
    "skipped": number;
}

/**
 * SkillsTargetResult is what turning one agent on or off did.
 */
export interface SkillsTargetResult {
    "catalog": SkillsCatalog;

    /**
     * skills installed or removed
     */
    "count": number;

    /**
     * user-edited files left in place (uninstall only)
     */
    "kept": number;
}
