// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Integration is one connector family as the Integrations screen shows it: what
 * the registry declares about it, plus what the credential store currently
 * holds for it.
 * 
 * It is a projection of the registry, not a second list. A connector that is
 * not registered is not an integration — there is no "coming soon" entry,
 * because a card a user cannot act on is a promise the code does not make.
 * 
 * Cards are grouped by credentials provider: a provider that ships several
 * connector types (Grafana's metrics and alerts) shows as one card, because
 * connecting a stack authenticates both. A connector with no provider (the
 * webhook listener is local ingress) is its own card, keyed by its type.
 */
export interface Integration {
    /**
     * Key identifies the card: the credentials provider for a credentialed
     * connector ("github", "grafana"), else the connector type
     * ("sources.webhook"). The frontend keys its icon and drawer off it.
     */
    "key": string;
    "title": string;
    "stability": string;

    /**
     * Provider is the credentials provider, empty when the connector needs no
     * credential. Empty means the account fields below are meaningless rather
     * than merely empty: a webhook listener is not "not connected".
     */
    "provider": string;

    /**
     * Types are the connector node types this card covers, sorted. A family
     * like Grafana lists several; a single-type connector lists one.
     */
    "types": string[] | null;

    /**
     * Accounts is every connected account for Provider, sorted. Names only —
     * a value never leaves the credential store.
     */
    "accounts": string[] | null;

    /**
     * EnvOverride reports that this provider's environment override is set,
     * which authenticates every fetch without any stored account. Without it
     * a headless or CI run would show "Not connected" beside a working feed.
     */
    "envOverride": boolean;
}
