// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FlowsService is the Wails service exposing the desktop pipeline's flow
 * definitions to the frontend graph editor. All data comes from the
 * injected *flow.FlowStore; this type is wire glue only, matching
 * FeedService/PipelineService's thin-glue style.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as flow$0 from "../internal/desktop/pipeline/flow/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateFlow seeds a new flow (a new "profile") named name and returns its
 * listing summary, so the frontend can select it immediately.
 */
export function CreateFlow(name: string): $CancellablePromise<$models.FlowSummary> {
    return $Call.ByID(307325216, name);
}

/**
 * DeleteFlow removes a flow (a profile) and its files before purging durable
 * pipeline state. FlowStore.Delete treats an already-missing file as success,
 * which makes a retry after a files-first partial deletion idempotent.
 */
export function DeleteFlow(id: string): $CancellablePromise<void> {
    return $Call.ByID(2980382819, id);
}

/**
 * GetFlow returns one flow's full definition for the editor.
 */
export function GetFlow(id: string): $CancellablePromise<flow$0.Flow> {
    return $Call.ByID(609138560, id);
}

/**
 * GetLayout returns a flow's node layout (canvas positions). A missing or
 * broken layout file is not an error: it returns an empty Layout so the
 * editor lays out nodes fresh.
 */
export function GetLayout(id: string): $CancellablePromise<flow$0.Layout> {
    return $Call.ByID(2624980366, id);
}

/**
 * GetSidebar returns a flow's sidebar layout: how its feed nodes are grouped
 * into folders and ordered in the sidebar's FEEDS section. A missing or broken
 * file is not an error — it returns an empty layout so the sidebar falls back
 * to flow-node order.
 */
export function GetSidebar(id: string): $CancellablePromise<flow$0.SidebarLayout> {
    return $Call.ByID(378136572, id);
}

/**
 * ListFlows returns one summary per flow file — valid and invalid alike —
 * for the flows picker.
 */
export function ListFlows(): $CancellablePromise<$models.FlowSummary[] | null> {
    return $Call.ByID(2305899597);
}

/**
 * RenameFlow changes a flow's profile-facing display name while preserving its
 * stable id and graph definition.
 */
export function RenameFlow(id: string, name: string): $CancellablePromise<$models.FlowSummary> {
    return $Call.ByID(1672705850, id, name);
}

/**
 * SaveFlow validates and persists a flow's definition. An invalid flow is
 * rejected and the last-good file on disk — and the store's served flow —
 * are left untouched.
 */
export function SaveFlow(f: flow$0.Flow): $CancellablePromise<void> {
    return $Call.ByID(2097739689, f);
}

/**
 * SaveLayout persists a flow's node layout.
 */
export function SaveLayout(id: string, layout: flow$0.Layout): $CancellablePromise<void> {
    return $Call.ByID(4232063923, id, layout);
}

/**
 * SaveSidebar persists a flow's sidebar layout (feed folders + ordering).
 */
export function SaveSidebar(id: string, layout: flow$0.SidebarLayout): $CancellablePromise<void> {
    return $Call.ByID(3551590419, id, layout);
}

/**
 * SetFlowEnabled controls whether a profile participates in polling and flow
 * execution while preserving its existing feed data and graph definition.
 */
export function SetFlowEnabled(id: string, enabled: boolean): $CancellablePromise<$models.FlowSummary> {
    return $Call.ByID(822063213, id, enabled);
}
