// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * JobService exposes live action-run jobs to the desktop frontend. The
 * titlebar reads active and briefly lingering jobs through ListActive, while
 * List provides cursor-based history paging.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as jobs$0 from "../internal/desktop/jobs/models.js";

/**
 * List returns up to limit jobs with id < before, newest first.
 */
export function List(before: number, limit: number): $CancellablePromise<jobs$0.Job[] | null> {
    return $Call.ByID(1946050826, before, limit);
}

/**
 * ListActive returns non-terminal jobs plus terminal jobs completed within the
 * backend-owned lingering window.
 */
export function ListActive(): $CancellablePromise<jobs$0.Job[] | null> {
    return $Call.ByID(2667553212);
}
