// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PipelineService is the Wails service exposing the desktop pipeline's
 * event log, configured actions, and commit protocol to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pipeline$0 from "../internal/desktop/pipeline/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as actions$0 from "../internal/desktop/pipeline/actions/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pipelinedb$0 from "../internal/desktop/pipeline/pipelinedb/models.js";

export function ActionRun(commandID: number): $CancellablePromise<pipeline$0.ActionRunView> {
    return $Call.ByID(2865983566, commandID);
}

/**
 * ActionViews returns the configured actions available for an item kind
 * ("PR"/"Issue"). The actions store is the single source for both these
 * detail-pane views and flow output actions.
 */
export function ActionViews(kind: string): $CancellablePromise<actions$0.View[] | null> {
    return $Call.ByID(2696790941, kind);
}

/**
 * ActivateReplay atomically advances the consumer and installs the prepared
 * membership state for a startup or deploy replay.
 */
export function ActivateReplay(profileID: string, tail: string, claims: pipelinedb$0.FeedMembershipClaim[] | null, feedIDs: string[] | null, sourceIDs: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(542565145, profileID, tail, claims, feedIDs, sourceIDs);
}

/**
 * Commit applies the frontend graph runtime's batch atomically. Feed outputs
 * are accepted without durable effect until membership claims land; action
 * outputs, node-run metrics, and the consumer offset are persisted atomically.
 * Idempotent by offset: replaying a batch already applied (UpToOffset <= the
 * consumer's current offset) is a no-op.
 */
export function Commit(batch: pipeline$0.CommitBatch): $CancellablePromise<void> {
    return $Call.ByID(2833242122, batch);
}

/**
 * EventLogTailOffset returns a Wails-safe decimal tail for the startup/deploy
 * replay protocol.
 */
export function EventLogTailOffset(): $CancellablePromise<string> {
    return $Call.ByID(255024248);
}

export function FeedCounts(profileID: string): $CancellablePromise<pipelinedb$0.FeedInboxCount[] | null> {
    return $Call.ByID(1308541807, profileID);
}

export function InboxItemEvents(itemID: number, limit: number): $CancellablePromise<pipelinedb$0.InboxEventView[] | null> {
    return $Call.ByID(1702778487, itemID, limit);
}

/**
 * InvokeAction records the user's explicit confirmation for actionID against
 * item and executes it. It accepts only actions that apply to the item's kind;
 * executable configuration is always re-resolved from ActionStore.
 */
export function InvokeAction(actionID: string, itemID: number, input: pipeline$0.ActionInvocationInput): $CancellablePromise<pipeline$0.ActionRunView> {
    return $Call.ByID(204589393, actionID, itemID, input);
}

/**
 * ListArchivedInboxItemsByFeed returns a feed's archived section, loaded
 * lazily when the user expands the archived divider.
 */
export function ListArchivedInboxItemsByFeed(profileID: string, feedID: string, limit: number): $CancellablePromise<pipelinedb$0.InboxItemView[] | null> {
    return $Call.ByID(2639908520, profileID, feedID, limit);
}

export function ListInboxItemsByFeed(profileID: string, feedID: string, limit: number): $CancellablePromise<pipelinedb$0.InboxItemView[] | null> {
    return $Call.ByID(4276258094, profileID, feedID, limit);
}

/**
 * ListInboxItemsTrash returns unrouted and ignored items for the Trash
 * utility view.
 */
export function ListInboxItemsTrash(profileID: string, limit: number): $CancellablePromise<pipelinedb$0.InboxItemView[] | null> {
    return $Call.ByID(719859655, profileID, limit);
}

/**
 * ListReplaySourceSnapshots returns each source's latest authoritative
 * snapshot so membership replay preserves source provenance.
 */
export function ListReplaySourceSnapshots(profileID: string, throughOffset: string): $CancellablePromise<pipelinedb$0.Msg[] | null> {
    return $Call.ByID(3644752070, profileID, throughOffset);
}

/**
 * ListUnarchivedInboxItems returns the JSON/Wails-friendly immutable inbox
 * identity and payload needed for claims-only synthetic replay.
 */
export function ListUnarchivedInboxItems(profileID: string): $CancellablePromise<pipelinedb$0.InboxItemView[] | null> {
    return $Call.ByID(3418617238, profileID);
}

export function MarkInboxItemUnread(itemID: number, revision: number, unread: boolean): $CancellablePromise<pipelinedb$0.InboxItemView> {
    return $Call.ByID(3957671458, itemID, revision, unread);
}

/**
 * NodeRuns returns up to limit of a flow's most recent node_run rows,
 * newest first, for the flows canvas's live per-node status and RECENT
 * activity list.
 */
export function NodeRuns(flowID: string, limit: number): $CancellablePromise<pipeline$0.NodeRunRecord[] | null> {
    return $Call.ByID(2130853077, flowID, limit);
}

/**
 * ReadFrom returns up to limit event_log rows after consumer's persisted
 * offset, in ascending order. The frontend never supplies an offset: the
 * SQLite checkpoint is the source of truth across runtime restarts.
 */
export function ReadFrom(consumer: string, limit: number): $CancellablePromise<pipelinedb$0.Msg[] | null> {
    return $Call.ByID(2706344123, consumer, limit);
}

/**
 * SessionLaunchOptions supplies the configured repository and agent choices
 * for interactive launch-session actions. It intentionally exposes no local
 * checkout paths or executable action configuration.
 */
export function SessionLaunchOptions(): $CancellablePromise<pipeline$0.SessionLaunchOptions> {
    return $Call.ByID(2125140544);
}

export function ToggleInboxItemArchived(itemID: number, revision: number): $CancellablePromise<pipelinedb$0.InboxItemView> {
    return $Call.ByID(2438600320, itemID, revision);
}

export function ToggleInboxItemIgnored(itemID: number, revision: number): $CancellablePromise<pipelinedb$0.InboxItemView> {
    return $Call.ByID(4199706836, itemID, revision);
}
