// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService exposes user-tunable desktop settings to the frontend.
 * Saving persists settings.yaml and applies supported values to the running
 * services immediately.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GithubSettings returns the current resolved GitHub polling settings.
 */
export function GithubSettings(): $CancellablePromise<$models.GithubSettings> {
    return $Call.ByID(2078919262);
}

/**
 * NotificationSettings returns the current resolved notification settings.
 */
export function NotificationSettings(): $CancellablePromise<$models.NotificationSettings> {
    return $Call.ByID(2998490926);
}

/**
 * SetGithubSettings validates, persists, and immediately applies the GitHub
 * poll interval. API callers below the floor are rejected rather than clamped.
 */
export function SetGithubSettings(settings: $models.GithubSettings): $CancellablePromise<void> {
    return $Call.ByID(2361435926, settings);
}

/**
 * SetNotificationSettings persists the notification configuration while
 * preserving all unrelated desktop settings.
 */
export function SetNotificationSettings(settings: $models.NotificationSettings): $CancellablePromise<void> {
    return $Call.ByID(2828604310, settings);
}
