// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WebhookService is the Wails service exposing the local webhook listener's
 * endpoint info and each webhook-source node's last captured delivery to the
 * frontend node editor.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Capture returns the last request body POSTed to a webhook-source node,
 * with the non-blocking feed-shape verdict the editor surfaces (a payload
 * missing feed-item fields ingests fine but renders minimally in feeds).
 */
export function Capture(flowID: string, nodeID: string): $CancellablePromise<$models.WebhookCaptureView> {
    return $Call.ByID(2696250954, flowID, nodeID);
}

/**
 * Info returns the listener's state and the base URL webhook-source paths
 * are served under (endpoint URL = BaseURL + node path).
 */
export function Info(): $CancellablePromise<$models.WebhookInfo> {
    return $Call.ByID(2539458276);
}
