// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * IntegrationsService exposes the connector registry and each entry's
 * connection state to the Integrations screen. The frontend re-reads it on
 * connection:updated.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../../app/models.js";

export function List(): $CancellablePromise<app$0.Integration[] | null> {
    return $Call.ByID(2370375180);
}
