// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Info(): $CancellablePromise<$models.PerfInfo> {
    return $Call.ByID(3373815408);
}

export function Record(samples: $models.PerfSample[] | null): $CancellablePromise<$models.PerfRecordResult> {
    return $Call.ByID(2483740841, samples);
}
