// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ReleaseNotesService exposes the embedded changelog: what to show once after
 * an update, and the full history the About pane lists.
 * 
 * It takes no channel. Every entry a build carries is either a stable release
 * — which the publish cascade sends to every channel — or this build's own
 * draft, so there is nothing a user on one channel must be kept from seeing.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Acknowledge records the running version as seen, so the surface does not
 * return on the next launch.
 */
export function Acknowledge(): $CancellablePromise<void> {
    return $Call.ByID(2843663663);
}

/**
 * History lists this build's draft followed by every stable release it knows
 * of, newest first.
 */
export function History(): $CancellablePromise<$models.ReleaseNote[] | null> {
    return $Call.ByID(2514746955);
}

/**
 * Pending reports what this launch should show, if anything.
 */
export function Pending(): $CancellablePromise<$models.PendingReleaseNotes> {
    return $Call.ByID(1101717552);
}
