// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SourcesService is the frontend's manual refresh. The feed's refresh command
 * and its empty-state button call it before they re-read the list, so pressing
 * refresh fetches instead of redrawing what was already stored.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Refresh drains every source now. It returns once the fetches are done, but
 * the items they produced land asynchronously — the caller reloads on the
 * "inbox:updated" event, not on this returning.
 */
export function Refresh(): $CancellablePromise<$models.RefreshResult> {
    return $Call.ByID(2633572216);
}
