// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../../encoding/json/models.js";

export interface FeedInboxCount {
    "feedId": string;
    "total": number;
    "unread": number;
    "archived": number;
}

export interface InboxEventView {
    "id": number;
    "itemId": number;
    "kind": string;
    "transition": string;
    "attention": string;
    "summary"?: string;
    "detail"?: json$0.RawMessage;
    "createdAt": number;
}

/**
 * InboxItemView is the read-side shape used by inbox callers.
 */
export interface InboxItemView {
    "id": number;
    "profileId": string;
    "sourceKind": string;
    "sourceScope": string;
    "externalId": string;
    "title": string;
    "url": string;
    "payload": json$0.RawMessage;
    "revision": number;
    "unread": boolean;
    "archivedAt"?: number | null;
    "archivedActor"?: string;
    "archivedReason"?: string;
    "lifecycle": string;
    "sourceState"?: string;
    "firstSeenAt": number;
    "lastEventAt": number;
    "ignoredAt"?: number | null;
}

/**
 * NodeRunRecord is the JSON/Wails-friendly shape of a persisted node_run
 * row, read back for the flows canvas's live status and RECENT list. It
 * carries the same fields as NodeRunView (commit.go's write-side shape)
 * plus EndedAt, which only exists once a run has actually been persisted —
 * CommitBatch stamps it server-side, so the write-side NodeRunView has no
 * use for it.
 */
export interface NodeRunRecord {
    "flowId": string;
    "nodeId": string;
    "ok": boolean;
    "inCount": number;
    "outCount": number;
    "dropCount": number;
    "err": string;
    "durMs": number;
    "endedAt": number;
}
