// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.4

// Built By: go install

package jobs

import (
	"fmt"
	"strings"
)

const (
	// JobStatusQueued is a JobStatus of type queued.
	JobStatusQueued JobStatus = "queued"
	// JobStatusRunning is a JobStatus of type running.
	JobStatusRunning JobStatus = "running"
	// JobStatusDone is a JobStatus of type done.
	JobStatusDone JobStatus = "done"
	// JobStatusFailed is a JobStatus of type failed.
	JobStatusFailed JobStatus = "failed"
)

var ErrInvalidJobStatus = fmt.Errorf("not a valid JobStatus, try [%s]", strings.Join(_JobStatusNames, ", "))

var _JobStatusNames = []string{
	string(JobStatusQueued),
	string(JobStatusRunning),
	string(JobStatusDone),
	string(JobStatusFailed),
}

// JobStatusNames returns a list of possible string values of JobStatus.
func JobStatusNames() []string {
	tmp := make([]string, len(_JobStatusNames))
	copy(tmp, _JobStatusNames)
	return tmp
}

// String implements the Stringer interface.
func (x JobStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x JobStatus) IsValid() bool {
	_, err := ParseJobStatus(string(x))
	return err == nil
}

var _JobStatusValue = map[string]JobStatus{
	"queued":  JobStatusQueued,
	"running": JobStatusRunning,
	"done":    JobStatusDone,
	"failed":  JobStatusFailed,
}

// ParseJobStatus attempts to convert a string to a JobStatus.
func ParseJobStatus(name string) (JobStatus, error) {
	if x, ok := _JobStatusValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _JobStatusValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return JobStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidJobStatus)
}

// MarshalText implements the text marshaller method.
func (x JobStatus) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *JobStatus) UnmarshalText(text []byte) error {
	tmp, err := ParseJobStatus(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *JobStatus) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
