// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../../../encoding/json/models.js";

export interface FeedCount {
    "feedId": string;
    "total": number;
    "unread": number;
    "archived": number;
}

export interface InboxEvent {
    "id": number;
    "itemId": number;
    "kind": string;
    "transition": string;
    "attention": string;
    "summary"?: string;
    "detail"?: json$0.RawMessage;
    "createdAt": number;
}

export interface InboxItem {
    "id": number;
    "profileId": string;
    "sourceKind": string;
    "sourceScope": string;
    "externalId": string;
    "title": string;
    "url": string;
    "payload": json$0.RawMessage;
    "revision": number;
    "unread": boolean;
    "archivedAt"?: number | null;
    "archivedActor"?: string;
    "archivedReason"?: string;
    "lifecycle": string;
    "sourceState"?: string;
    "firstSeenAt": number;
    "lastEventAt": number;
    "ignoredAt"?: number | null;
}

/**
 * NodeRunRecord adds persisted EndedAt to the Wails-facing node-run shape.
 */
export interface NodeRunRecord {
    "flowId": string;
    "nodeId": string;
    "ok": boolean;
    "inCount": number;
    "outCount": number;
    "dropCount": number;
    "err": string;
    "durMs": number;
    "endedAt": number;
}
