// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.4

// Built By: go install

package schedule

import (
	"fmt"
	"strings"
)

const (
	// OnMissedRun is a OnMissed of type run.
	OnMissedRun OnMissed = "run"
	// OnMissedSkip is a OnMissed of type skip.
	OnMissedSkip OnMissed = "skip"
)

var ErrInvalidOnMissed = fmt.Errorf("not a valid OnMissed, try [%s]", strings.Join(_OnMissedNames, ", "))

var _OnMissedNames = []string{
	string(OnMissedRun),
	string(OnMissedSkip),
}

// OnMissedNames returns a list of possible string values of OnMissed.
func OnMissedNames() []string {
	tmp := make([]string, len(_OnMissedNames))
	copy(tmp, _OnMissedNames)
	return tmp
}

// String implements the Stringer interface.
func (x OnMissed) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x OnMissed) IsValid() bool {
	_, err := ParseOnMissed(string(x))
	return err == nil
}

var _OnMissedValue = map[string]OnMissed{
	"run":  OnMissedRun,
	"skip": OnMissedSkip,
}

// ParseOnMissed attempts to convert a string to a OnMissed.
func ParseOnMissed(name string) (OnMissed, error) {
	if x, ok := _OnMissedValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _OnMissedValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return OnMissed(""), fmt.Errorf("%s is %w", name, ErrInvalidOnMissed)
}

// MarshalText implements the text marshaller method.
func (x OnMissed) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *OnMissed) UnmarshalText(text []byte) error {
	tmp, err := ParseOnMissed(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *OnMissed) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// ReasonDue is a Reason of type due.
	ReasonDue Reason = "due"
	// ReasonCatchUp is a Reason of type catch_up.
	ReasonCatchUp Reason = "catch_up"
	// ReasonManual is a Reason of type manual.
	ReasonManual Reason = "manual"
)

var ErrInvalidReason = fmt.Errorf("not a valid Reason, try [%s]", strings.Join(_ReasonNames, ", "))

var _ReasonNames = []string{
	string(ReasonDue),
	string(ReasonCatchUp),
	string(ReasonManual),
}

// ReasonNames returns a list of possible string values of Reason.
func ReasonNames() []string {
	tmp := make([]string, len(_ReasonNames))
	copy(tmp, _ReasonNames)
	return tmp
}

// String implements the Stringer interface.
func (x Reason) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Reason) IsValid() bool {
	_, err := ParseReason(string(x))
	return err == nil
}

var _ReasonValue = map[string]Reason{
	"due":      ReasonDue,
	"catch_up": ReasonCatchUp,
	"manual":   ReasonManual,
}

// ParseReason attempts to convert a string to a Reason.
func ParseReason(name string) (Reason, error) {
	if x, ok := _ReasonValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _ReasonValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return Reason(""), fmt.Errorf("%s is %w", name, ErrInvalidReason)
}

// MarshalText implements the text marshaller method.
func (x Reason) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Reason) UnmarshalText(text []byte) error {
	tmp, err := ParseReason(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *Reason) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// StatusLaunched is a Status of type launched.
	StatusLaunched Status = "launched"
	// StatusFailed is a Status of type failed.
	StatusFailed Status = "failed"
	// StatusSkipped is a Status of type skipped.
	StatusSkipped Status = "skipped"
)

var ErrInvalidStatus = fmt.Errorf("not a valid Status, try [%s]", strings.Join(_StatusNames, ", "))

var _StatusNames = []string{
	string(StatusLaunched),
	string(StatusFailed),
	string(StatusSkipped),
}

// StatusNames returns a list of possible string values of Status.
func StatusNames() []string {
	tmp := make([]string, len(_StatusNames))
	copy(tmp, _StatusNames)
	return tmp
}

// String implements the Stringer interface.
func (x Status) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Status) IsValid() bool {
	_, err := ParseStatus(string(x))
	return err == nil
}

var _StatusValue = map[string]Status{
	"launched": StatusLaunched,
	"failed":   StatusFailed,
	"skipped":  StatusSkipped,
}

// ParseStatus attempts to convert a string to a Status.
func ParseStatus(name string) (Status, error) {
	if x, ok := _StatusValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _StatusValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return Status(""), fmt.Errorf("%s is %w", name, ErrInvalidStatus)
}

// MarshalText implements the text marshaller method.
func (x Status) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Status) UnmarshalText(text []byte) error {
	tmp, err := ParseStatus(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *Status) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
