// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Category is the semantic bucket of an event. It drives the Activity view's
 * filter pills and, for non-error events, the row's icon and accent color.
 * 
 * ENUM(refresh, session, auto_action, action, config, system)
 */
export type Category = string;

/**
 * Event is one activity-log entry. ID and CreatedAt are assigned by the store
 * on append; constructors and callers leave them zero. CreatedAt is unix
 * milliseconds (see the activity_event migration for why milliseconds).
 */
export interface Event {
    "id": number;
    "createdAt": number;
    "category": Category;
    "severity": Severity;
    "title": string;
    "body"?: string;
    "source"?: string;

    /**
     * Metadata is opaque to storage and reserved for later enrichment (links,
     * ids, counts). No emit site populates it yet; it round-trips through the
     * reserved metadata column so a future write path needs no schema change.
     */
    "metadata"?: { [_ in string]?: string } | null;
}

/**
 * RecordInput is the frontend-facing shape for recording an event over the
 * Wails boundary. Category and severity are plain strings resolved (case
 * -insensitively) by [RecordInput.Event]; empty values default to system/info.
 */
export interface RecordInput {
    "category": string;
    "severity": string;
    "title": string;
    "body": string;
    "source": string;
    "metadata": { [_ in string]?: string } | null;
}

/**
 * Severity is the emphasis of an event, independent of its category: a refresh
 * that failed is Category=refresh, Severity=error. It selects error/auto row
 * styling and bridges to the toast system's matching severities.
 * 
 * ENUM(info, success, warning, error, auto)
 */
export type Severity = string;
