// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.4

// Built By: go install

package sources

import (
	"fmt"
	"strings"
)

const (
	// BackendGithub is a Backend of type github.
	BackendGithub Backend = "github"
	// BackendGitea is a Backend of type gitea.
	BackendGitea Backend = "gitea"
)

var ErrInvalidBackend = fmt.Errorf("not a valid Backend, try [%s]", strings.Join(_BackendNames, ", "))

var _BackendNames = []string{
	string(BackendGithub),
	string(BackendGitea),
}

// BackendNames returns a list of possible string values of Backend.
func BackendNames() []string {
	tmp := make([]string, len(_BackendNames))
	copy(tmp, _BackendNames)
	return tmp
}

// String implements the Stringer interface.
func (x Backend) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Backend) IsValid() bool {
	_, err := ParseBackend(string(x))
	return err == nil
}

var _BackendValue = map[string]Backend{
	"github": BackendGithub,
	"gitea":  BackendGitea,
}

// ParseBackend attempts to convert a string to a Backend.
func ParseBackend(name string) (Backend, error) {
	if x, ok := _BackendValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _BackendValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return Backend(""), fmt.Errorf("%s is %w", name, ErrInvalidBackend)
}

// MarshalText implements the text marshaller method.
func (x Backend) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Backend) UnmarshalText(text []byte) error {
	tmp, err := ParseBackend(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *Backend) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
