// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.4

// Built By: go install

package pipelinedb

import (
	"fmt"
	"strings"
)

const (
	// ArchivedActorManual is a ArchivedActor of type manual.
	ArchivedActorManual ArchivedActor = "manual"
	// ArchivedActorSystem is a ArchivedActor of type system.
	ArchivedActorSystem ArchivedActor = "system"
)

var ErrInvalidArchivedActor = fmt.Errorf("not a valid ArchivedActor, try [%s]", strings.Join(_ArchivedActorNames, ", "))

var _ArchivedActorNames = []string{
	string(ArchivedActorManual),
	string(ArchivedActorSystem),
}

// ArchivedActorNames returns a list of possible string values of ArchivedActor.
func ArchivedActorNames() []string {
	tmp := make([]string, len(_ArchivedActorNames))
	copy(tmp, _ArchivedActorNames)
	return tmp
}

// String implements the Stringer interface.
func (x ArchivedActor) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ArchivedActor) IsValid() bool {
	_, err := ParseArchivedActor(string(x))
	return err == nil
}

var _ArchivedActorValue = map[string]ArchivedActor{
	"manual": ArchivedActorManual,
	"system": ArchivedActorSystem,
}

// ParseArchivedActor attempts to convert a string to a ArchivedActor.
func ParseArchivedActor(name string) (ArchivedActor, error) {
	if x, ok := _ArchivedActorValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _ArchivedActorValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return ArchivedActor(""), fmt.Errorf("%s is %w", name, ErrInvalidArchivedActor)
}

// MarshalText implements the text marshaller method.
func (x ArchivedActor) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ArchivedActor) UnmarshalText(text []byte) error {
	tmp, err := ParseArchivedActor(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *ArchivedActor) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// AttentionActivity is a Attention of type activity.
	AttentionActivity Attention = "activity"
	// AttentionTrivial is a Attention of type trivial.
	AttentionTrivial Attention = "trivial"
)

var ErrInvalidAttention = fmt.Errorf("not a valid Attention, try [%s]", strings.Join(_AttentionNames, ", "))

var _AttentionNames = []string{
	string(AttentionActivity),
	string(AttentionTrivial),
}

// AttentionNames returns a list of possible string values of Attention.
func AttentionNames() []string {
	tmp := make([]string, len(_AttentionNames))
	copy(tmp, _AttentionNames)
	return tmp
}

// String implements the Stringer interface.
func (x Attention) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Attention) IsValid() bool {
	_, err := ParseAttention(string(x))
	return err == nil
}

var _AttentionValue = map[string]Attention{
	"activity": AttentionActivity,
	"trivial":  AttentionTrivial,
}

// ParseAttention attempts to convert a string to a Attention.
func ParseAttention(name string) (Attention, error) {
	if x, ok := _AttentionValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _AttentionValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return Attention(""), fmt.Errorf("%s is %w", name, ErrInvalidAttention)
}

// MarshalText implements the text marshaller method.
func (x Attention) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Attention) UnmarshalText(text []byte) error {
	tmp, err := ParseAttention(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *Attention) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// LifecycleActive is a Lifecycle of type active.
	LifecycleActive Lifecycle = "active"
	// LifecycleTerminal is a Lifecycle of type terminal.
	LifecycleTerminal Lifecycle = "terminal"
	// LifecycleUnknown is a Lifecycle of type unknown.
	LifecycleUnknown Lifecycle = "unknown"
)

var ErrInvalidLifecycle = fmt.Errorf("not a valid Lifecycle, try [%s]", strings.Join(_LifecycleNames, ", "))

var _LifecycleNames = []string{
	string(LifecycleActive),
	string(LifecycleTerminal),
	string(LifecycleUnknown),
}

// LifecycleNames returns a list of possible string values of Lifecycle.
func LifecycleNames() []string {
	tmp := make([]string, len(_LifecycleNames))
	copy(tmp, _LifecycleNames)
	return tmp
}

// String implements the Stringer interface.
func (x Lifecycle) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Lifecycle) IsValid() bool {
	_, err := ParseLifecycle(string(x))
	return err == nil
}

var _LifecycleValue = map[string]Lifecycle{
	"active":   LifecycleActive,
	"terminal": LifecycleTerminal,
	"unknown":  LifecycleUnknown,
}

// ParseLifecycle attempts to convert a string to a Lifecycle.
func ParseLifecycle(name string) (Lifecycle, error) {
	if x, ok := _LifecycleValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _LifecycleValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return Lifecycle(""), fmt.Errorf("%s is %w", name, ErrInvalidLifecycle)
}

// MarshalText implements the text marshaller method.
func (x Lifecycle) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Lifecycle) UnmarshalText(text []byte) error {
	tmp, err := ParseLifecycle(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *Lifecycle) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// ResurfacePolicyAll is a ResurfacePolicy of type all.
	ResurfacePolicyAll ResurfacePolicy = "all"
	// ResurfacePolicyStateChanges is a ResurfacePolicy of type state-changes.
	ResurfacePolicyStateChanges ResurfacePolicy = "state-changes"
	// ResurfacePolicyNever is a ResurfacePolicy of type never.
	ResurfacePolicyNever ResurfacePolicy = "never"
)

var ErrInvalidResurfacePolicy = fmt.Errorf("not a valid ResurfacePolicy, try [%s]", strings.Join(_ResurfacePolicyNames, ", "))

var _ResurfacePolicyNames = []string{
	string(ResurfacePolicyAll),
	string(ResurfacePolicyStateChanges),
	string(ResurfacePolicyNever),
}

// ResurfacePolicyNames returns a list of possible string values of ResurfacePolicy.
func ResurfacePolicyNames() []string {
	tmp := make([]string, len(_ResurfacePolicyNames))
	copy(tmp, _ResurfacePolicyNames)
	return tmp
}

// String implements the Stringer interface.
func (x ResurfacePolicy) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ResurfacePolicy) IsValid() bool {
	_, err := ParseResurfacePolicy(string(x))
	return err == nil
}

var _ResurfacePolicyValue = map[string]ResurfacePolicy{
	"all":           ResurfacePolicyAll,
	"state-changes": ResurfacePolicyStateChanges,
	"never":         ResurfacePolicyNever,
}

// ParseResurfacePolicy attempts to convert a string to a ResurfacePolicy.
func ParseResurfacePolicy(name string) (ResurfacePolicy, error) {
	if x, ok := _ResurfacePolicyValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _ResurfacePolicyValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return ResurfacePolicy(""), fmt.Errorf("%s is %w", name, ErrInvalidResurfacePolicy)
}

// MarshalText implements the text marshaller method.
func (x ResurfacePolicy) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ResurfacePolicy) UnmarshalText(text []byte) error {
	tmp, err := ParseResurfacePolicy(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *ResurfacePolicy) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// TransitionNone is a Transition of type none.
	TransitionNone Transition = "none"
	// TransitionEnteredTerminal is a Transition of type entered-terminal.
	TransitionEnteredTerminal Transition = "entered-terminal"
	// TransitionLeftTerminal is a Transition of type left-terminal.
	TransitionLeftTerminal Transition = "left-terminal"
)

var ErrInvalidTransition = fmt.Errorf("not a valid Transition, try [%s]", strings.Join(_TransitionNames, ", "))

var _TransitionNames = []string{
	string(TransitionNone),
	string(TransitionEnteredTerminal),
	string(TransitionLeftTerminal),
}

// TransitionNames returns a list of possible string values of Transition.
func TransitionNames() []string {
	tmp := make([]string, len(_TransitionNames))
	copy(tmp, _TransitionNames)
	return tmp
}

// String implements the Stringer interface.
func (x Transition) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Transition) IsValid() bool {
	_, err := ParseTransition(string(x))
	return err == nil
}

var _TransitionValue = map[string]Transition{
	"none":             TransitionNone,
	"entered-terminal": TransitionEnteredTerminal,
	"left-terminal":    TransitionLeftTerminal,
}

// ParseTransition attempts to convert a string to a Transition.
func ParseTransition(name string) (Transition, error) {
	if x, ok := _TransitionValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _TransitionValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return Transition(""), fmt.Errorf("%s is %w", name, ErrInvalidTransition)
}

// MarshalText implements the text marshaller method.
func (x Transition) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Transition) UnmarshalText(text []byte) error {
	tmp, err := ParseTransition(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *Transition) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
