// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pipelinedb

import (
	"database/sql"
)

type ActivityEvent struct {
	ID        int64  `json:"id"`
	CreatedAt int64  `json:"created_at"`
	Category  string `json:"category"`
	Severity  string `json:"severity"`
	Title     string `json:"title"`
	Body      string `json:"body"`
	Source    string `json:"source"`
	Metadata  []byte `json:"metadata"`
}

type ConsumerOffset struct {
	Consumer string `json:"consumer"`
	Offset   int64  `json:"offset"`
}

type EventLog struct {
	Offset        int64          `json:"offset"`
	Topic         string         `json:"topic"`
	Key           string         `json:"key"`
	Payload       []byte         `json:"payload"`
	Snapshot      int64          `json:"snapshot"`
	SourceKind    string         `json:"source_kind"`
	SourceScope   string         `json:"source_scope"`
	OccurrenceKey sql.NullString `json:"occurrence_key"`
	CreatedAt     int64          `json:"created_at"`
}

type FeedMembershipClaim struct {
	ProfileID string `json:"profile_id"`
	FeedID    string `json:"feed_id"`
	ItemID    int64  `json:"item_id"`
	SourceID  string `json:"source_id"`
}

type InboxEvent struct {
	ID            int64          `json:"id"`
	ItemID        int64          `json:"item_id"`
	Kind          string         `json:"kind"`
	Transition    string         `json:"transition"`
	Attention     string         `json:"attention"`
	OccurrenceKey sql.NullString `json:"occurrence_key"`
	Summary       sql.NullString `json:"summary"`
	Detail        []byte         `json:"detail"`
	CreatedAt     int64          `json:"created_at"`
}

type InboxItem struct {
	ID             int64          `json:"id"`
	ProfileID      string         `json:"profile_id"`
	SourceKind     string         `json:"source_kind"`
	SourceScope    string         `json:"source_scope"`
	ExternalID     string         `json:"external_id"`
	Title          string         `json:"title"`
	Url            string         `json:"url"`
	Payload        []byte         `json:"payload"`
	Revision       int64          `json:"revision"`
	Unread         int64          `json:"unread"`
	ArchivedAt     sql.NullInt64  `json:"archived_at"`
	ArchivedActor  sql.NullString `json:"archived_actor"`
	ArchivedReason sql.NullString `json:"archived_reason"`
	Lifecycle      string         `json:"lifecycle"`
	SourceState    sql.NullString `json:"source_state"`
	FirstSeenAt    int64          `json:"first_seen_at"`
	LastEventAt    int64          `json:"last_event_at"`
	IgnoredAt      sql.NullInt64  `json:"ignored_at"`
}

type Job struct {
	ID        int64         `json:"id"`
	CreatedAt int64         `json:"created_at"`
	UpdatedAt int64         `json:"updated_at"`
	Status    string        `json:"status"`
	Label     string        `json:"label"`
	Step      string        `json:"step"`
	ActionID  string        `json:"action_id"`
	Target    string        `json:"target"`
	Error     string        `json:"error"`
	CommandID sql.NullInt64 `json:"command_id"`
}

type NodeRun struct {
	FlowID    string         `json:"flow_id"`
	NodeID    string         `json:"node_id"`
	Ok        int64          `json:"ok"`
	InCount   int64          `json:"in_count"`
	OutCount  int64          `json:"out_count"`
	DropCount int64          `json:"drop_count"`
	Err       sql.NullString `json:"err"`
	EndedAt   int64          `json:"ended_at"`
	DurMs     int64          `json:"dur_ms"`
}

type OutputCommand struct {
	ID         int64          `json:"id"`
	ActionID   string         `json:"action_id"`
	Key        string         `json:"key"`
	Payload    []byte         `json:"payload"`
	Status     string         `json:"status"`
	Attempts   int64          `json:"attempts"`
	LastError  sql.NullString `json:"last_error"`
	ResultJson sql.NullString `json:"result_json"`
	Stdout     sql.NullString `json:"stdout"`
	Stderr     sql.NullString `json:"stderr"`
	CreatedAt  int64          `json:"created_at"`
	IsRerun    int64          `json:"is_rerun"`
}

type SourceHead struct {
	Topic   string `json:"topic"`
	Key     string `json:"key"`
	Payload []byte `json:"payload"`
}
