// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EditableAction is the explicit, non-executable editor contract exposed to
 * desktop clients. Exactly one config branch must be set and it must match
 * Type; callers cannot send an untyped executable blob.
 */
export interface EditableAction {
    "id": string;
    "label": string;
    "type": string;
    "showInDetail": boolean;
    "appliesTo": string[] | null;
    "launch"?: EditableLaunchConfig | null;
    "shell"?: EditableShellConfig | null;
    "message"?: EditableMessageConfig | null;
}

/**
 * EditableCatalog returns the effective last-good catalog and any error from
 * parsing the latest file. It lets the settings UI remain useful while making
 * a hand-edited malformed actions.yml visible to the user.
 */
export interface EditableCatalog {
    "actions": EditableAction[] | null;
    "error": string;
}

export interface EditableLaunchConfig {
    "promptTemplate": string;
    "agent"?: string;
    "repoTemplate"?: string;
}

export interface EditableMessageConfig {
    "messageTemplate": string;
    "topic": string;
}

export interface EditableShellConfig {
    "commandTemplate": string;
    "cwd"?: string;
    "timeout"?: string;
    "env"?: { [_ in string]?: string } | null;
}

/**
 * View is the complete action contract exposed to the desktop frontend. It
 * deliberately excludes executable configuration: the frontend can present
 * and identify an action, but execution always resolves its current
 * definition from ActionStore.
 */
export interface View {
    "id": string;
    "label": string;
    "type": string;
    "showInDetail": boolean;
    "requiresSessionInput": boolean;
}
