// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../../../encoding/json/models.js";

/**
 * CommitBatch is the frontend graph runtime's atomic write: it advances a
 * consumer's committed offset and persists the outputs/node-run metrics
 * produced while processing up to that offset, all in one transaction (see
 * DB.CommitBatch).
 */
export interface CommitBatch {
    /**
     * event_log consumer key (flow id / consumer id)
     */
    "consumer": string;

    /**
     * decimal event-log offset; strings preserve int64 precision across Wails
     */
    "upToOffset": string;
    "outputs": Output[] | null;
    "feedSnapshots": FeedSnapshot[] | null;
    "discards": Discard[] | null;
    "nodeRuns": NodeRunView[] | null;
}

/**
 * Discard records a message a node dropped instead of forwarding, for
 * metrics/observability. CommitBatch does not persist Discards as rows —
 * they exist for callers that want to log or count them; the per-node
 * aggregate is expected to already be reflected in the corresponding
 * NodeRun.DropCount.
 */
export interface Discard {
    "msgId": string;
    "nodeId": string;
}

export interface FeedInboxCount {
    "feedId": string;
    "total": number;
    "unread": number;
}

export interface FeedMembershipClaim {
    "profile_id": string;
    "feed_id": string;
    "item_id": number;
    "source_id": string;
}

/**
 * FeedSnapshot declares one source's complete current output scope for a feed.
 * CommitBatch accepts these declarations but does not persist reconciliation
 * state until membership claims are introduced.
 */
export interface FeedSnapshot {
    "feedId": string;
    "sourceTopic": string;
    "snapshotId": string;
}

export interface InboxCounts {
    "inboxTotal": number;
    "inboxUnread": number;
}

export interface InboxEventView {
    "id": number;
    "itemId": number;
    "kind": string;
    "transition": string;
    "attention": string;
    "summary"?: string;
    "detail"?: json$0.RawMessage;
    "createdAt": number;
}

/**
 * InboxItemView is the read-side shape used by inbox callers.
 */
export interface InboxItemView {
    "id": number;
    "profileId": string;
    "sourceKind": string;
    "sourceScope": string;
    "externalId": string;
    "title": string;
    "url": string;
    "payload": json$0.RawMessage;
    "revision": number;
    "unread": boolean;
    "archivedAt"?: number | null;
    "archivedActor"?: string;
    "archivedReason"?: string;
    "lifecycle": string;
    "sourceState"?: string;
    "firstSeenAt": number;
    "lastEventAt": number;
    "ignoredAt"?: number | null;
}

/**
 * Msg is the pipeline's generic log record, appended by sources and consumed
 * by the frontend graph runtime.
 * 
 * It mirrors the design's { id, key, topic, ts, payload } contract,
 * with Snapshot populated only for an authoritative full-source snapshot,
 * mapped onto the event_log schema (see migrations/0001_pipeline.up.sql):
 *   - ID is derived from the row's "offset" (stable, unique per append; there
 *     is no separate id column).
 *   - Ts is the row's created_at (unix milliseconds).
 *   - Snapshot is nil for ordinary item events and contains the full current
 *     source item set for successful poll snapshots.
 */
export interface Msg {
    "ID": string;
    "Key": string;
    "Topic": string;
    "Ts": number;
    "Payload": json$0.RawMessage;
    "Snapshot"?: SnapshotItem[] | null;
    "SourceKind": string;
    "SourceScope": string;
    "OccurrenceKey"?: string;
}

/**
 * NodeRunRecord is the JSON/Wails-friendly shape of a persisted node_run
 * row, read back for the flows canvas's live status and RECENT list. It
 * carries the same fields as NodeRunView (commit.go's write-side shape)
 * plus EndedAt, which only exists once a run has actually been persisted —
 * CommitBatch stamps it server-side, so the write-side NodeRunView has no
 * use for it.
 */
export interface NodeRunRecord {
    "flowId": string;
    "nodeId": string;
    "ok": boolean;
    "inCount": number;
    "outCount": number;
    "dropCount": number;
    "err": string;
    "durMs": number;
    "endedAt": number;
}

/**
 * NodeRunView is one node's per-tick execution summary, recorded for the
 * flows debug/status UI. It is named "View" (rather than NodeRun) only to
 * avoid colliding with the sqlc-generated raw row model of the same name in
 * models.go — package pipeline's NodeRun alias re-exports this type under
 * the name callers actually use (see pipeline/commit.go).
 */
export interface NodeRunView {
    "flowId": string;
    "nodeId": string;
    "ok": boolean;
    "inCount": number;
    "outCount": number;
    "dropCount": number;
    "err": string;
    "durMs": number;
}

/**
 * Output is one committed side effect of a flow run.
 */
export interface Output {
    "sink": Sink;

    /**
     * feed external ID only
     */
    "key"?: string;

    /**
     * action dedup key only
     */
    "occurrenceKey"?: string;

    /**
     * action payload only
     */
    "payload"?: json$0.RawMessage;
    "sourceKind"?: string;
    "sourceScope"?: string;
    "sourceTopic": string;
    "snapshotId"?: string;
}

/**
 * Sink identifies where an Output is committed. Feed outputs claim immutable
 * inbox membership; action outputs enqueue an output_command.
 */
export interface Sink {
    "kind": string;
    "targetId": string;
}

/**
 * SnapshotItem is one current source item carried by a successful source
 * snapshot. A snapshot event is distinct from ordinary changed-item events:
 * it is emitted on every successful poll, including when the source is empty.
 */
export interface SnapshotItem {
    "key": string;
    "payload": json$0.RawMessage;
}
