// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_hc.sql

package db

import (
	"context"
	"strings"

	"github.com/hay-kot/hive-desktop/internal/hivecore/core/hc"
)

const addHCBlocker = `-- name: AddHCBlocker :exec

INSERT OR IGNORE INTO hc_task_blockers (blocker_id, blocked_id) VALUES (?, ?)
`

type AddHCBlockerParams struct {
	BlockerID string `json:"blocker_id"`
	BlockedID string `json:"blocked_id"`
}

// HC Task Blockers
func (q *Queries) AddHCBlocker(ctx context.Context, arg AddHCBlockerParams) error {
	_, err := q.db.ExecContext(ctx, addHCBlocker, arg.BlockerID, arg.BlockedID)
	return err
}

const countHCItemsByStatusOlderThan = `-- name: CountHCItemsByStatusOlderThan :one
SELECT COUNT(*) FROM hc_items WHERE status = ? AND updated_at < ?
`

type CountHCItemsByStatusOlderThanParams struct {
	Status    hc.Status `json:"status"`
	UpdatedAt int64     `json:"updated_at"`
}

func (q *Queries) CountHCItemsByStatusOlderThan(ctx context.Context, arg CountHCItemsByStatusOlderThanParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countHCItemsByStatusOlderThan, arg.Status, arg.UpdatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countHCOpenChildren = `-- name: CountHCOpenChildren :one
SELECT COUNT(*) FROM hc_items
WHERE parent_id = ? AND status IN ('open', 'in_progress')
`

func (q *Queries) CountHCOpenChildren(ctx context.Context, parentID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countHCOpenChildren, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHCItem = `-- name: CreateHCItem :exec

INSERT INTO hc_items (id, repo_key, epic_id, parent_id, session_id, title, desc, type, status, depth, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateHCItemParams struct {
	ID        string      `json:"id"`
	RepoKey   string      `json:"repo_key"`
	EpicID    string      `json:"epic_id"`
	ParentID  string      `json:"parent_id"`
	SessionID string      `json:"session_id"`
	Title     string      `json:"title"`
	Desc      string      `json:"desc"`
	Type      hc.ItemType `json:"type"`
	Status    hc.Status   `json:"status"`
	Depth     int64       `json:"depth"`
	CreatedAt int64       `json:"created_at"`
	UpdatedAt int64       `json:"updated_at"`
}

// HC Items
func (q *Queries) CreateHCItem(ctx context.Context, arg CreateHCItemParams) error {
	_, err := q.db.ExecContext(ctx, createHCItem,
		arg.ID,
		arg.RepoKey,
		arg.EpicID,
		arg.ParentID,
		arg.SessionID,
		arg.Title,
		arg.Desc,
		arg.Type,
		arg.Status,
		arg.Depth,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteHCCommentsByItemID = `-- name: DeleteHCCommentsByItemID :exec
DELETE FROM hc_comments WHERE item_id = ?
`

func (q *Queries) DeleteHCCommentsByItemID(ctx context.Context, itemID string) error {
	_, err := q.db.ExecContext(ctx, deleteHCCommentsByItemID, itemID)
	return err
}

const deleteHCItem = `-- name: DeleteHCItem :exec
DELETE FROM hc_items WHERE id = ?
`

func (q *Queries) DeleteHCItem(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteHCItem, id)
	return err
}

const deleteHCItemsByStatusOlderThan = `-- name: DeleteHCItemsByStatusOlderThan :exec
DELETE FROM hc_items WHERE status = ? AND updated_at < ?
`

type DeleteHCItemsByStatusOlderThanParams struct {
	Status    hc.Status `json:"status"`
	UpdatedAt int64     `json:"updated_at"`
}

func (q *Queries) DeleteHCItemsByStatusOlderThan(ctx context.Context, arg DeleteHCItemsByStatusOlderThanParams) error {
	_, err := q.db.ExecContext(ctx, deleteHCItemsByStatusOlderThan, arg.Status, arg.UpdatedAt)
	return err
}

const getHCItem = `-- name: GetHCItem :one
SELECT id, repo_key, epic_id, parent_id, session_id, title, "desc", type, status, depth, created_at, updated_at FROM hc_items WHERE id = ?
`

func (q *Queries) GetHCItem(ctx context.Context, id string) (HcItem, error) {
	row := q.db.QueryRowContext(ctx, getHCItem, id)
	var i HcItem
	err := row.Scan(
		&i.ID,
		&i.RepoKey,
		&i.EpicID,
		&i.ParentID,
		&i.SessionID,
		&i.Title,
		&i.Desc,
		&i.Type,
		&i.Status,
		&i.Depth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertHCComment = `-- name: InsertHCComment :one

INSERT INTO hc_comments (id, item_id, message, created_at)
VALUES (?, ?, ?, ?)
RETURNING id, item_id, message, created_at
`

type InsertHCCommentParams struct {
	ID        string `json:"id"`
	ItemID    string `json:"item_id"`
	Message   string `json:"message"`
	CreatedAt int64  `json:"created_at"`
}

// HC Comments
func (q *Queries) InsertHCComment(ctx context.Context, arg InsertHCCommentParams) (HcComment, error) {
	row := q.db.QueryRowContext(ctx, insertHCComment,
		arg.ID,
		arg.ItemID,
		arg.Message,
		arg.CreatedAt,
	)
	var i HcComment
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const listAllHCBlockerEdges = `-- name: ListAllHCBlockerEdges :many
SELECT blocker_id, blocked_id FROM hc_task_blockers
`

func (q *Queries) ListAllHCBlockerEdges(ctx context.Context) ([]HcTaskBlocker, error) {
	rows, err := q.db.QueryContext(ctx, listAllHCBlockerEdges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HcTaskBlocker{}
	for rows.Next() {
		var i HcTaskBlocker
		if err := rows.Scan(&i.BlockerID, &i.BlockedID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllHCItems = `-- name: ListAllHCItems :many
SELECT id, repo_key, epic_id, parent_id, session_id, title, "desc", type, status, depth, created_at, updated_at FROM hc_items ORDER BY created_at DESC
`

func (q *Queries) ListAllHCItems(ctx context.Context) ([]HcItem, error) {
	rows, err := q.db.QueryContext(ctx, listAllHCItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HcItem{}
	for rows.Next() {
		var i HcItem
		if err := rows.Scan(
			&i.ID,
			&i.RepoKey,
			&i.EpicID,
			&i.ParentID,
			&i.SessionID,
			&i.Title,
			&i.Desc,
			&i.Type,
			&i.Status,
			&i.Depth,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllHCItemsByStatus = `-- name: ListAllHCItemsByStatus :many
SELECT id, repo_key, epic_id, parent_id, session_id, title, "desc", type, status, depth, created_at, updated_at FROM hc_items WHERE status = ? ORDER BY created_at DESC
`

func (q *Queries) ListAllHCItemsByStatus(ctx context.Context, status hc.Status) ([]HcItem, error) {
	rows, err := q.db.QueryContext(ctx, listAllHCItemsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HcItem{}
	for rows.Next() {
		var i HcItem
		if err := rows.Scan(
			&i.ID,
			&i.RepoKey,
			&i.EpicID,
			&i.ParentID,
			&i.SessionID,
			&i.Title,
			&i.Desc,
			&i.Type,
			&i.Status,
			&i.Depth,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHCBlockedParentIDs = `-- name: ListHCBlockedParentIDs :many
SELECT DISTINCT parent_id FROM hc_items
WHERE parent_id != '' AND status IN ('open', 'in_progress')
`

func (q *Queries) ListHCBlockedParentIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listHCBlockedParentIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var parent_id string
		if err := rows.Scan(&parent_id); err != nil {
			return nil, err
		}
		items = append(items, parent_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHCBlockersForItem = `-- name: ListHCBlockersForItem :many
SELECT blocker_id FROM hc_task_blockers WHERE blocked_id = ? ORDER BY blocker_id
`

func (q *Queries) ListHCBlockersForItem(ctx context.Context, blockedID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listHCBlockersForItem, blockedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var blocker_id string
		if err := rows.Scan(&blocker_id); err != nil {
			return nil, err
		}
		items = append(items, blocker_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHCComments = `-- name: ListHCComments :many
SELECT id, item_id, message, created_at FROM hc_comments WHERE item_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListHCComments(ctx context.Context, itemID string) ([]HcComment, error) {
	rows, err := q.db.QueryContext(ctx, listHCComments, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HcComment{}
	for rows.Next() {
		var i HcComment
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHCEpics = `-- name: ListHCEpics :many
SELECT id, repo_key, epic_id, parent_id, session_id, title, "desc", type, status, depth, created_at, updated_at FROM hc_items WHERE type = 'epic' ORDER BY created_at DESC
`

func (q *Queries) ListHCEpics(ctx context.Context) ([]HcItem, error) {
	rows, err := q.db.QueryContext(ctx, listHCEpics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HcItem{}
	for rows.Next() {
		var i HcItem
		if err := rows.Scan(
			&i.ID,
			&i.RepoKey,
			&i.EpicID,
			&i.ParentID,
			&i.SessionID,
			&i.Title,
			&i.Desc,
			&i.Type,
			&i.Status,
			&i.Depth,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHCEpicsByRepo = `-- name: ListHCEpicsByRepo :many
SELECT id, repo_key, epic_id, parent_id, session_id, title, "desc", type, status, depth, created_at, updated_at FROM hc_items WHERE type = 'epic' AND repo_key = ? ORDER BY created_at DESC
`

func (q *Queries) ListHCEpicsByRepo(ctx context.Context, repoKey string) ([]HcItem, error) {
	rows, err := q.db.QueryContext(ctx, listHCEpicsByRepo, repoKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HcItem{}
	for rows.Next() {
		var i HcItem
		if err := rows.Scan(
			&i.ID,
			&i.RepoKey,
			&i.EpicID,
			&i.ParentID,
			&i.SessionID,
			&i.Title,
			&i.Desc,
			&i.Type,
			&i.Status,
			&i.Depth,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHCExplicitlyBlockedIDs = `-- name: ListHCExplicitlyBlockedIDs :many
SELECT DISTINCT blocked_id FROM hc_task_blockers
JOIN hc_items ON hc_items.id = hc_task_blockers.blocker_id
WHERE hc_items.status IN ('open', 'in_progress')
`

func (q *Queries) ListHCExplicitlyBlockedIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listHCExplicitlyBlockedIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var blocked_id string
		if err := rows.Scan(&blocked_id); err != nil {
			return nil, err
		}
		items = append(items, blocked_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHCExplicitlyBlockedIDsWithBlockers = `-- name: ListHCExplicitlyBlockedIDsWithBlockers :many
SELECT DISTINCT b.blocked_id FROM hc_task_blockers b
JOIN hc_items i ON i.id = b.blocker_id
WHERE i.status IN ('open', 'in_progress')
  AND b.blocked_id IN (/*SLICE:ids*/?)
`

func (q *Queries) ListHCExplicitlyBlockedIDsWithBlockers(ctx context.Context, ids []string) ([]string, error) {
	query := listHCExplicitlyBlockedIDsWithBlockers
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var blocked_id string
		if err := rows.Scan(&blocked_id); err != nil {
			return nil, err
		}
		items = append(items, blocked_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHCItemsBlockedBy = `-- name: ListHCItemsBlockedBy :many
SELECT blocked_id FROM hc_task_blockers WHERE blocker_id = ? ORDER BY blocked_id
`

func (q *Queries) ListHCItemsBlockedBy(ctx context.Context, blockerID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listHCItemsBlockedBy, blockerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var blocked_id string
		if err := rows.Scan(&blocked_id); err != nil {
			return nil, err
		}
		items = append(items, blocked_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHCItemsByEpic = `-- name: ListHCItemsByEpic :many
SELECT id, repo_key, epic_id, parent_id, session_id, title, "desc", type, status, depth, created_at, updated_at FROM hc_items WHERE epic_id = ? ORDER BY depth ASC, created_at ASC
`

func (q *Queries) ListHCItemsByEpic(ctx context.Context, epicID string) ([]HcItem, error) {
	rows, err := q.db.QueryContext(ctx, listHCItemsByEpic, epicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HcItem{}
	for rows.Next() {
		var i HcItem
		if err := rows.Scan(
			&i.ID,
			&i.RepoKey,
			&i.EpicID,
			&i.ParentID,
			&i.SessionID,
			&i.Title,
			&i.Desc,
			&i.Type,
			&i.Status,
			&i.Depth,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHCItemsByEpicAndStatus = `-- name: ListHCItemsByEpicAndStatus :many
SELECT id, repo_key, epic_id, parent_id, session_id, title, "desc", type, status, depth, created_at, updated_at FROM hc_items WHERE epic_id = ? AND status = ? ORDER BY depth ASC, created_at ASC
`

type ListHCItemsByEpicAndStatusParams struct {
	EpicID string    `json:"epic_id"`
	Status hc.Status `json:"status"`
}

func (q *Queries) ListHCItemsByEpicAndStatus(ctx context.Context, arg ListHCItemsByEpicAndStatusParams) ([]HcItem, error) {
	rows, err := q.db.QueryContext(ctx, listHCItemsByEpicAndStatus, arg.EpicID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HcItem{}
	for rows.Next() {
		var i HcItem
		if err := rows.Scan(
			&i.ID,
			&i.RepoKey,
			&i.EpicID,
			&i.ParentID,
			&i.SessionID,
			&i.Title,
			&i.Desc,
			&i.Type,
			&i.Status,
			&i.Depth,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHCItemsByRepo = `-- name: ListHCItemsByRepo :many
SELECT id, repo_key, epic_id, parent_id, session_id, title, "desc", type, status, depth, created_at, updated_at FROM hc_items WHERE repo_key = ? ORDER BY created_at ASC
`

func (q *Queries) ListHCItemsByRepo(ctx context.Context, repoKey string) ([]HcItem, error) {
	rows, err := q.db.QueryContext(ctx, listHCItemsByRepo, repoKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HcItem{}
	for rows.Next() {
		var i HcItem
		if err := rows.Scan(
			&i.ID,
			&i.RepoKey,
			&i.EpicID,
			&i.ParentID,
			&i.SessionID,
			&i.Title,
			&i.Desc,
			&i.Type,
			&i.Status,
			&i.Depth,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHCItemsBySession = `-- name: ListHCItemsBySession :many
SELECT id, repo_key, epic_id, parent_id, session_id, title, "desc", type, status, depth, created_at, updated_at FROM hc_items WHERE session_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListHCItemsBySession(ctx context.Context, sessionID string) ([]HcItem, error) {
	rows, err := q.db.QueryContext(ctx, listHCItemsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HcItem{}
	for rows.Next() {
		var i HcItem
		if err := rows.Scan(
			&i.ID,
			&i.RepoKey,
			&i.EpicID,
			&i.ParentID,
			&i.SessionID,
			&i.Title,
			&i.Desc,
			&i.Type,
			&i.Status,
			&i.Depth,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHCOpenBlockerIDsForItem = `-- name: ListHCOpenBlockerIDsForItem :many
SELECT b.blocker_id FROM hc_task_blockers b
JOIN hc_items i ON i.id = b.blocker_id
WHERE b.blocked_id = ? AND i.status IN ('open', 'in_progress')
ORDER BY b.blocker_id
`

func (q *Queries) ListHCOpenBlockerIDsForItem(ctx context.Context, blockedID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listHCOpenBlockerIDsForItem, blockedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var blocker_id string
		if err := rows.Scan(&blocker_id); err != nil {
			return nil, err
		}
		items = append(items, blocker_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHCRepoKeys = `-- name: ListHCRepoKeys :many
SELECT DISTINCT repo_key FROM hc_items WHERE repo_key != '' ORDER BY repo_key
`

func (q *Queries) ListHCRepoKeys(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listHCRepoKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var repo_key string
		if err := rows.Scan(&repo_key); err != nil {
			return nil, err
		}
		items = append(items, repo_key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextHCItemForSession = `-- name: NextHCItemForSession :one
SELECT outer_item.id, outer_item.repo_key, outer_item.epic_id, outer_item.parent_id, outer_item.session_id, outer_item.title, outer_item."desc", outer_item.type, outer_item.status, outer_item.depth, outer_item.created_at, outer_item.updated_at FROM hc_items AS outer_item
WHERE outer_item.session_id = ?
  AND outer_item.status = 'open'
  AND outer_item.id NOT IN (
    SELECT DISTINCT inner_item.parent_id FROM hc_items AS inner_item
    WHERE inner_item.parent_id != '' AND inner_item.status IN ('open', 'in_progress')
  )
  AND outer_item.id NOT IN (
    SELECT DISTINCT b.blocked_id FROM hc_task_blockers b
    JOIN hc_items blocker ON blocker.id = b.blocker_id
    WHERE blocker.status IN ('open', 'in_progress')
  )
ORDER BY outer_item.depth DESC, outer_item.created_at ASC
LIMIT 1
`

func (q *Queries) NextHCItemForSession(ctx context.Context, sessionID string) (HcItem, error) {
	row := q.db.QueryRowContext(ctx, nextHCItemForSession, sessionID)
	var i HcItem
	err := row.Scan(
		&i.ID,
		&i.RepoKey,
		&i.EpicID,
		&i.ParentID,
		&i.SessionID,
		&i.Title,
		&i.Desc,
		&i.Type,
		&i.Status,
		&i.Depth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const nextHCItemForSessionInEpic = `-- name: NextHCItemForSessionInEpic :one
SELECT outer_item.id, outer_item.repo_key, outer_item.epic_id, outer_item.parent_id, outer_item.session_id, outer_item.title, outer_item."desc", outer_item.type, outer_item.status, outer_item.depth, outer_item.created_at, outer_item.updated_at FROM hc_items AS outer_item
WHERE outer_item.session_id = ?
  AND outer_item.epic_id = ?
  AND outer_item.status = 'open'
  AND outer_item.id NOT IN (
    SELECT DISTINCT inner_item.parent_id FROM hc_items AS inner_item
    WHERE inner_item.parent_id != '' AND inner_item.status IN ('open', 'in_progress')
  )
  AND outer_item.id NOT IN (
    SELECT DISTINCT b.blocked_id FROM hc_task_blockers b
    JOIN hc_items blocker ON blocker.id = b.blocker_id
    WHERE blocker.status IN ('open', 'in_progress')
  )
ORDER BY outer_item.depth DESC, outer_item.created_at ASC
LIMIT 1
`

type NextHCItemForSessionInEpicParams struct {
	SessionID string `json:"session_id"`
	EpicID    string `json:"epic_id"`
}

func (q *Queries) NextHCItemForSessionInEpic(ctx context.Context, arg NextHCItemForSessionInEpicParams) (HcItem, error) {
	row := q.db.QueryRowContext(ctx, nextHCItemForSessionInEpic, arg.SessionID, arg.EpicID)
	var i HcItem
	err := row.Scan(
		&i.ID,
		&i.RepoKey,
		&i.EpicID,
		&i.ParentID,
		&i.SessionID,
		&i.Title,
		&i.Desc,
		&i.Type,
		&i.Status,
		&i.Depth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const pruneHCCommentsByStatus = `-- name: PruneHCCommentsByStatus :exec
DELETE FROM hc_comments
WHERE hc_comments.item_id IN (
    SELECT hc_items.id
    FROM hc_items
    WHERE hc_items.status = ? AND hc_items.updated_at < ?
)
`

type PruneHCCommentsByStatusParams struct {
	Status    hc.Status `json:"status"`
	UpdatedAt int64     `json:"updated_at"`
}

func (q *Queries) PruneHCCommentsByStatus(ctx context.Context, arg PruneHCCommentsByStatusParams) error {
	_, err := q.db.ExecContext(ctx, pruneHCCommentsByStatus, arg.Status, arg.UpdatedAt)
	return err
}

const removeHCBlocker = `-- name: RemoveHCBlocker :exec
DELETE FROM hc_task_blockers WHERE blocker_id = ? AND blocked_id = ?
`

type RemoveHCBlockerParams struct {
	BlockerID string `json:"blocker_id"`
	BlockedID string `json:"blocked_id"`
}

func (q *Queries) RemoveHCBlocker(ctx context.Context, arg RemoveHCBlockerParams) error {
	_, err := q.db.ExecContext(ctx, removeHCBlocker, arg.BlockerID, arg.BlockedID)
	return err
}

const resumeHCItemForSession = `-- name: ResumeHCItemForSession :one
SELECT outer_item.id, outer_item.repo_key, outer_item.epic_id, outer_item.parent_id, outer_item.session_id, outer_item.title, outer_item."desc", outer_item.type, outer_item.status, outer_item.depth, outer_item.created_at, outer_item.updated_at FROM hc_items AS outer_item
WHERE outer_item.session_id = ?
  AND outer_item.status = 'in_progress'
  AND outer_item.id NOT IN (
    SELECT DISTINCT inner_item.parent_id FROM hc_items AS inner_item
    WHERE inner_item.parent_id != '' AND inner_item.status IN ('open', 'in_progress')
  )
ORDER BY outer_item.depth DESC, outer_item.created_at ASC
LIMIT 1
`

func (q *Queries) ResumeHCItemForSession(ctx context.Context, sessionID string) (HcItem, error) {
	row := q.db.QueryRowContext(ctx, resumeHCItemForSession, sessionID)
	var i HcItem
	err := row.Scan(
		&i.ID,
		&i.RepoKey,
		&i.EpicID,
		&i.ParentID,
		&i.SessionID,
		&i.Title,
		&i.Desc,
		&i.Type,
		&i.Status,
		&i.Depth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resumeHCItemForSessionInEpic = `-- name: ResumeHCItemForSessionInEpic :one
SELECT outer_item.id, outer_item.repo_key, outer_item.epic_id, outer_item.parent_id, outer_item.session_id, outer_item.title, outer_item."desc", outer_item.type, outer_item.status, outer_item.depth, outer_item.created_at, outer_item.updated_at FROM hc_items AS outer_item
WHERE outer_item.session_id = ?
  AND outer_item.epic_id = ?
  AND outer_item.status = 'in_progress'
  AND outer_item.id NOT IN (
    SELECT DISTINCT inner_item.parent_id FROM hc_items AS inner_item
    WHERE inner_item.parent_id != '' AND inner_item.status IN ('open', 'in_progress')
  )
ORDER BY outer_item.depth DESC, outer_item.created_at ASC
LIMIT 1
`

type ResumeHCItemForSessionInEpicParams struct {
	SessionID string `json:"session_id"`
	EpicID    string `json:"epic_id"`
}

func (q *Queries) ResumeHCItemForSessionInEpic(ctx context.Context, arg ResumeHCItemForSessionInEpicParams) (HcItem, error) {
	row := q.db.QueryRowContext(ctx, resumeHCItemForSessionInEpic, arg.SessionID, arg.EpicID)
	var i HcItem
	err := row.Scan(
		&i.ID,
		&i.RepoKey,
		&i.EpicID,
		&i.ParentID,
		&i.SessionID,
		&i.Title,
		&i.Desc,
		&i.Type,
		&i.Status,
		&i.Depth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateHCItem = `-- name: UpdateHCItem :exec
UPDATE hc_items SET status = ?, session_id = ?, title = ?, desc = ?, updated_at = ? WHERE id = ?
`

type UpdateHCItemParams struct {
	Status    hc.Status `json:"status"`
	SessionID string    `json:"session_id"`
	Title     string    `json:"title"`
	Desc      string    `json:"desc"`
	UpdatedAt int64     `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdateHCItem(ctx context.Context, arg UpdateHCItemParams) error {
	_, err := q.db.ExecContext(ctx, updateHCItem,
		arg.Status,
		arg.SessionID,
		arg.Title,
		arg.Desc,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateHCItemStatusByEpicID = `-- name: UpdateHCItemStatusByEpicID :exec
UPDATE hc_items
SET status = ?, updated_at = ?
WHERE epic_id = ?
  AND status NOT IN ('done', 'cancelled')
`

type UpdateHCItemStatusByEpicIDParams struct {
	Status    hc.Status `json:"status"`
	UpdatedAt int64     `json:"updated_at"`
	EpicID    string    `json:"epic_id"`
}

func (q *Queries) UpdateHCItemStatusByEpicID(ctx context.Context, arg UpdateHCItemStatusByEpicIDParams) error {
	_, err := q.db.ExecContext(ctx, updateHCItemStatusByEpicID, arg.Status, arg.UpdatedAt, arg.EpicID)
	return err
}
