package main

import (
	"bufio"
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"unicode"
)

func writeDotenvAtomic(path string, values map[string]string) error {
	var output strings.Builder
	output.WriteString("# Generated by cmd/devtools. Do not edit; run `mise run desktop:dev:fresh`.\n")
	for _, key := range sortedKeys(values) {
		if !validEnvKey(key) {
			return fmt.Errorf("invalid environment key %q", key)
		}
		output.WriteString(key)
		output.WriteByte('=')
		output.WriteString(strconv.Quote(values[key]))
		output.WriteByte('\n')
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	file, err := os.CreateTemp(filepath.Dir(path), ".launch-*.env")
	if err != nil {
		return fmt.Errorf("create temporary launch environment: %w", err)
	}
	temp := file.Name()
	defer func() { _ = os.Remove(temp) }()
	if err := file.Chmod(0o600); err != nil {
		_ = file.Close()
		return err
	}
	if _, err := file.WriteString(output.String()); err != nil {
		_ = file.Close()
		return err
	}
	if err := file.Sync(); err != nil {
		_ = file.Close()
		return err
	}
	if err := file.Close(); err != nil {
		return err
	}
	if err := os.Rename(temp, path); err != nil {
		return fmt.Errorf("replace launch environment: %w", err)
	}
	return nil
}

func parseDotenv(data []byte) (map[string]string, error) {
	values := make(map[string]string)
	scanner := bufio.NewScanner(bytes.NewReader(data))
	for lineNumber := 1; scanner.Scan(); lineNumber++ {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, encoded, ok := strings.Cut(line, "=")
		if !ok || !validEnvKey(key) {
			return nil, fmt.Errorf("line %d: expected NAME=quoted-value", lineNumber)
		}
		if _, exists := values[key]; exists {
			return nil, fmt.Errorf("line %d: duplicate key %s", lineNumber, key)
		}
		value, err := strconv.Unquote(encoded)
		if err != nil {
			return nil, fmt.Errorf("line %d: value must be a Go-compatible quoted string: %w", lineNumber, err)
		}
		values[key] = value
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	return values, nil
}

func validEnvKey(key string) bool {
	if key == "" {
		return false
	}
	for index, r := range key {
		if index == 0 && r != '_' && !unicode.IsUpper(r) {
			return false
		}
		if r != '_' && !unicode.IsUpper(r) && !unicode.IsDigit(r) {
			return false
		}
	}
	return true
}
