// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ActionInvocationInput contains only user-supplied action inputs. It never
 * carries executable configuration or message attribution.
 */
export interface ActionInvocationInput {
    "session"?: SessionInvocationInput | null;

    /**
     * Inputs are the values collected for the action's declared inputs, keyed
     * by input name. They are validated against the catalog's declaration on
     * every invocation, so a name the action does not declare is refused.
     */
    "inputs"?: { [_ in string]?: string } | null;
    "rerun"?: boolean;
}

export interface ActionRunView {
    "commandId": number;
    "status": string;
    "result"?: ExecutionOutcome | null;
    "error"?: string;
    "stdout"?: string;
    "stderr"?: string;
    "confirmationRequired"?: boolean;
}

/**
 * ClipboardExecutionOutcome carries the text a clipboard action rendered. The
 * clipboard write itself is the desktop adapter's: the core produces the text
 * and the frontend copies it (see the detail-pane render path), so this is the
 * executor's whole result.
 */
export interface ClipboardExecutionOutcome {
    "text": string;
}

/**
 * CreateSessionRequest is a user-submitted New Session form. ItemID is the
 * inbox item the form was drafted from, or 0 for a blank one; it is an id
 * rather than a ref because the core resolves the item's identity itself and
 * never takes it from a client.
 */
export interface CreateSessionRequest {
    "repository": string;
    "name": string;
    "prompt": string;
    "agent"?: string;
    "itemId"?: number;
}

/**
 * ExecutionOutcome is a tagged-by-presence union. Exactly one branch is set
 * for successful side-effecting executors.
 */
export interface ExecutionOutcome {
    "session"?: SessionExecutionOutcome | null;
    "message"?: MessageExecutionOutcome | null;
    "clipboard"?: ClipboardExecutionOutcome | null;
}

/**
 * ItemSessionView is one hive session an inbox item spawned. Only CreatedAt
 * comes from the link — everything else is read live from hive, so a session
 * renamed or recycled outside this app reports what it actually is.
 */
export interface ItemSessionView {
    "id": string;
    "name": string;
    "slug": string;
    "repo": string;
    "state": string;
    "running": boolean;
    "createdAt": string;
}

export interface MessageExecutionOutcome {
    "topic": string;
    "sender": string;
}

/**
 * PullRequestStatus is why a session has no pull request to show, or that it
 * does. The four are kept apart deliberately: a bar that renders "no pull
 * request" for a failed lookup or a disconnected account tells the user the
 * branch has none, which is a different and wrong fact.
 */
export enum PullRequestStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * PullRequestStatusNone reports a branch GitHub has no pull request for.
     */
    PullRequestStatusNone = "none",

    /**
     * PullRequestStatusFound reports one, described by the rest of the view.
     */
    PullRequestStatusFound = "found",

    /**
     * PullRequestStatusDisconnected reports that no GitHub account is
     * connected, so nothing was asked.
     */
    PullRequestStatusDisconnected = "disconnected",

    /**
     * PullRequestStatusUnsupported reports a session whose remote is not a
     * GitHub one, or whose branch did not resolve.
     */
    PullRequestStatusUnsupported = "unsupported",
};

/**
 * SessionDetail is one session read in full, for a detail view.
 */
export interface SessionDetail {
    "id": string;
    "name": string;
    "slug": string;
    "repo": string;
    "state": string;
    "path": string;
    "cloneStrategy": string;
    "worktreeBranch": string;
    "tags": string[] | null;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * SessionDraft is a New Session form prefilled from an inbox item.
 */
export interface SessionDraft {
    "repository": string;
    "name": string;
    "prompt": string;
}

export interface SessionExecutionOutcome {
    "id": string;
    "name": string;
}

/**
 * SessionGitStatus is one session's checkout as the session status bar reads
 * it. Resolved separates "git answered" from the zero value, so a bar can tell
 * a clean branch from a session it has not read yet or cannot read at all;
 * Error carries why when a read failed, and is never a substitute for it.
 */
export interface SessionGitStatus {
    "path": string;
    "branch": string;
    "dirty": boolean;
    "unpushed": boolean;

    /**
     * Additions and Deletions are lines against the default branch, not
     * against HEAD — the same figure hive's own session list shows.
     */
    "additions": number;
    "deletions": number;

    /**
     * Owner and Repo are the session remote's GitHub coordinates, empty for a
     * remote that is not a GitHub one.
     */
    "owner": string;
    "repo": string;
    "resolved": boolean;
    "error": string;
}

export interface SessionInvocationInput {
    "name": string;
    "repository": string;
    "agent"?: string;
}

/**
 * SessionLaunchOptions is the narrow DTO used by the session launch dialog.
 */
export interface SessionLaunchOptions {
    "repositories": SessionLaunchRepository[] | null;
    "defaultRepository": string;
    "agents": string[] | null;
    "defaultAgent": string;
}

/**
 * SessionLaunchRepository is the safe presentation of a repository available
 * to an interactive action. Local checkout paths stay backend-only.
 */
export interface SessionLaunchRepository {
    "name": string;
    "repository": string;
}

/**
 * SessionPullRequest is the branch's pull request as the session status bar
 * shows it. Everything below Status is meaningful only for
 * PullRequestStatusFound.
 */
export interface SessionPullRequest {
    "status": PullRequestStatus;
    "number": number;
    "title": string;
    "state": string;
    "isDraft": boolean;
    "url": string;

    /**
     * ReviewDecision is GitHub's own vocabulary — APPROVED,
     * CHANGES_REQUESTED, REVIEW_REQUIRED — or empty when review is not
     * required.
     */
    "reviewDecision": string;

    /**
     * Checks is passing, pending, failing, or empty for a head commit with no
     * checks configured.
     */
    "checks": string;

    /**
     * Additions and Deletions are the pull request's own line counts, which are
     * deliberately not SessionGitStatus's: those measure the working tree
     * against the default branch and drift the moment the branch moves on.
     */
    "additions": number;
    "deletions": number;
}

/**
 * SessionPullRequestKey addresses the pull request a session's branch has.
 * Git is what resolves the branch, so the key is built from a SessionGitStatus
 * rather than read again.
 */
export interface SessionPullRequestKey {
    "owner": string;
    "repo": string;
    "branch": string;
}

/**
 * SessionRisk is the pre-flight a destructive operation confirms against: what
 * unsaved work the session holds, and whether recycling it is really a delete.
 */
export interface SessionRisk {
    "uncommittedChanges": boolean;
    "unpushedCommits": boolean;

    /**
     * RecycleDeletes reports that recycling this session destroys it: hive
     * routes a worktree session's recycle straight to DeleteSession, because a
     * worktree has no clone of its own to reset.
     */
    "recycleDeletes": boolean;
}

/**
 * SessionStatus separates tmux liveness from the activity detected in each
 * agent window.
 */
export interface SessionStatus {
    "sessionId": string;
    "running": boolean;
    "windows": SessionWindowStatus[] | null;
}

/**
 * SessionSummary is one session as the desktop's session list sees it. Slug is
 * the tmux session name, which is what a terminal attach targets. It stays a
 * projection: the rest of a session is read on demand as a SessionDetail.
 */
export interface SessionSummary {
    "id": string;
    "name": string;
    "slug": string;
    "repo": string;
    "state": string;
}

/**
 * SessionWindowStatus is one tmux window's detected agent activity.
 */
export interface SessionWindowStatus {
    "windowId": string;
    "status": string;
    "tool": string;
}

/**
 * TerminalTarget identifies the terminal session — and optionally the window
 * inside it — an action was invoked from. It carries identity only: every
 * value a template can read is resolved from the session record at invocation
 * time, so a client cannot hand an executor a checkout path of its choosing.
 */
export interface TerminalTarget {
    "slug": string;

    /**
     * WindowID is set when the invocation came from a window row. It is what
     * separates a window invocation from a session one, and it is the tmux
     * window id, so it addresses the window across renames.
     */
    "windowId"?: string;
}
