// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ActionInvocationInput contains only user-supplied action inputs. It never
 * carries executable configuration or message attribution.
 */
export interface ActionInvocationInput {
    "session"?: SessionInvocationInput | null;

    /**
     * Inputs are the values collected for the action's declared inputs, keyed
     * by input name. They are validated against the catalog's declaration on
     * every invocation, so a name the action does not declare is refused.
     */
    "inputs"?: { [_ in string]?: string } | null;
    "rerun"?: boolean;
}

export interface ActionRunView {
    "commandId": number;
    "status": string;
    "result"?: ExecutionOutcome | null;
    "error"?: string;
    "stdout"?: string;
    "stderr"?: string;
    "confirmationRequired"?: boolean;
}

/**
 * ClipboardExecutionOutcome carries the text a clipboard action rendered. The
 * clipboard write itself is the desktop adapter's: the core produces the text
 * and the frontend copies it (see the detail-pane render path), so this is the
 * executor's whole result.
 */
export interface ClipboardExecutionOutcome {
    "text": string;
}

/**
 * CreateSessionRequest is a user-submitted New Session form.
 */
export interface CreateSessionRequest {
    "repository": string;
    "name": string;
    "prompt": string;
    "agent"?: string;
}

/**
 * ExecutionOutcome is a tagged-by-presence union. Exactly one branch is set
 * for successful side-effecting executors.
 */
export interface ExecutionOutcome {
    "session"?: SessionExecutionOutcome | null;
    "message"?: MessageExecutionOutcome | null;
    "clipboard"?: ClipboardExecutionOutcome | null;
}

export interface MessageExecutionOutcome {
    "topic": string;
    "sender": string;
}

/**
 * SessionDetail is one session read in full, for a detail view.
 */
export interface SessionDetail {
    "id": string;
    "name": string;
    "slug": string;
    "repo": string;
    "state": string;
    "path": string;
    "cloneStrategy": string;
    "worktreeBranch": string;
    "tags": string[] | null;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * SessionDraft is a New Session form prefilled from an inbox item.
 */
export interface SessionDraft {
    "repository": string;
    "name": string;
    "prompt": string;
}

export interface SessionExecutionOutcome {
    "id": string;
    "name": string;
}

export interface SessionInvocationInput {
    "name": string;
    "repository": string;
    "agent"?: string;
}

/**
 * SessionLaunchOptions is the narrow DTO used by the session launch dialog.
 */
export interface SessionLaunchOptions {
    "repositories": SessionLaunchRepository[] | null;
    "defaultRepository": string;
    "agents": string[] | null;
    "defaultAgent": string;
}

/**
 * SessionLaunchRepository is the safe presentation of a repository available
 * to an interactive action. Local checkout paths stay backend-only.
 */
export interface SessionLaunchRepository {
    "name": string;
    "repository": string;
}

/**
 * SessionRisk is the pre-flight a destructive operation confirms against: what
 * unsaved work the session holds, and whether recycling it is really a delete.
 */
export interface SessionRisk {
    "uncommittedChanges": boolean;
    "unpushedCommits": boolean;

    /**
     * RecycleDeletes reports that recycling this session destroys it: hive
     * routes a worktree session's recycle straight to DeleteSession, because a
     * worktree has no clone of its own to reset.
     */
    "recycleDeletes": boolean;
}

/**
 * SessionStatus separates tmux liveness from the activity detected in each
 * agent window.
 */
export interface SessionStatus {
    "sessionId": string;
    "running": boolean;
    "windows": SessionWindowStatus[] | null;
}

/**
 * SessionSummary is one session as the desktop's session list sees it. Slug is
 * the tmux session name, which is what a terminal attach targets. It stays a
 * projection: the rest of a session is read on demand as a SessionDetail.
 */
export interface SessionSummary {
    "id": string;
    "name": string;
    "slug": string;
    "repo": string;
    "state": string;
}

/**
 * SessionWindowStatus is one tmux window's detected agent activity.
 */
export interface SessionWindowStatus {
    "windowId": string;
    "status": string;
    "tool": string;
}
