// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Stack is the resolved identity of a connected stack, returned to the UI so it
 * can show which account a pasted URL and token resolved to.
 */
export interface Stack {
    "account": string;
    "url": string;
    "orgID": number;
    "orgName": string;
}
