// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnectionStatus is this connector's own connection state. It is the
 * connector's, not the app's: Login/Name/AvatarURL describe the connected
 * GitHub account and belong on an Integrations card, not in app chrome.
 */
export interface ConnectionStatus {
    /**
     * StateDisconnected | StateConnected
     */
    "state": string;
    "login": string;
    "name": string;
    "avatarUrl": string;

    /**
     * Message carries a user-facing problem description (invalid stored
     * token, device flow failure) without changing the state machine.
     */
    "message": string;
}

/**
 * DeviceFlowInfo is the pending device authorization the connect screen
 * renders: the user opens VerificationURI and enters UserCode.
 */
export interface DeviceFlowInfo {
    "userCode": string;
    "verificationUri": string;
}
