// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Command is one bindable command from the frontend's keybinding catalog.
 * 
 * This is the single fact the frontend owns that a prompt needs: the catalog
 * is UI (it carries icons and palette grouping) and stays in
 * desktop/frontend/src/keybindings/catalog.ts. The keybindings prompt is
 * rendered with whatever the frontend reports, so adding a command extends the
 * prompt with no change here.
 */
export interface Command {
    "id": string;
    "title": string;
    "group": string;
    "context": string;
    "defaultCombos": string[] | null;
}

/**
 * Input carries the caller-supplied context a prompt needs beyond Env. Every
 * field is optional; a prompt that needs one documents it on its definition.
 */
export interface Input {
    /**
     * Commands is the bindable command catalog, required by the keybindings
     * prompt.
     */
    "commands": Command[] | null;

    /**
     * WebhookPath and WebhookSample scope the webhook transform prompt to one
     * webhook-source node: its configured path and its last captured delivery.
     */
    "webhookPath": string;
    "webhookSample": string;
}

/**
 * Prompt is one rendered, copyable prompt.
 */
export interface Prompt {
    "id": string;

    /**
     * Title and Description label the entry in the settings catalog.
     */
    "title": string;
    "description": string;

    /**
     * Target names what the prompt configures — a path for file-backed
     * prompts, a surface name otherwise — shown under the title.
     */
    "target": string;

    /**
     * Text is the prompt itself: what the copy button puts on the clipboard.
     */
    "text": string;
}
